### ISSUE TITLE
TS6133 Unused argument options in BaseHttpRequest

### ISSUE THREAD

**Issue by vitalybaev** [ferdikoomen/openapi-typescript-codegen#1012]
<img width="771" alt="CleanShot 2022-04-01 at 11 16 28@2x" src="https://user-images.githubusercontent.com/724423/161214352-41be16cc-92f5-46c6-8a4e-2ae40787658f.png">

**Comment by ferdikoomen** [comment]
@vitalybaev There is already a change to make the BaseHttpRequest abstract: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/templates/core/BaseHttpRequest.hbs
This version has not been published, will make sure to publish a new version today, that should resolve your issue

**Comment by ferdikoomen** [comment]
@vitalybaev Pushed 0.21.0

**Comment by vitalybaev** [comment]
Thank you!
