### ISSUE TITLE
[Feature request] intercept response -- postMiddleware feature

### ISSUE THREAD

**Issue by mkusaka** [ferdikoomen/openapi-typescript-codegen#1014]
Hi 👋..
Thank you for the wonderful library.

I would like to have the feature to register a middleware that processes all responses, like the one implemented in "openapitools/openapi-generator-cli".
Do you have any plans to add such feature to this library?

A specific use case would be to retrieve the response content of headers and body returned by the server only when an error of 500 or more occurs.

Similarly https://github.com/ferdikoomen/openapi-typescript-codegen/issues/995

**Comment by ferdikoomen** [comment]
@mkusaka Closing your ticket to continue conversation in #995

**Comment by lrstanley** [comment]
@ferdikoomen looks like #995 is related to pre-request middleware, however looks like this one is for response interception. Is there a way to do this without extending a `HttpRequestConstructor`? I'd like to grab the response headers globally, and store it in a global state (in my case, ratelimit headers).

**Comment by blakehawkins** [comment]
I'd also like access to post-request context

At the moment I have no way to debug or add context to unmapped `Generic Error` in `catchErrorCodes`

**Comment by frdwhite24** [comment]
has anyone made any progress on this? i'd also love to intercept the responses just like Axios interceptors, we log 4XX errors and also parse data from snake_case to camelCase with our Axios response interceptor.

Thanks so much for the great library!
