### ISSUE TITLE
 AbortController is not defined (SSR)

### ISSUE THREAD

**Issue by utsavshrestha170** [ferdikoomen/openapi-typescript-codegen#1015]
**Describe the solution you'd like**
I am using this package for next js. While the api is being hit, i have an error 'abortcontroller is not defined'
Can we have something that could be used in both ssr and csr? That would be really helpful. Thank you

**Comment by ferdikoomen** [comment]
@utsavshrestha170 The only way to use a ssr and csr solution would be to switch to Axios, that works very nicely in NodeJS and browser environments: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/axios-support.md
