### ISSUE TITLE
Disabling certification verification

### ISSUE THREAD

**Issue by laurynas-wn** [ferdikoomen/openapi-typescript-codegen#1019]
Hey,

Recently we added SSL to our dev environment and been having issues generating the API client.

`ResolverError: Error downloading https://dev.local:9001/spec-json unable to verify the first certificate`

Is there a way to disable certificate verification for the purposes of generating the api client? Or any other way to work around this issue?

**Comment by ferdikoomen** [comment]
@laurynas-wn I have never had such issues with the project. Seems like there might be a SSL configuration issue on your side. Can you can modify the generated source code and check what 'fixes' this? Or provide an environment for me to test this again?
