### ISSUE TITLE
request.ts: getHeaders will ignore mediaType property of ApiRequestOptions object under certain circumstances

### ISSUE THREAD

**Issue by Maritims** [ferdikoomen/openapi-typescript-codegen#1022]
I'm running a Micronaut backend and have used openapi-typescript-codegen@0.21.0 to generate client code.

This behaviour is reproducible by creating a request where the formData and mediaType properties of the ApiRequestOptions object are set, but not the body property.

The getHeaders method in the file request.ts will ignore the mediaType property. This is because the mediaType is only respected if the body property of the ApiRequestOptions object is set.

The result is that you do not have any control of the Content-Type header which can result in unexpected behaviour when sending requests to your backend. I am for instance currently experiencing that my request is sent with a multipart/form-data header instead of application/x-www-form-urlencoded.

This is how I create my request:
```
return __request(OpenAPI, {
    method: 'POST',
    url: '/login',
    formData: formData,
    mediaType: 'application/x-www-form-urlencoded',
});
```

Surely it would be reasonable to expect that this request is sent with application/x-www-form-urlencoded, right?

Is this intentional or is it a bug? Any help would be appreciated. You can find the getHeaders below for your convenience.

```
const getHeaders = async (config: OpenAPIConfig, options: ApiRequestOptions): Promise<Headers> => {
    const token = await resolve(options, config.TOKEN);
    const username = await resolve(options, config.USERNAME);
    const password = await resolve(options, config.PASSWORD);
    const additionalHeaders = await resolve(options, config.HEADERS);

    const headers = Object.entries({
        Accept: 'application/json',
        ...additionalHeaders,
        ...options.headers,
    })
        .filter(([_, value]) => isDefined(value))
        .reduce((headers, [key, value]) => ({
            ...headers,
            [key]: String(value),
        }), {} as Record<string, string>);

    if (isStringWithValue(token)) {
        headers['Authorization'] = `Bearer ${token}`;
    }

    if (isStringWithValue(username) && isStringWithValue(password)) {
        const credentials = base64(`${username}:${password}`);
        headers['Authorization'] = `Basic ${credentials}`;
    }

    if (options.body) {
        if (options.mediaType) {
            headers['Content-Type'] = options.mediaType;
        } else if (isBlob(options.body)) {
            headers['Content-Type'] = options.body.type || 'application/octet-stream';
        } else if (isString(options.body)) {
            headers['Content-Type'] = 'text/plain';
        } else if (!isFormData(options.body)) {
            headers['Content-Type'] = 'application/json';
        }
    }

    return new Headers(headers);
};
```

**Comment by jgoz** [comment]
It looks like `mediaType` isn't used at all for axios clients either. Should I file a separate issue for that?

**Comment by Maritims** [comment]
> It looks like `mediaType` isn't used at all for axios clients either. Should I file a separate issue for that?

@jgoz It seems related to this issue from my perspective. Maybe it's not specific to which client implementation is chosen, but I wouldn't know. I'll have to leave it up to @ferdikoomen

**Comment by jgoz** [comment]
Looking at the templates, it seems like all of them except for axios use the same check rooted on `options.body`, while the axios template doesn't set it at all.

**Comment by ferdikoomen** [comment]
@jgoz @Maritims I just merged a PR that adds the headers for the Axios client, will publish a new version today
