### ISSUE TITLE
Cannot find name 'Blob'.

### ISSUE THREAD

**Issue by PanMan** [ferdikoomen/openapi-typescript-codegen#1023]
**Describe the bug**
A clear and concise description of what the bug is. Ideally with a screenshot of the result or a link to a small example.

Hi!
When running I get the error 
```
core/request.ts:26:39 - error TS2304: Cannot find name 'Blob'.

26 const isBlob = (value: any): value is Blob => {
```

I'm now running this to generate the client:
`"npx openapi -i ./src/docs/MewsFixed.yaml -o ./src/mewsclient --useOptions --name MewsClient --client axios"`

btw, overall I found "how to get started" with this and Node (also how to run an instance) a bit scattered to find out: eg I'm not sure I need the `--name` but without that I don't know what/how to import to run the client.

Also, I DIDN'T have to set ` "allowSyntheticDefaultImports": true` (as documented at https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/axios-support.md)

I did get the Blob error to dissapear by adding "DOM" to the `lib` in `tsconfig.json` but that feels heavy for my server side project..

**Comment by ferdikoomen** [comment]
@PanMan i added a small addition to the axios library. Yes you will need to include the "dom" library in the "lib" section. This does not make the project any bigger, but it tells Typescript what kind of libraries are available in your environment: https://www.typescriptlang.org/tsconfig#lib

Feel free to create a PR with changes in the documentation :-)
