### ISSUE TITLE
[question] Equivalent for node backends?

### ISSUE THREAD

**Issue by benjaminbillet** [ferdikoomen/openapi-typescript-codegen#1024]
Hello,
Is there some equivalent of this library for node backends (with Express support for example)? I was going to simply fork the lib because your parser is useful, but maybe you could be interested by a contribution instead?

**Comment by PanMan** [comment]
I think the generated client can also be used from Node? :)

**Comment by ferdikoomen** [comment]
@benjaminbillet You can generate a NodeJS compatible client. Documentation: 
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/node-fetch-support.md
Or by using Axios:
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/axios-support.md
