### ISSUE TITLE
Documentation for the `CancellablePromise<T>` type 

### ISSUE THREAD

**Issue by pattrickrice** [ferdikoomen/openapi-typescript-codegen#1036]
**Describe the solution you'd like**

The type has some great utility, but I couldn't find documentation around it. If it already exists, feel free to close.

**Comment by ferdikoomen** [comment]
@pattrickrice Hope this helps: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/canceling-requests.md feel free to make a pr with improvements
