### ISSUE TITLE
Support the `deprecate` keyword

### ISSUE THREAD

**Issue by galah92** [ferdikoomen/openapi-typescript-codegen#1039]
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ideally with a small example of the proposed changes.

`deprecated: true` can be used on properties for OpenAPI / JsonSchema definitions. Is is possible to add the relevant annotations to these field for the generated code? Maybe relevant comments such that the IDE will pick them?

Thank you

**Comment by ferdikoomen** [comment]
@galah92 I pushed changes to the main branch with better deprecated support, will publish a new version today.
