### ISSUE TITLE
Custom generating types

### ISSUE THREAD

**Issue by Abukodonosor** [ferdikoomen/openapi-typescript-codegen#1051]
Hello, I would like to add one bonus parameter like (include/exclude) for generating schemas.

Will be nice to have a way to give strict names of the models which we want to get generated.

We are splitting the monolith into microservices and we want to have a specific type for every microservice.

So our swagger documentation is a bit large and I don't need all those types, just specific ones.

Are you ok to start developing this feature?
Is it making sense?
Would you like me to start working on it, or you will take an ovnership?

Its a simple feature, so wont be much work on this

Thanks for answer

**Comment by ferdikoomen** [comment]
@Abukodonosor i'm fine if you want to create a PR, but why would you split the generation? You could also do the following: Just create a generate the whole client (including all services and models), then publish that as a package and use this inside each micro service. Tree shaking should remove the models you do not need. 

Alternatively you can already do this by trimming the OpenAPI spec before generating the client:

Example file: `generate.js`
```
const { generate } = require('openapi-typescript-codegen');

// Load the spec file (assuming OpenAPI V3 json format)
const mySpec = require('./spec.json');

// Remove the stuff you do not need
delete mySpec.paths["/users"];
delete mySpec.paths["/shops"];
delete mySpec.components.schemas.User;
delete mySpec.components.schemas.Shop;
delete mySpec.components.schemas.Foo;

// Then generate the client based on this spec
generate({
    input: mySpec,
    output: './myClient',
});
```

**Comment by Abukodonosor** [comment]
I am going with the reverse process.

On the FE side, I need the schema for each Microservice.

The common library has some types which I don't need.
Cuz I have those types inside other BE microservice, and I want to use them from there.

So besacily usecase:

"generate:pairing": "npx openapi -i http://10.4.17.22:9041/v3/api-docs -o ./src/api/generated/pairing --exportCore false --exportServices false",

and from 

"generate:common": "npx openapi -i ht..." - i would like to exclude or include list.... so it doesn't generate all types.

Also useful feature is just to recreate changed ones.. not every time to regenerate all of them.
