### ISSUE TITLE
[feature] Use this codegen for alternative stacks

### ISSUE THREAD

**Issue by ThePlenkov** [ferdikoomen/openapi-typescript-codegen#1054]
Hi! I'm searching for openapi codegen which supports alternative stacks ( in my case is ABAP language ).

So the ideal situation - if I'm able to create a custom template and to use template to generate text files in my own format ( not typescript ).

So far I have found two products which can do this:
- [Swagger Coden](https://swagger.io/tools/swagger-codegen/)
- [OpenApi codegen](https://openapi-generator.tech/docs/customization)

the problem is that both solutions require Java stack.  I think it was one of core reasons for this utility too. So it would be nice if it can have extensibility feature too. Do you think is it possible already now? 

Thanks!

**Comment by ferdikoomen** [comment]
@ThePlenkov this OpenAPI generator is really aimed at Typescript/Javascript frontent stack with predefined options. For ABAP the best solution would probably something like this: https://github.com/abap-openapi/abap-openapi
