### ISSUE TITLE
When using Axios client the TypeScript generated types are incorrect with latest version of axios@0.27.2

### ISSUE THREAD

**Issue by callmeberzerker** [ferdikoomen/openapi-typescript-codegen#1083]
Here is an example of the error message from the generated `request.ts` core file.

```
TS2322: Type 'AxiosResponse<unknown, any>' is not assignable to type 'AxiosResponse<T, any>'.
  Type 'unknown' is not assignable to type 'T'.
    'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.
        return axiosError.response;
```

**Comment by jtc42** [comment]
I'm getting this too. Have you found a workaround?

**Comment by callmeberzerker** [comment]
@jtc42 I am not sure what fixed it - but I don't have the problem anymore. I think some dependency was off - but I can't recall.

**Comment by jtc42** [comment]
Ah ok, thanks for the tip!

**Comment by callmeberzerker** [comment]
If you found a solution write it down here for the next passer-by! Don't make my mistake. 😄

**Comment by jtc42** [comment]
> If you found a solution write it down here for the next passer-by! Don't make my mistake. 😄 

Truth be told we just switched to [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-axios.md). It's definitely clunkier than this repo but for our specific requirements it was a neater fit anyway.
