### ISSUE TITLE
self signed certificate error during client generation from aspnetcore server

### ISSUE THREAD

**Issue by barocuda** [ferdikoomen/openapi-typescript-codegen#1160]
Hi,

I am currently trying to generate typescript client from aspnetcore server which works fine if SSL deactivated on launch configurations. 

I am getting self signed certificate error if I activate the SSL and trying to download specs.json via https. Are there any option that I am missing to trust self signed certificates which is generated by dotnet?

**Comment by RyKilleen** [comment]
This is a general node issue, if you're trying to reach https on localhost, you can disable this with a node environment variable: `NODE_TLS_REJECT_UNAUTHORIZED=0`

The requisite warning, this is very insecure and should be used locally only.

**Comment by barocuda** [comment]
Thank you @RyKilleen. It works.
