### ISSUE TITLE
Make updating the base url optional

### ISSUE THREAD

**Issue by stianste** [ferdikoomen/openapi-typescript-codegen#1180]
At the moment when running the generator, the base url will automatically be replaced with whatever host the api was generated against. In our current project we want to keep the base url empty, so that the requests will hit the different environments respectively, e.g (www.test.example.com, www.stage.example.com and www.example.com) based on the contexts it's being called in. This means we have to manually set `BASE` back to `''` each time we run the generator, which is an inconvenience. 

It would be great if there was a flag for this, e.g `--update-base-url=false` or something similar which would allow for keeping the base url unchanged.

**Comment by hrstmr** [comment]
@stianste you can use the exportCore attribute when running the generate command `--exportCore false`

`npx openapi-typescript-codegen --input [SCHEMA] --output [OUTPUT_DIR] --exportCore false`

Note: doing this will remove the related exports from the index.ts so you might have to manually update the import paths

![image](https://user-images.githubusercontent.com/37159938/201494946-ba1b8122-8651-430f-945c-1065f9c46f43.png)

**Comment by stianste** [comment]
@hrstmr thanks for the tip! But the whole point was to avoid having to do manual changes. In this case it's easier to reset the url than to update the imports
