### ISSUE TITLE
Add option to use ESM style import specifiers

### ISSUE THREAD

**Issue by Awem** [ferdikoomen/openapi-typescript-codegen#1182]
The code generated by this package is currently not suitable to be easily used in ESM projects. This is because for ESM, we need different import specifiers: https://nodejs.org/api/esm.html#import-specifiers

So e.g.:

`export { ApiError } from './core/ApiError` should be `export { ApiError } from './core/ApiError.js`

It would be helpful to provide a configuration option, that changes the generated code accordingly.

**Comment by Pustur** [comment]
Seems like #1226 is trying to fix this

**Comment by klippx** [comment]
@ferdikoomen Can you please re-open this?

**Comment by klippx** [comment]
Here is a codesandbox illustrating the problem: https://codesandbox.io/p/sandbox/openapi-typescript-codegen--with-esm-c83t3c?file=%2Fsrc%2Findex.ts%3A1%2C1

See how we cannot build since the generated types are not ESM? Hence we cannot get a dist folder updated without manually updating the generated files.

**Comment by matthewadams** [comment]
@ferdikoomen We are trying to upgrade to Node 20.x & Typescript 5.x and this is a blocker.  It seems to me that there are two issues here:  first, having the tool generate code that is usable in an ESM project, and second, _using_ this tool in an ESM project.

It appears that https://github.com/ferdikoomen/openapi-typescript-codegen/pull/1226 is attempting to address the second issue.  There still needs to be a PR to address the first.

**Comment by doichev-kostia** [comment]
If it's blocking for someone, you can patch the package with https://gist.github.com/doichev-kostia/ccfb0689a5c72f66950518f062249e43 where I added the `.js` extension to those imports in the bundled code

for instance:
```shell
pnpm patch openapi-typescript-codegen@<version>
```

You'll receive something like
```shell
You can now edit the following folder: /private/var/folders/nr/bj8rh6yn4yn2l16wlfjygmlw0000gn/T/1c9e286e3d40a1ea67821c5c574c7a02

Once you're done with your changes, run "pnpm patch-commit /private/var/folders/nr/bj8rh6yn4yn2l16wlfjygmlw0000gn/T/1c9e286e3d40a1ea67821c5c574c7a02"
```

then open the `/private/var/folders/nr/bj8rh6yn4yn2l16wlfjygmlw0000gn/T/1c9e286e3d40a1ea67821c5c574c7a02` in the editor and replace the `./dist/index.js` with one provided in the [gist](https://gist.github.com/doichev-kostia/ccfb0689a5c72f66950518f062249e43)

save and run 
```shell
pnpm patch-commit <patch_directory>
```

and re-run `pnpm i`

after that, it should be ok
