### ISSUE TITLE
[Bug] Operation path generation

### ISSUE THREAD

**Issue by songzhi** [ferdikoomen/openapi-typescript-codegen#119]
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/977854effb707ee171b06bbf3c6b18786441bad5/src/openApi/v3/parser/getOperationPath.ts#L8

If there's a url like `/users/{user_id}/`,the parameter name in generated code will be `userId`,but in path it still is `user_id`.Which is a bug.
Here's my fix:
``` typescript
import camelCase from 'camelcase';
/**
 * Get the final service path, this replaces the "{api-version}" placeholder
 * with a new template string placeholder so we can dynamically inject the
 * OpenAPI version without the need to hardcode this in the URL.
 * @param path
 */
export function getOperationPath(path: string): string {
    return path.replace(/{api-version}/g, '{OpenAPI.VERSION}').replace(/\{(.*?)\}/g, (_, w) => `\$\{${camelCase(w)}\}`);
}
```

**Comment by ferdikoomen** [comment]
Hey Songzhi, let me have a check tomorrow, will merge your fix asap, plus will add a test case to prevent the issue in the future.

**Comment by ferdikoomen** [comment]
@songzhi I have pushed a new version (0.1.15) with the changes. Let me know if this works for you.

**Comment by ferdikoomen** [comment]
@songzhi I have pushed a new version (0.1.15) with the changes. Let me know if this works for you.
