### ISSUE TITLE
Error in type generation due to reserved word `interface`

### ISSUE THREAD

**Issue by christianvogt** [ferdikoomen/openapi-typescript-codegen#1230]
**Describe the bug**
Error in type generation due to reserved word `interface`:

```
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0"
  },
  "components": {
    "schemas": {
      "interface": {
        "type": "object"
      }
    }
  }
}
```

Output `interface.ts`:
```
export type interface = {
};
```

`Identifier expected. 'interface' is a reserved word in strict mode. Modules are automatically in strict mode.`

<img width="892" alt="image" src="https://user-images.githubusercontent.com/14068621/187264067-54a25959-12c3-46f7-946f-c5fabe2ccb36.png">

**Comment by mb21** [comment]
This may be solved by https://github.com/ferdikoomen/openapi-typescript-codegen/pull/1192...

**Comment by ferdikoomen** [comment]
Yes, should be solved now!
