### ISSUE TITLE
Put all generated function's parameters into one object

### ISSUE THREAD

**Issue by songzhi** [ferdikoomen/openapi-typescript-codegen#127]
Here's the problem I've met.Because JS/TS hasn't named  parameter.The normal solution is 
``` ts
interface Names {
    name1: boolean
    name2: boolean
    name3: boolean
    name4: boolean
}

function myFunction({name1, name2, name3, name4}: Names) {
    // name1, etc. are boolean
}
```
And currrently the generated code is like
```ts
function myFunction(name1:boolean, name2:boolean, name3:boolean, name4:boolean) {
    // name1, etc. are boolean
}
```
It's frustrating that if I want to pass just one parameter which is in the rear,I have to write a bunch of undefined before it.

So if we use the former way,the problom will be solved.And we have named parameter passing(by the object literal).And the codegen don't need to sort them by required,maybe could in alphabetical order?Or we just put optional parameters into a object.

Anyway the former way seems more idiomatic,so I hope you can change to it.Honestly your work is very great,the official ts-codegen sucks 😂.Thanks for your wonderful work.

**Comment by ferdikoomen** [comment]
Oh i like that, that could be a nice flag: ArgumentStyle vs ObjectStyle. Something like --useOptions?

**Comment by songzhi** [comment]
Yeah，and now I think put all optional parameters to into options is the best way if using `--useOptions` .Like `**kwargs` in Python。

**Comment by songzhi** [comment]
@ferdikoomen It's embarrassing to say that I'm too impatient to wait for the new style.I wrote more code and found that the code could be more flexible and simple if using the new style.

**Comment by ferdikoomen** [comment]
no problem, i had a look this weekend and it should be a simple change. I should be able to push some changes later on this week. If you want to help then feel free to create a PR or update some documentation. I will update this thread when the new option is available.

**Comment by songzhi** [comment]
I did some updates on README. #128 You can edit it for correctness after you finish the code writing.

**Comment by ferdikoomen** [comment]
Added 0.1.17 that supports --useOptions param. I'm still testing this, but feel free to play around with it.

**Comment by ferdikoomen** [comment]
@songzhi 0.1.17 has been tested and should have the alternative style fro arguments vs options
