### ISSUE TITLE
[Question] Nullables and optionals

### ISSUE THREAD

**Issue by ssbb** [ferdikoomen/openapi-typescript-codegen#1300]
I am just wondering if there a way to use `nullable` flag to not make type fields optionals? 

For example

```
"title": {
  "nullable": false,
  "type": "string",
}
`` 

I would expect it to generate `title: string` instead of `title?: string` which can be undefined.

**Comment by hrstmr** [comment]
@ssbb  you can mark the `title` as required by adding it to the list `"required": ["title"],` which would generate the type definition  of `title: string` 
```
"SomeObject": {
    "required": ["title"],
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        }
    }
}
```

**Comment by ssbb** [comment]
> @ssbb you can mark the `title` as required by adding it to the list `"required": ["title"],` which would generate the type definition of `title: string`
> 
> ```
> "SomeObject": {
>     "required": ["title"],
>     "type": "object",
>     "properties": {
>         "title": {
>             "type": "string"
>         }
>     }
> }
> ```

Oh, thank you! ❤️ 

I thought it's more for input but makes sense.

**Comment by tombohub** [comment]
@hrstmr where exactly we do that? What file?

**Comment by alexanderchr** [comment]
If using NSwag, you can automatically add non-nullable fields to the required array by registering a custom schema processor as in https://github.com/RicoSuter/NSwag/issues/3110#issuecomment-799519820
