### ISSUE TITLE
Very Long names

### ISSUE THREAD

**Issue by tomitrescak** [ferdikoomen/openapi-typescript-codegen#1329]
What a phenomenal package!

I am just wondering why does it generate such a long names for functions?
For example my functions are:

```
recommendProgramForRolesRecommendProgramForRolesPost
```

Why is `RecommendProgramForRolesPost` appended?
Would not it be easier just to put:

```
recommendProgramForRolesPost
```

I guess there must be some clashing happening I just do not understand where and when it can happen.

**Comment by fracalo** [comment]
That pretty much depends from how your backend names the types,
I have a similar issue in my .net webapi.

You can check the names (and eventually modify them) in the `components.schema` section of your openapi specs.

**Comment by tomitrescak** [comment]
Thank you @fracalo for your answer. I will look into it.
