### ISSUE TITLE
Status code 204 returns as error

### ISSUE THREAD

**Issue by tombohub** [ferdikoomen/openapi-typescript-codegen#1341]
**Describe the bug**
A clear and concise description of what the bug is. Ideally with a screenshot of the result or a link to a small example.

I am returning No content with status code 204. 
When using vanilla axios return status is Success, but with generated fetchers from openapi-typescript-codegen return status is Error.

**Comment by ferdikoomen** [comment]
@tombohub Do you have the spec + response ? Otherwise this will be hard to debug

**Comment by tombohub** [comment]
@ferdikoomen it was long time ago, I dont have anything right now. We can close this issue and reopen if it ever happens again
