### ISSUE TITLE
Wrong code generated when using model named `File`

### ISSUE THREAD

**Issue by songzhi** [ferdikoomen/openapi-typescript-codegen#135]
I have  a model named `File` and another named `FilePagingResponse`,here's the generated code:
``` ts
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/**
 * Abstract base class for generic types.
 * A generic type is typically declared by inheriting from
 * this class parameterized with one or more type variables.
 * For example, a generic mapping type might be defined as::
 * class Mapping(Generic[KT, VT]):
 * def __getitem__(self, key: KT) -> VT:
 * ...
 * # Etc.
 * This class can then be used as follows::
 * def lookup_name(mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:
 * try:
 * return mapping[key]
 * except KeyError:
 * return default
 */
export interface FilePagingResponse {
  items: Array<File>
  total: number
  has_more?: boolean
}
```
So it's just using the builtin `File`,which is not my `File` model. And other code is OK.So, there must be something wrong in here.

**Comment by ferdikoomen** [comment]
Hi @songzhi The File is an internal Javascript/Typescript class. Used for actual file references. Its used for when you for instance want to build something like an upload

**Comment by songzhi** [comment]
@ferdikoomen I know, but I have a model called `File`.So either I rename the model or you change the codegen.By the way, the previous features are still be waiting desperately😂.

**Comment by songzhi** [comment]
@ferdikoomen Based on Open API 3.0 [Spec](https://swagger.io/docs/specification/data-models/data-types/#file),which does not have the file type. Files are defined as strings.
So I think the code in here https://github.com/ferdikoomen/openapi-typescript-codegen/blob/43375ef0269081a2e6207ec771ffc6cef40f8a00/src/openApi/v3/parser/constants.ts#L13 is a mistake.Could you please fix it?

**Comment by ferdikoomen** [comment]
OpenAPI has indeed no concept of 'Files'. Since each language uses its own spec, however it does have support for binaries. Lets say someone want to create a service that uploads a file. The following spec could make that work:

```json
"/api/v{api-version}/upload": {
    "post": {
        "tags": [
            "Upload"
        ],
        "operationId": "UploadFile",
        "parameters": [
            {
                "description": "Supply a file reference for upload",
                "name": "file",
                "in": "formData",
                "required": true,
                "schema": {
                    "type": "File"
                }
            }
        ],
        "responses": {
            "200": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        }
    }
}
```

It would generate a call that looks like this:

```typescript
/**
 * @param file Supply a file reference for upload
 * @result boolean
 * @throws ApiError
 */
public static async uploadFile(file: File): Promise<boolean> {

    const result = await __request({
        method: 'post',
        path: `/api/v${OpenAPI.VERSION}/upload`,
        formData: {
            'file': file,
        },
    });

    catchGenericError(result);

    return result.body;
}
```

**Comment by songzhi** [comment]
I'm not so familiar with OpenAPI, but in the website I quoted before, it's saying:

> Unlike OpenAPI 2.0, Open API 3.0 does not have the file type. Files are defined as strings:
> ``` yaml
> type: string
> format: binary  # binary file contents
> ```
> or
> ``` yaml
> type: string
> format: byte    # base64-encoded file contents
> ```
> depending on the desired file transfer method. For more information, see [File Upload](https://swagger.io/docs/specification/describing-request-body/file-upload/), [Multipart > Requests](https://swagger.io/docs/specification/describing-request-body/multipart-requests/) and [Response That Returns a File](https://swagger.io/docs/specification/describing-responses/#response-that-returns-a-file).

**Comment by songzhi** [comment]
Souds reasonable, thank you.

**Comment by nazarhussain** [comment]
@ferdikoomen Is this `"in": "formData",` a valid for OAS 3? I could not find any reference for it? As per my knowledge, there are only `path`, `query`, `header`, and `cookie` parameters.
