### ISSUE TITLE
Custom `requestUsingXX` function

### ISSUE THREAD

**Issue by songzhi** [ferdikoomen/openapi-typescript-codegen#136]
Supports using custom `requestUsingXX` function besides `requestUsingXHR` and `requestUsingFetch`.So users can using their custom network stack, for example there is a sort of plaform called 'mini program' in China, which is basically browers-based, but has it's own APIs eg. `request`.
It's easy to implement:
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/83483e67e42d0806f69fd8a535a099d2998c47d4/src/templates/core/OpenAPI.hbs#L9
Could be refactored to:
``` ts
import { Result } from './Result'
// ...
export let CLIENT:
 | string
 | ((url: string, request: Readonly<RequestInit>) => Promise<Result>) 
 = '{{{httpClient}}}'
```
And in here add more conditions
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/83483e67e42d0806f69fd8a535a099d2998c47d4/src/templates/core/request.ts#L66-L72

**Comment by ferdikoomen** [comment]
Hi Songzhi, sorry for the delay in the response, but the idea behind the library is to keep it simple and work with standard (build-in) methods like fetch or xhr. If you want a fully customisable output then the classic codegen might be a better fit.
