### ISSUE TITLE
Support for Axios 1.x

### ISSUE THREAD

**Issue by ldsenow** [ferdikoomen/openapi-typescript-codegen#1411]
First of all, thanks for your awesome tool. It helps us a lot.

I have a small little wish request as the title above. Axios recently has upgraded the version and we start getting typescript compile error due to axios headers type definition. Is possible to take a look this breaking change?

**Comment by sicksid** [comment]
i just started seeing this too

**Comment by sicksid** [comment]
its this problem specifically:

```
TS2741: Property 'headers' is missing in type '{}' but required in type 'AxiosRequestConfig<any>'.
```

![Screenshot 2023-01-19 at 19 40 18](https://user-images.githubusercontent.com/7379966/213599776-2b5117d8-1f7c-471c-9b80-da1d401518fb.png)

**Comment by sicksid** [comment]
there is this issue here which is probably where this should be fixed: https://github.com/axios/axios/issues/5476

**Comment by sicksid** [comment]
@ldsenow  if you install `    "axios": "1.2.2", ` you skip the problem entirely 

I think we can close this and let the axios team fix this
