### ISSUE TITLE
Support onDownloadProgress in ApiRequestOptions

### ISSUE THREAD

**Issue by lukqw** [ferdikoomen/openapi-typescript-codegen#1428]
**Describe the solution you'd like**
I'd like to make axios requests with the `onDownloadProgress` option. 
For that I need `ApiRequestOptions` to include `readonly onDownloadProgress?: (progressEvent: ProgressEvent) => void;`
Furthermore I need this field to be unwrapped into the `requestConfig` of the `sendRequest` method.

Maybe in general a way of extending axios request options would be nice?

**Comment by Or-Zarchi-Forter** [comment]
I've created a PR that can solve this by allowing an axios custom instance, #1434. Please comment there so it will get attention 😄

**Comment by 50Bytes-dev** [comment]
Check my PR #1682
