### ISSUE TITLE
CancellablePromise in Typescript 4.9.5

### ISSUE THREAD

**Issue by mstosio** [ferdikoomen/openapi-typescript-codegen#1448]
In Typescript version 4.9.5, after generting there is error in CancellablePromise:

readonly [Symbol.toStringTag]: string;

TS2564: Property '[Symbol.toStringTag]' has no initializer and is not definitely assigned in the constructor.

**Comment by ferdikoomen** [comment]
This should be fixed in the latest release @mstosio

**Comment by ferdikoomen** [comment]
Thanks for the PR!
