### ISSUE TITLE
Rearchitecture to support multiple client instances

### ISSUE THREAD

**Issue by kraenhansen** [ferdikoomen/openapi-typescript-codegen#1455]
I have a use-case where I would like to create multiple instances of API clients (each with different base urls, for dev, testing and prod environments), which is not possible in the current architecture of the generated code, since the `OpenAPI` is a shared object and operations are exposed as static methods on services.

A possible solution to this would be:
- a root `Client` class would be emitted with services exposed as instance properties
- the `Client` would take an optional `config` object to override things like the `request` function and `baseUrl`
- the operations would be instance methods on those services.

I've tried to write up an example of a very simple client with that architecture:

```typescript
type ClientConfig = { baseUrl: string, /* request: ... */ };

class PeopleService {
    constructor(private config: ClientConfig) {}
    list(): CancelablePromise<People[]>
}

const DEFAULT_CONFIG: ClientConfig = { baseUrl: "https://..." };

class Client {
  people = new PeopleService(this.config);
  constructor(private config: ClientConfig = DEFAULT_CONFIG) {}
}
```

This architecture would allow multiple instances of `Client` in the same process, each with a different state of `baseUrl` which could also be extended with a state for authentication headers to inject when issuing a request.

```typescript
const prodClient = new Client();
const testClient = new Client({ baseUrl: "http://test..." });
```

Also ... I totally understand that this would be a pretty significant change that you might not want to see happen.
I just though I would leave my feedback, in case you're looking for ideas on how to take this further and make it even more valuable.

And thanks for taking the time to build and maintain this library!

**Comment by Pangamma** [comment]
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/client-instances.md
^ This capability does already exist. I just wish we could also make it so file names were camel case.

**Comment by kraenhansen** [comment]
@Pangamma wow thanks for sharing that! 💙

I was happy with the naming in the generated code, so I had no clue that a feature like that would be included in a `--name` runtime parameter. I'd suggest the CLI would just guess a name from the spec title and have this behavior enabled by default.
