### ISSUE TITLE
Adding comments to generated files

### ISSUE THREAD

**Issue by OdinQualifyze** [ferdikoomen/openapi-typescript-codegen#1502]
I would like to be able to specify comments that are added to the beginning of all generated files. The specific use-case I have in mind is putting 

```js
// THIS FILE IS GENERATED, DO NOT EDIT
```

to avoid confusing generated files with "regular" source files

**Comment by ferdikoomen** [comment]
Added!

**Comment by ferdikoomen** [comment]
/* generated using openapi-typescript-codegen -- do no edit */
