### ISSUE TITLE
Replace form-data with nodejs FormData?

### ISSUE THREAD

**Issue by Carseason** [ferdikoomen/openapi-typescript-codegen#1516]
The latest node has integrated DataForm https://github.com/form-data/form-data/issues/544 ,
There are many problems with npm data-form in ssr

**Comment by blumendorf** [comment]
We are on node 18 and switched to Axios as client for openapi.

This now leads to the following eslint error:
Error: Cannot find module '.../node_modules/form-data/lib/form_data'. Please verify that the package.json has a valid "main" entry
Occurred while linting .../src/App.tsx:2
Rule: "import/no-cycle"
...

We have not been able to further pin this down to anything in our code as the only change was switching from fetch to Axios as client.
