### ISSUE TITLE
npm release 0.24 reverts changes from 0.21

### ISSUE THREAD

**Issue by fidoriel** [ferdikoomen/openapi-typescript-codegen#1528]
**Describe the bug**
The current 0.24 npm release contains the `#` for private stuff introduced in 0.21. Strangely the 0.24 release has no corresponding github tag. Using this new feature breaks compatibility with my app, so I am using 0.23. The general situation seems strange to me, I expected that the change back would be in a Changelog.

**Comment by ferdikoomen** [comment]
@fidoriel i have added the tags, the # for private variables should still be there. Please raise an issue with the exact description of the bug, then i can have a look
