### ISSUE TITLE
Please release 0.25

### ISSUE THREAD

**Issue by abotteram** [ferdikoomen/openapi-typescript-codegen#1561]
Hi, we are currently experiencing the bug that was fixed by this PR: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/1067/files. 

We would greatly appreciate if you would release this fix to npm.

Thanks in advance!

**Comment by ferdikoomen** [comment]
Done!

**Comment by abotteram** [comment]
Thank you so much! Amazing work.
