### ISSUE TITLE
How to rename DefaultService to for example ApiService?

### ISSUE THREAD

**Issue by urosjarc** [ferdikoomen/openapi-typescript-codegen#1667]
I'm wondering how can I rename DefaultService that is generated by this lib to something more appropirate?

![image](https://github.com/ferdikoomen/openapi-typescript-codegen/assets/8678755/81c5d024-e0f8-4ab1-90cb-58e0924321e6)

In the documentation doesn't write anything so I joust created an issue.
All The best!

**Comment by mrlubos** [comment]
Hey @urosjarc, I tend to use tags for this purpose. I wonder if you use any? I don't see a `DefaultService` being generated on my end at all.

**Comment by urosjarc** [comment]
I joust use Angular specific library for generating typescript client from OpenAPI...
> ng-openapi-gen
They have much better angular integration...
