### ISSUE TITLE
Cannot actually use the generated functions

### ISSUE THREAD

**Issue by matthewhausman** [ferdikoomen/openapi-typescript-codegen#1769]
```
const coursesClient = new AppClient({
  TOKEN: getToken,
  BASE: process.env.NEXT_PUBLIC_HOST_API || '',
});

const go = async () => {
  const response = await coursesClient.courses.getCoursesCoursesGet({})
  console.log(response);
};

go();
```

following the simplest example of the libraries usage I cannot print the response as follows. The network tab clearly shows that the request is successful, as well as printing the response in the generated request file. However, the promise appears to be unawaitable. 

next js version: latest
codegen version: latest
node version: 18.12.0

**Comment by matthewhausman** [comment]
Not sure if it fixed in latest next version, I wasn’t able to get it working without changing the Cancellable promise code

**Comment by matthewhausman** [comment]
There’s another issue filed already with the fix

**Comment by KiwiKilian** [comment]
You can install from GitHub until the fix is published on npm:
```
npm install https://github.com/ferdikoomen/openapi-typescript-codegen
```
Fixes the problem on my side 🎉.
