### ISSUE TITLE
Unable to read result of api method call in my nextjs code eventhough browser network call shows the result

### ISSUE THREAD

**Issue by anuragjha** [ferdikoomen/openapi-typescript-codegen#1813]
I have installed typescript-axios client. using command
`openapi --input autobots-api.json --output ./src/generated/client --name ABClient --client axios`

The sdk is being generated and I am using it in my code like this:
1st try:
```
const client = new ABClient({BASE:'https://xyz.com'});
const res = await client.hello.helloV1HelloGet();
console.log(res);
```
2nd try:
```
const client = new ABClient({BASE:'https://xyz.com'});
const respr = client.hello.helloV1HelloGet();
respr.then(res => {
  console.log(res);
}).catch(error => {
  if (error instanceof CancelError) {
    console.log('Promise was cancelled:', error.message);
  } else {
    console.log('Error:', error);
  }
});
```
I am unable to see console logs and there are no errors being thrown. Also on debug of frontend, the cursor just drops after 
`const respr = client.hello.helloV1HelloGet();`

On the network calls I see the result. 

I am new to frontend and having hard time finding the issue. Please point me in right direction.

**Comment by krisgrm** [comment]
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/1751

related to this
