### ISSUE TITLE
Wrong path on Windows

### ISSUE THREAD

**Issue by mmospanenko** [ferdikoomen/openapi-typescript-codegen#2052]
On Windows, when use app under another process, RefParser gets wrong path. And as result - it joins abs and rel paths from package and argument. So I had to fix it like this:
<img width="734" alt="image" src="https://github.com/ferdikoomen/openapi-typescript-codegen/assets/2766211/60394ee9-7e52-47dc-9650-6f942e615242">

STR:
1. create file with exec (cli or import - the same)
2. run as node myfile.js on windows

<img width="1849" alt="image" src="https://github.com/ferdikoomen/openapi-typescript-codegen/assets/2766211/56bf0232-2d94-4105-9491-f5db1d76d760">

**Comment by mrlubos** [comment]
Thanks. Seems quite a few people run into this issue

**Comment by mrlubos** [comment]
@tajnymag hm, this package used that version before and people still complained so it got reverted

**Comment by tajnymag** [comment]
> @tajnymag hm, this package used that version before and people still complained so it got reverted

Interesting. I'll try to find out why it worked and why it would't. I tried it with openapi-codegen (your version) installed as a devDependency

**Comment by mrlubos** [comment]
@tajnymag thanks, let me know if you find out please. I didn't get around to trying this one out yet

**Comment by mrlubos** [comment]
@tajnymag i suspect we'll need to fork the other package too https://github.com/APIDevTools/json-schema-ref-parser/issues/303

**Comment by tajnymag** [comment]
@mrlubos I think I fixed the issue. Basically followed @mmospanenko's suggestion and made all passed paths to json-schema-ref-parser absolute.

Both of these had to be made together to pass our tests
1. always pass absolute url to json-schema-ref-parser
2. update json-schema-ref-parser to v11.1.0

**Comment by mrlubos** [comment]
@tajnymag is the absolute path conversion happening inside this package or is that something you do before passing the value to `--input`?

**Comment by mrlubos** [comment]
@mmospanenko we've published a fix in [our fork](https://github.com/nicolas-chaulet/openapi-typescript-codegen), mind giving it a try and see if it works without the need for workarounds on your end?

**Comment by mmospanenko** [comment]
I can't test on Windows, it was funny testing game while we were trying to solve the issue)) but yes, will be great to remove workaround, thank you, @mrlubos!
I think thread could be closed if you've fixed this

**Comment by mrlubos** [comment]
@mmospanenko i don't have the permissions to close issues in this repository, but as long as our fix works for you, I will continue referring people to our fork if they experience the same issue

**Comment by o0Maikeru0o** [comment]
@tajnymag That was my mistake. I hadn't updated the package to the latest version with your changes. Seems to working now. Thanks for contributing

**Comment by mrlubos** [comment]
Cool stuff @tajnymag, thanks for confirming @o0Maikeru0o
