### ISSUE TITLE
 'fetch is not defined\n'

### ISSUE THREAD

**Issue by yzf1116** [ferdikoomen/openapi-typescript-codegen#2124]
PS D:\workOther\pnpmProject\packages\vite-project> openapi --input http://10.193.239.107:8082/manage/v2/api-docs --output ./generated --client axios
{
  stack: 'JSONParserError: Error downloading http://10.193.239.107:8082/manage/v2/api-docs \n' +
    'fetch is not defined\n' +
    '    at download (C:\\Users\\77081\\AppData\\Roaming\\nvm\\v16.20.2\\node_modules\\openapi-typescript-codegen\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\resolvers\\http.js:113:15)',
  code: 'ERESOLVER',
  name: 'ResolverError',
  message: 'Error downloading http://10.193.239.107:8082/manage/v2/api-docs \n' +
    'fetch is not defined',
  source: 'http://10.193.239.107:8082/manage/v2/api-docs',
  path: null,
  toJSON: [Function: toJSON],
  footprint: 'null+http://10.193.239.107:8082/manage/v2/api-docs+ERESOLVER+Error downloading http://10.193.239.107:8082/manage/v2/api-docs \n' +
    'fetch is not defined',
  toString: [Function: toString]
}
What was the problem? please

**Comment by mrlubos** [comment]
Hey! Can you try updating to Node 18 and use https://github.com/hey-api/openapi-ts?

**Comment by yzf1116** [comment]
> Hey! Can you try updating to Node 18 and use https://github.com/hey-api/openapi-ts?

thank you vary much, you are right！
