### ISSUE TITLE
Feature request: Allow urls in input parameter

### ISSUE THREAD

**Issue by gazab** [ferdikoomen/openapi-typescript-codegen#220]
It would be very useful if you could specify an url as input when generating the client instead of just a local file. I always use an automatically generated OpenAPI spec together with Swagger UI and pointing it to the http served specification file is very natural.

Sure you can easily download it and generate a new client but I would prefer to just point it to the url of our test enviroment and fire away everytime we need to update the client.

Thanks for an awesome tool btw!

**Comment by ferdikoomen** [comment]
@gazab There is a fix pushed to master, the generator now supports HTTP and HTTPS urls (public available, since it just plugs into the http and https methods of nodejs). Will create a new release in a bit, that will also contain the fixes for the credentials fix.

**Comment by gazab** [comment]
Awesome! Thanks a lot!
