### ISSUE TITLE
Custom Axios Client

### ISSUE THREAD

**Issue by swollner** [ferdikoomen/openapi-typescript-codegen#2230]
Hi,
I want to use a custom axios client like described on https://github.com/ferdikoomen/openapi-typescript-codegen/wiki/Axios-Support

But I can't find BaseHttpRequest in the generated code. So how do I do this in the latest version: (0.29.0)

At the moment, the only way to do so, is to override all Services.

I used "openapi -o ./generated/ -i http://localhost:8080/rest/v3/api-docs -c axios --useOptions" to generate the code

This is what i got:
![Bildschirmfoto_2024-07-28_09-52-20](https://github.com/user-attachments/assets/0d3c1dcc-391a-4f36-afbe-36c0c60577a0)

**Comment by swollner** [comment]
Ok I solved it by myself... 

So you have to add e.g. --name AppClient to generate the missing wrappers. 
Maybe you should fix this in the documentation :)

openapi -o ./generated/ -i http://localhost:8080/rest/v3/api-docs -c axios --useOptions --name AppClient

will generate:
![Bildschirmfoto_2024-07-28_10-00-33](https://github.com/user-attachments/assets/53f9a9d5-dc40-48c3-aeaf-cc8884f78cf3)

**Comment by mrlubos** [comment]
Hey @swollner, this package is no longer maintained -> https://github.com/hey-api/openapi-ts
