### ISSUE TITLE
Feature request: Option to change how cookies are sent with requests

### ISSUE THREAD

**Issue by gazab** [ferdikoomen/openapi-typescript-codegen#249]
To allow us to use cookie based authentication and make the browser pass cookies to the server on each request we need to tell fetch to allow it. This is done by setting _credentials_ to "same-origin" or "include" when doing requests. Right now this is hardcoded to "same-origin" which only works if the client and API has the same origin. 

I would like to set it to "include" by passing some option so I can have the client and API on different origins and still use cookie authentication.

**Comment by ferdikoomen** [comment]
Good point @gazab Do you want to set this at the moment of generation? Otherwise im thinking we can add this to the OpenApi global settings (where we also set the bearer token for instace)

**Comment by gazab** [comment]
@ferdikoomen Hm, I think I would prefer the global options for anything not required to be done on generation. And the old value should still be default. What do you think?

**Comment by ferdikoomen** [comment]
Sounds good, adding this now

**Comment by ferdikoomen** [comment]
Created PR: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/256

OpenApi.WITH_CREDENTIALS = true

Will set the correct settings for both fetch and XHR request

**Comment by ferdikoomen** [comment]
Will create a new build in a bit, PR is merged
