### ISSUE TITLE
Accept PR to separate Enums into own files?

### ISSUE THREAD

**Issue by samuelneff** [ferdikoomen/openapi-typescript-codegen#262]
**Describe the solution you'd like**
I'd like to have an option to write enums to their own files (off by default to maintain backward compatibility).

With this option on, this currently generated code:

```ts
export interface SomeModel {
    status: SomeModel.status;
}

export namespace SomeModel {
    export enum status {
        started = 'started',
        finished = 'finished'
    }
}
```

would instead generate this

```ts
// SomeModel.ts
export interface SomeModel {
    status: Status;
}

// Status.ts
export enum Status {
    started = 'started',
    finished = 'finished'
}
```

If you would accept this, any guidance on how to go about it would be appreciated. I looked through the code and think it can be done with a new post-processor and template, but won't know for sure until I start.

**Comment by ferdikoomen** [comment]
@samuelneff I'm happy to give you some pointers, but maybe we need to answer the question: Why do we need/want this change? The reason they are inside a namespace (that equals the model) is because the enum is based on a variable name and those are no guaranteed to be unique. So you can have one model, lets say Person that will have a enum Gender, and you can have another model called Animal with a similar name enum. This wil cause issues with exports. So the use case is very limited. In most projects i'm involved in this would not work.

**Comment by samuelneff** [comment]
Thank you. I understand it could run into problems, and that's why it would be off by default.

The reason I want it is because if we use the same enum in multiple places, we end up with duplicates and the namespace doesn't really make sense in that scenario. It might be a use-case that would work in our situation since we're very careful with variable naming consistency, but would not work in many other situations unfortunately.

Since posting this I've found that OpenAPI spec itself supports having the enums as first class defined types and when this is done openapi-typescript-codegen does produce them as separate files. I'm not sure how to force Java/Spring to generate a schema with the enums as separate types though. Still looking at that alternate solution to my specific situation.

**Comment by ferdikoomen** [comment]
"I'm not sure how to force Java/Spring to generate a schema with the enums as separate types though. Still looking at that alternate solution to my specific situation." Do you mean from the server / spec generation side?

**Comment by samuelneff** [comment]
Yes, sorry I wasn't clear. I was referring to when we generate the schema from the Java classes. 

Another teammate just suggested generating TS interfaces directly from the Java classes. That's more direct and probably better for my specific situation.

Sorry to have wasted your time.

**Comment by ferdikoomen** [comment]
No problem! To be fair Java and Typescript are indeed very similar, so that sounds like a doable task, specially if the amount of enums are limited. I will close the issue, but feel free to reopen this if you get some new insights :-)

**Comment by dev-rifaii** [comment]
> Yes, sorry I wasn't clear. I was referring to when we generate the schema from the Java classes.
> 
> Another teammate just suggested generating TS interfaces directly from the Java classes. That's more direct and probably better for my specific situation.
> 
> Sorry to have wasted your time.

Did you end up generating them separately?
