### ISSUE TITLE
Creating services includes imports not in use

### ISSUE THREAD

**Issue by thsorens** [ferdikoomen/openapi-typescript-codegen#263]
```
import { MessageDetailsDto } from '../models/MessageDetailsDto';
import { ApiError, catchGenericError } from '../core/ApiError';
import { request as __request } from '../core/request';
import { OpenAPI } from '../core/OpenAPI';

export class MessageService {

```

ApiError and OpenAPI is not being used in the generated service, and causes a TS6133 error when building it.

**Comment by ferdikoomen** [comment]
@thsorens By default indeed it imports some general classes indeed, let me check it i can easily filter these out (or only add them if needed).

**Comment by ferdikoomen** [comment]
@thsorens pushed version 0.4.4, let me know if that works for you

**Comment by thsorens** [comment]
It looks great:) Now it generates it correctly. Thanks for the quick reply. This is a great tool:)
