### ISSUE TITLE
Generated barrelfile incomplete

### ISSUE THREAD

**Issue by PieterVanEde** [ferdikoomen/openapi-typescript-codegen#264]
When I generate using these options:

`    exportCore: false,
    exportModels: true,
    exportSchemas: true,
    exportServices: false,`

Then the barrel file has the following problems:
- it contains a reference to a service, which is explicitly not generated
- it contains no references to the models

**Comment by ferdikoomen** [comment]
Hi Pieter, let me check, I'll add some additional test cases for these scenarios.

**Comment by PieterVanEde** [comment]
Great! I'm currently seeing if I can make a PR to fix this.

**Comment by PieterVanEde** [comment]
Weird thing is that if I look at your code, it seems valid to me, yet with even version 0.4.4 I see the behaviour is wrong.

**Comment by ferdikoomen** [comment]
@PieterVanEde Can you share you spec with me? Is that possible?

**Comment by ferdikoomen** [comment]
Or the better question: if you generate it with the default options, does everything look good then?

**Comment by PieterVanEde** [comment]
Yep, after fooling around a bit, I've found the following:

- if generated with default options, all looks fine.
- if generated with everything set to false, the barrel file is empty (correct)
- if generated with `exportCore: true,
    exportModels: false,
    exportSchemas: false,
    exportServices: true,` then only the core and models end up in the barrel (wrong)
- if generated with `exportCore: true,
    exportModels: true,
    exportSchemas: false,
    exportServices: false,` then I only get the core and services in the barrel (wrong)
- and like that I see more cases where the generate flags seem to have effect on the wrong section in the barrel file.

**Comment by ferdikoomen** [comment]
Ah maybe the parsing logic of the booleans are wrong somehow, are using the Node API or using it via command line / package json?

**Comment by PieterVanEde** [comment]
The parsing is indeed wrong, I've linked my local checkout of my fork inside my test project, and added this to the top of the index.hbs:

`{{#if exportCore}}
// pieter was here: exportCore true
{{/if}}
{{#if exportModels}}
// pieter was here: exportModels true
{{/if}}
{{#if exportSchemas}}
// pieter was here: exportSchemas true
{{/if}}
{{#if exportServices}}
// pieter was here: exportServices true
{{/if}}`

Result for config `exportCore: true,
    exportModels: false,
    exportSchemas: false,
    exportServices: true,` is core and models

**Comment by PieterVanEde** [comment]
I'm using the typescript interface to call the library

**Comment by PieterVanEde** [comment]
Strangely enough, only the barrel file is wrong. The actual files that are output, are correct.

**Comment by PieterVanEde** [comment]
Error spotted, PR on its way

**Comment by PieterVanEde** [comment]
I don't have the time to write some tests, could I leave that to you?

**Comment by PieterVanEde** [comment]
PR is created, hope you agree ;)

**Comment by ferdikoomen** [comment]
Cool, thanks for spotting this, stupid mistake, will push a new version to npm now

**Comment by ferdikoomen** [comment]
Pushed 0.4.5

**Comment by ferdikoomen** [comment]
I re-opend this as a reminder to add some test cases

**Comment by PieterVanEde** [comment]
Great! And well, there is a stupid mistake in a great library that I could use for free, so I don't see a problem ;)
