### ISSUE TITLE
Add custom headers

### ISSUE THREAD

**Issue by thsorens** [ferdikoomen/openapi-typescript-codegen#269]
Is it possible to add a way to add custom headers?

Basically a dictionary that custom headers can be added to (in the config file), and just traverse and add them in the request? It is not uncommon for applications to provide additional headers. 

Im happy to provide a pull-request if that makes it easier for you:)

**Comment by kobik** [comment]
Allowing adding default headers and per request headers would be great

**Comment by ferdikoomen** [comment]
@thsorens @kobik Why can't you guys use the default OpenAPI spec for this?

You can define custom headers using the following spec:

```json
"/api/v{api-version}/something": {
    "get": {
        "tags": [
            "Parameters"
        ],
        "operationId": "SomeCallWithAdditionalHeaders",
        "parameters": [
            {
                "name": "custom-header-1",
                "in": "header",
                "schema": {
                    "type": "string",
                    "default": "Foo"
                }
            },
            {
                "name": "custom-header-2",
                "in": "header",
                "schema": {
                    "type": "string",
                    "default": "Bar"
                }
            }
        ]
    }
},
```

This generated the following Typescript service call:

```typescript
public static async someCallWithAdditionalHeaders(
    customHeader1: string = 'Foo',
    customHeader2: string = 'Bar',
): Promise<void> {

    const result = await __request({
        method: 'get',
        path: `/api/v${OpenAPI.VERSION}/something`,
        headers: {
            'custom-header-1': customHeader1,
            'custom-header-2': customHeader2,
        },
    });

    catchGenericError(result);

    return result.body;
}
```

Cheers,

Ferdi

**Comment by thsorens** [comment]
In our example we send in two tokens, on as access token and one for a given context. The openapi schema is autogenerated from a netcore api, so would be nice to avoid having to change rhe api

**Comment by mayoyml** [comment]
@ferdikoomen Thank you so much for making such a nice library! For me,  not only header, but also would like to add [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) as well. This helps when you want to cancel the request while waiting. [Demo page](https://mdn.github.io/dom-examples/abort-api/) Thank you so much for your time 🙏

**Comment by ferdikoomen** [comment]
@thsorens @mayoyml I will push a new version soon that has support for custom headers (via OpenAPI.HEADERS object). The code is already in the master branch. @mayoyml The AbortSignal will not be implemented since its to much client specific, we support fetch, xhr and node-fetch and only one of those has the AbortSignal.

**Comment by ferdikoomen** [comment]
The new version will be 0.6.0, will need to fix a few more bugs today and after that i'll push it to NPM
