### ISSUE TITLE
Apparently no way of disabling `exportCore` and `exportServices` in command line

### ISSUE THREAD

**Issue by arabold** [ferdikoomen/openapi-typescript-codegen#282]
I'm tried to use `openapi-typescript-codegen` from command line to generate only the models as I want to use a custom implementation for the requests themselves. So, I don't need `core` or `services`, just `models`.

However, passing `--exportCore false` or `--exportCore 0` or similar doesn't seem to work. It will still generate all files.

**Expected Behavior**
The following command should only generate `models` but no `core` or `services` code:
```sh
npx openapi-typescript-codegen \
  --input https://example.com/swagger.json \
  --exportCore false --exportServices false --exportModules true
```

**Comment by ferdikoomen** [comment]
@arabold Uploaded a new version that fixed this issue: 0.4.8
