### ISSUE TITLE
Enum with `null` throws an error

### ISSUE THREAD

**Issue by Alex0007** [ferdikoomen/openapi-typescript-codegen#289]
![image](https://user-images.githubusercontent.com/1143226/87780771-d251d400-c848-11ea-8762-b4fc1bbff2e9.png)
```
(node:73849) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at /Users/Alex/Development/projects/webdock-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:19871
    at Array.map (<anonymous>)
```

Link to example yaml: http://apidocs.beta.webdock.io/api-docs/webdock-v10.yaml

**Comment by ferdikoomen** [comment]
Hi @Alex0007 im prompted for a username and password, can you send me the spec / yaml in a private message? Or share the details?

**Comment by Alex0007** [comment]
> Hi @Alex0007 im prompted for a username and password, can you send me the spec / yaml in a private message? Or share the details?

https://gist.githubusercontent.com/Alex0007/1da683e083950e71f04a513d11b20611/raw/2a4b9bce5c5807960244f794b0306a14cc2338c3/webdock.yaml

**Comment by ferdikoomen** [comment]
Thanks @Alex0007, just downloaded the file, will investigate this tomorrow

**Comment by ferdikoomen** [comment]
Fixed, new build will be created end of day today
