### ISSUE TITLE
Add --no-core flag to exclude core folder regeneration

### ISSUE THREAD

**Issue by iegik** [ferdikoomen/openapi-typescript-codegen#298]
In most cases the changes will be in models, schemas, services folders only.
But core functions may differ from project to project.

So, nice to have some flag which disables core folder generation.

**Comment by ferdikoomen** [comment]
Hi @iegik with the latest version you have working export properties:

```bash
npx openapi-typescript-codegen --input spec.json --output someDir --exportCore false --exportServices false --exportModels false --exportSchemas false
```

**Comment by ferdikoomen** [comment]
--exportCore
--exportServices
--exportModels
--exportSchemas

Allow for true and false parameters. Hope that helps

**Comment by iegik** [comment]
Thanks
