### ISSUE TITLE
Generated code does not compile

### ISSUE THREAD

**Issue by trane** [ferdikoomen/openapi-typescript-codegen#323]
**Describe the bug**
The templates reference types that are not imported which results in typescript complaining when using the generated code. 

```json
{
  "scripts": "ts-node src/client/http/index.ts"
}
```

![Screen Shot 2020-08-11 at 3 51 24 PM](https://user-images.githubusercontent.com/36095/89956870-d88a6480-dbea-11ea-922b-ed446feb8c68.png)

You can see this in the code today: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/templates/core/request.ts#L26 (this uses `Headers` but does not import it).

**What is expected**

I figure that this error would happen to anyone using bare `tsc` to compile, so I assume there must be something I'm missing. Perhaps a "User Guide" section in the README.md would suffice to explain the expectations of the compile-time environment. (I'm guessing that this would work just fine if I were using Babel 7 -- and potentially webpack or rollup).

If it is that the library doesn't support `tsc`, then perhaps we can move this to a feature request to support a simple `tsc` backed use-case.

**Notes**
I was able to reproduce a compiled version following your `test/index.js` approach -- which successfully compiled the generated code in my repo: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/test/index.js
I'm not clean on why using this particular configuration of `tsc` would work while my version would not.

This still only gets one step further -- at runtime this still fails.

This time with an error when constructing the `new Header` in `request.js` -- which gets called when you do `MyGeneratedService.staticMethodName(body)`:
```
 ReferenceError: Headers is not defined
```

I have included my `tsconfig.json` here

```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"rootDir": ".",
		"types": ["node"],
		"strict": true,
		"sourceMap": true,
		"declaration": false,
		"esModuleInterop": true,
		"allowSyntheticDefaultImports": true,
		"moduleResolution": "node",
		"importHelpers": true,
		"target": "es6",
		"module": "commonjs",
		"typeRoots": ["node_modules/@types"],
		"lib": ["es2020", "es6"],
		"skipLibCheck": true,
		"skipDefaultLibCheck": true,
		"outDir": "dist",
		"baseUrl": ".",
		"noImplicitAny": false,
	},
	"exclude": ["node_modules", "tmp", "dist"],
	"include": ["src/**/*.ts"],
}
```

**Comment by ferdikoomen** [comment]
@trane Just for my info, what version of Node and Typescript are you using? The Header class is a default class for browser based Typescript projects (probably you will need to add "dom" in the lib section of your tsconfig)
```
"lib": ["es2020", "es6", "dom"],
```
But let me verify that.

**Comment by ferdikoomen** [comment]
Are you building a node "backend" project or are you using this inside a browser based application? If its the last then you need the "dom" lib. Otherwise you might need something like https://www.npmjs.com/package/node-fetch as a polyfill... but let me know, maybe i can add some support for that.

**Comment by trane** [comment]
Thank you for the info -- I am using this for a backend node project, so adding the `"dom"` lib indeed fixed the compile-time error! 

Unfortunately, now I'm left with a runtime error.

```
ReferenceError: Headers is not defined
    at Object.<anonymous> (/path/to/api/generated/core/request.ts:26:21)
```

Here are my versions:
Typescript version: `"typescript": "~3.9.7"`
node-fetch version: `"node-fetch": "~2.6.0"`
Node version: `v12.18.3`

Here is the code that I am using:

```typescript
import { Service, OpenAPI, v1Request  } from './api/generated';

// patch the global object in node with node-fetch
// https://github.com/node-fetch/node-fetch#loading-and-configuring-the-module
import fetch from 'node-fetch';
if (!globalThis.fetch) {
    globalThis.fetch = fetch;
}

OpenAPI.BASE = 'localhost:7089';
OpenAPI.CLIENT = 'fetch';

async function request(tokenProvider: () => Promise<string>): Promise<void> {
    const token = await tokenProvider();
    console.log('TOKEN', token)
    OpenAPI.TOKEN = token;

    const body: v1Request = {
        id: 'my-id'
    }
    console.log('BODY', body)

    const result = await Service.v1Request({body});
    console.log('RESULT', result)

    console.log(result);
    return
}

request(() => {
    console.log('RUNNING');
    return new Promise((resolve) => resolve('abcde'));
});
```

**Comment by lgazo** [comment]
I've got bit further with this

```
import fetch from 'node-fetch';
global.fetch = fetch;
global.Headers = fetch.Headers;
global.Blob = fetch.Blob;
```

but ended up with `TypeError: Right-hand side of 'instanceof' is not an object` at this line `if (options.body instanceof Blob) {`

**Comment by trane** [comment]
That's amazing, I came here to put the exact same details! I also tried some ideas based on this documentation from `node-fetch`: https://github.com/node-fetch/node-fetch#interface-body
I tried setting `global.Blob` to `Buffer` and `Readable` -- both of which don't meet the requirements for `Blob`.

I then looked at the code that references `Blob` in `node-fetch`: https://github.com/node-fetch/node-fetch/blob/64c5c296a0250b852010746c76144cb9e14698d9/src/body.js#L11. It doesn't appear to export this value, however. So, I decided to try to use the `Blob` from that package, and I still get an error.

```
import fetch, { Headers, Request } from 'node-fetch';
import Blob from 'fetch-blob';

if (!globalThis.fetch) {
	globalThis.fetch = fetch;
	globalThis.Request = Request;
	globalThis.Headers = Headers;
	globalThis.Blob = Blob;
}
```
The error:
```
src/client/http/index.ts:14:2 - error TS2322: Type 'typeof Blob' is not assignable to type '{ new (blobParts?: BlobPart[] | undefined, options?: BlobPropertyBag | undefined): Blob; prototype: Blob; }'.
  The types returned by 'prototype.stream()' are incompatible between these types.
    Type 'Readable' is missing the following properties from type 'ReadableStream<any>': locked, cancel, getReader, pipeThrough, and 2 more.

14  globalThis.Blob = Blob;
```

**Comment by trane** [comment]
It appears that node doesn't have `Blob` -- it uses `Buffer`. I wonder if making some target platform available in the configuration could allow the template to decide to use `Buffer` if set to `node`.

**Comment by ferdikoomen** [comment]
@trane @lgazo there is a new version 0.5.0-alpha that should resolve this issue, there is now support for Node.js clients, more info here: https://github.com/ferdikoomen/openapi-typescript-codegen#nodejs-support

**Comment by ferdikoomen** [comment]
0.5.0-beta ;-)

**Comment by ferdikoomen** [comment]
Just pushed 0.5.0 to NPM, closing this ticket.
