### ISSUE TITLE
Incorrect parsing of HTTP error responses with empty bodies

### ISSUE THREAD

**Issue by Alex0007** [ferdikoomen/openapi-typescript-codegen#324]
[Reference](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/60ae8a282cc992a224e870a15d4fca6ae875bbe4/src/templates/core/requestUsingFetch.ts#L21) to code

https://stackoverflow.com/questions/37280029/whatwg-fetch-fails-when-json-parsing-an-empty-response-how-can-i-prevent-it

Problem is: some API returns HTTP 401 Unauthorized with empty response body and `response.json()` throws an error `JSON.parse('')` (instead of relying on status code)

**Comment by ferdikoomen** [comment]
Hi @Alex0007 there is a try catch around the parser logic:
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/templates/core/requestUsingFetch.ts#L14-L29

Plus we only call response.json() when the response headers indicate the content should be "application/json". If the backend returns an empty body, then probably the backend is a better place to fix this?

**Comment by ferdikoomen** [comment]
Closing this due to no response
