### ISSUE TITLE
Generated project fails to build in create-react-app project

### ISSUE THREAD

**Issue by jedzej** [ferdikoomen/openapi-typescript-codegen#325]
**Experienced behavior**

I generated types definitions with CLI `openapi --input ./api_spec.yaml --output ./openapi`, but it fails to compile in unejected react app created with create-react-app CLI.

There are 2 problems:

Compilation error due to  :
```
C:/xxx/openapi/index.ts
TypeScript error in C:/xxx/openapi/index.ts(10,10):
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.  TS1205
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'

     8 | export { OpenAPI } from './core/OpenAPI';
     9 |
  > 10 | export { MyModel } from './models/MyModel';
```

After commenting out reexported modules I encountered second problem:
```
Failed to compile.

./openapi/core/ApiError.ts
SyntaxError: C:\xxx\openapi\core\ApiError.ts: Namespace not marked type-only declare. Non-declarative namespaces are only supported experimentally in Babel. To enable and review caveats see: https://babeljs.io/docs/en/babel-plugin-transform-typescript
  24 | }
  25 |
> 26 | export namespace ApiError {
     |                  ^^^^^^^^
  27 |     export enum Message {
  28 |         BAD_REQUEST = 'Bad Request',
  29 |         UNAUTHORIZED = 'Unauthorized',
```

**Expected behavior**

Generated code compiles properly without warnings.

**Comment by ferdikoomen** [comment]
@jedzej  I'll have a look at the first issue, but the second one is related to Babel, right now Babel does not support namespaces, so there is no way to use this library (see readme)

**Comment by jedzej** [comment]
@ferdikoomen Thanks for fast reply. Is there any proposed solution to the babel problem? It looks like the namespacing issue it's deeply rooted in the library, since the error is in the core part, not in my models. How would you suggest overcoming it?

**Comment by ferdikoomen** [comment]
Related: https://github.com/ferdikoomen/openapi-typescript-codegen/issues/345

**Comment by ferdikoomen** [comment]
@jedzej @ilyaulyanov @lcalisi I will push the final fixes for babel support today, documentation has already been updated: https://github.com/ferdikoomen/openapi-typescript-codegen#babel-support
Once the new version is out (0.5) then you can use `--useUnionTypes` inside your babel project to generate a fully supported API. Will keep you posted.

**Comment by ferdikoomen** [comment]
@jedzej @ilyaulyanov @lcalisi there is a new version 0.5.0-alpha that should resolve this issue, if you have time them please do check. More info on the flag here: https://github.com/ferdikoomen/openapi-typescript-codegen#enums-vs-union-types---useuniontypes and https://github.com/ferdikoomen/openapi-typescript-codegen#babel-support

**Comment by ferdikoomen** [comment]
0.5.0-beta ;-)

**Comment by philals** [comment]
Thanks @ferdikoomen 0.5.0-beta works and fixes this issue which I was having. Great stuff!

**Comment by lcalisi** [comment]
Yes, we are also having good luck with the new beta.

**Comment by ferdikoomen** [comment]
Thanks for testing. Just pushed 0.5.0 to NPM, closing this ticket.
