### ISSUE TITLE
string is generated as an interface

### ISSUE THREAD

**Issue by sahanatroam** [ferdikoomen/openapi-typescript-codegen#327]
**Describe the bug**
For some reason the following interface is generated when the command is run against the spec
```
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */


export interface string {
}
```

**Comment by sahanatroam** [comment]
hey @ferdikoomen do you have any updates on this ?

**Comment by balazssoltesz** [comment]
same here

**Comment by ferdikoomen** [comment]
@sahanatroam @balazssoltesz do you have a spec file where this happens? I'm not seeing this issue

**Comment by ferdikoomen** [comment]
Closing this due to no response
