### ISSUE TITLE
Generating Enums inside of namespaces doesn't work, alternative method possible?

### ISSUE THREAD

**Issue by lcalisi** [ferdikoomen/openapi-typescript-codegen#345]
Here is a hypothetical generated typescript generated code from your tool.

```
export interface Response {
    name: string;
    type: Response.type;
}

export namespace Response {
  export enum type {
    ERROR = 'ERROR',
    SUCCESS = 'SUCCESS',
  }
}
```

We realize this a known issue with Babel 7. However if the enum was generated this way then it works great with Babel 7. 

```
export interface Response {
    name: string;
    type: ResponseType;
}

export enum ResponseType {
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
}
```

Is there a reason why you chose to generate the code using the former method. Is it possible to add a flag to generate enums in the proposed style. The difference is the enum would append Type to the name of the interface. 

Thanks, Louis

**Comment by ilyaulyanov** [comment]
Experiencing the same issue, but with `ErrorMessage` enum. I also use Babel 7. Removing namespace resolves the type-check issue

**Comment by ferdikoomen** [comment]
Im closing this one, will continue in https://github.com/ferdikoomen/openapi-typescript-codegen/issues/345 to develop the babel compatible version of the generator
