### ISSUE TITLE
Support Axios as client

### ISSUE THREAD

**Issue by ilyaulyanov** [ferdikoomen/openapi-typescript-codegen#358]
**Describe the solution you'd like**
Currently, only XHR and Fetch are supported as clients. What would be required to add Axios as the request manager?

**Comment by lazharichir** [comment]
Using this for my GraphQL gateway to call my backend REST microservices exposing their OpenAPI schema... and I'd also love to use `Axios`.

**Comment by ferdikoomen** [comment]
This generator will stay focussed on having minimal library dependencies. If you want to fork this and build support for Axios then please go ahead :-) Or you can use something like: https://github.com/anttiviljami/openapi-client-axios or

**Comment by lroal** [comment]
I think supporting axios would be a great feature. Also, what I am missing today is the possibility to intercept the http calls and error handling. For example the token could be outdated and then I would like to display the login window. Only way to do this today, is to manually handle in with try catch on every call instead registering a handler on the instance.
