### ISSUE TITLE
OpenAPI3: Support Reusable Request Bodies

### ISSUE THREAD

**Issue by divyakarippath** [ferdikoomen/openapi-typescript-codegen#359]
Thank you team for the great work!

OpenAPI 3.0 supports reusable request bodies as shown in the below example. Right now the generator does not support this.

```
paths:
  /pets:
    post:
      summary: Add a new pet
      requestBody:
        $ref: '#/components/requestBodies/PetBody'
  /pets/{petId}
    put:
      summary: Update a pet
      parameters: [ ... ]
      requestBody:
        $ref: '#/components/requestBodies/PetBody'
components:
  requestBodies:
    PetBody:
      description: A JSON object containing pet information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
```

https://swagger.io/docs/specification/describing-request-body/

**Comment by ferdikoomen** [comment]
@divyakarippath Good point, indeed i did not load the ref for the request body, let me check if this is easy to fix

**Comment by ferdikoomen** [comment]
@divyakarippath I pushed a fix to the repository, will create a new version soon (0.5). Tomorrow I will fix a few more issues and then bundle this into the next release.

**Comment by divyakarippath** [comment]
Thank you @ferdikoomen .
