### ISSUE TITLE
Support export RequestOptions

### ISSUE THREAD

**Issue by feirpri** [ferdikoomen/openapi-typescript-codegen#360]
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ideally with a small example of the proposed changes.
希望增加输出 RequestOptions, 比如：
export const AppRequestOptions = {
       url: '/api/v1/getApps',
}

这样可以使用这个数据，自己选择 ajax client 封装request实现

**Comment by ferdikoomen** [comment]
Hi @feirpri The RequestOptions api is internal (and will always stay internal). You should be able to add all options through the Swagger / OpenAPI spec files (like the url example that you mention)
