### ISSUE TITLE
Lowercase PATCH methods are not fetch spec conform

### ISSUE THREAD

**Issue by maggo** [ferdikoomen/openapi-typescript-codegen#373]
We're having an issue with `PATCH` requests in our application using the generated API functions. The request just fails with a `net::ERR_HTTP2_PROTOCOL_ERROR` error message.

After digging around a bit I found out that methods are defined as all-lowercase (probably as they're coming from openapi spec?), which works for all other methods thanks to normalization, but `patch` is exempt as per the fetch spec. See here: https://fetch.spec.whatwg.org/#concept-method-normalize

## Proposed fix

Update method definitions to be all-uppercase

**Comment by ferdikoomen** [comment]
@maggo Good catch, i never had issues with this, but indeed we use the request method as defined in the spec, but we can use the correct uppercase method when we request this using fetch. I'll update this and bundle it into the 0.5 release (next release that is coming up.

**Comment by maggo** [comment]
Awesome, thank you!

**Comment by ferdikoomen** [comment]
@maggo there is a new version 0.5.0-alpha that should resolve this issue, if you have time them please do check. I'll also check this new build the next days, if all looks good I'll release the 0.5.0 version

**Comment by ferdikoomen** [comment]
0.5.0-beta ;-)

**Comment by maggo** [comment]
Had a look and it looks great :)

**Comment by ferdikoomen** [comment]
Thanks for testing. Just pushed 0.5.0 to NPM, closing this ticket.
