### ISSUE TITLE
Add --indent param for setting up indents in generated code

### ISSUE THREAD

**Issue by kirillurazov** [ferdikoomen/openapi-typescript-codegen#374]
How about to add settings param (e.g. console param --indent <value>) wich will setting up indents in generated code?

Not all users uses 4 spaces indents so will be very cool if we can to set indents.

P.S. sorry for my english 😅

**Comment by ferdikoomen** [comment]
The code follows the prettier default guidelines: https://prettier.io/. My advice would be not to worry about indentation, there are more important things in life :-)
