### ISSUE TITLE
[0.5.0-beta] "File" model name turns into "any" 

### ISSUE THREAD

**Issue by maggo** [ferdikoomen/openapi-typescript-codegen#375]
I just tried the 0.5.0 beta and came across a generation bug where the `File` model name is turned into `any`. Typescript will complain about `Interface name cannot be 'any'`

Here's a minimum spec to reproduce the behavior:

```yaml
swagger: "2.0"
info:
  version: v1
definitions:
  File:
    type: object
```

**Comment by ferdikoomen** [comment]
@maggo Yes i saw, i need to fix this for Node.js client + browser based clients (since Node.js does not know the concept of File / Blob)

**Comment by maggo** [comment]
Nice, thanks for the quick reply! We currently have our own fork of your project with some changes, but will be able to switch to 0.5.0 once this is fixed :)

**Comment by maggo** [comment]
Just built the latest master and everything seems to work! Would be great to get an npm release so we can test it in our project 🚀

**Comment by ferdikoomen** [comment]
Thanks for testing. Just pushed 0.5.0 to NPM, closing this ticket.
