### ISSUE TITLE
Non primitives loose their meaning in schemas

### ISSUE THREAD

**Issue by RowanDZ** [ferdikoomen/openapi-typescript-codegen#378]
Openapi 3.0

First of all, nice generator. Models and ApiServices seem to work fine. But for the schemas, I do have some issues, and generating Schemas is something that is really beneficial, above others.

Here is an example:
![image](https://user-images.githubusercontent.com/8612920/95198509-a573e400-07db-11eb-9e3b-5952cb89a1bd.png)

The array is defined like:
```
        issues:
          type: array
          items:
            $ref: '#/components/schemas/Issue'

```

Let's assume we use these schemas for frontend validations for input fields:

- `name` is fine, I see it's a type. Any props like isRequired, pattern, I can use.
- `entity` is less fine, but I could just `import * as Schemas from `index-of-schema` and do `Schemas[`${type}`]`, and check that object.
- `issues` is an issue :) . I see it's an array type, but this is where it stops.

Suggestion:

```
import {$EntityDto} from './$EntityDto';
import {$Issue} from './$IssueDto';


export const $SomeDto = {
    properties: {
        name: {
            type: 'string',
        },
        entity: {
            type: $EntityDto,
        },
        issues: {
            type: $Issue,
            array: true,
        },
    },
};

```

This way code should be able to dynamically determine what to do for settings properties on input fields, how to validate them..

**Comment by ferdikoomen** [comment]
@RowanDZ The issue here are circular references. When we generate interfaces that have a circular reference: 

```
import { ModelB } from './models';
export interface ModelA {
  prop: ModelB;
}

import { ModelA } from './models';
export interface ModelB {
  prop: ModelA
}
```

This is fine, because interfaces are just 'synthetic sugar' and the compiler wont care about these circular references. However the Schema objects are real objects, so something like this:

```
import { $ModelB } from './models';
export const $ModelA {
  prop: $ModelB;
}

import { $ModelA } from './models';
export const $ModelB {
  prop: $ModelA
}
```

...is invalid, because of the circular reference. May build tools will complain about this setup (Webback, Rollup, Babel, etc). There is no easy solution for this issue. You example will indeed work, but any more complex (real-world) backend will fail to then generate valid schema's.

**Comment by RowanDZ** [comment]
Hi @ferdikoomen . Actually there are no circular references in the code.
What is your expected result for my example? And the array having no reference to an object, that should not be right?
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/templates/partials/schemaArray.hbs , here you see the template for it, it indeed only gives 'array', that's it.

**Comment by ferdikoomen** [comment]
@RowanDZ I was talking about the last example you gave:

```
issues: {
   type: $Issue,
   array: true,
},
```

That `$Issue` is the problem with circular references (not in your specific example, but if we would use this generator on a larger project). But if we can start with specifying `array: true` and `type: 'Issue'` (as a string) then it would be fine. Would that work for you?

**Comment by RowanDZ** [comment]
I would say it would work, yes. Because then people can just do require or import * as .. and use the `'Issue'` as key.

**Comment by ferdikoomen** [comment]
Alright, let me see with i can do here @RowanDZ. Seems like a small change

**Comment by RowanDZ** [comment]
Nice, thanks! Then we can automate input validations 👍

**Comment by ferdikoomen** [comment]
@RowanDZ I got the following options:

### Option 1:

Schema for Array of booleans `Array<boolean>`
```
export const $ArrayWithBooleans = {
    array: {
        type: 'boolean',
    }
};
```
Schema for nested Array of booleans `Array<Array<boolean>`
```
export const $ArrayWithArray = {
    array: {
        array: {
            type: 'ModelWithString',
        },
    },
};
```

### Option 2:

Schema for Array of booleans `Array<boolean>`
```
export const $ArrayWithBooleans = {
    type: 'boolean',
    isArray: true,
};
```
Schema for nested Array of booleans `Array<Array<boolean>`
```
export const $ArrayWithArray = {
    type: {
        type: 'ModelWithString',
        isArray: true,
    },
    isArray: true,
};
```

preference?

**Comment by ferdikoomen** [comment]
Im in favour of the last one, since it still has the correct 'type' the schema is an array, but inside the array there is another 'type'.

**Comment by RowanDZ** [comment]
Option 1, feels more straight forward
Option 2, like you said.

Your repo, pick one. :) I think I'm with you for the second one

Op do 15 okt. 2020 om 18:31 schreef Ferdi Koomen <notifications@github.com>:

**Comment by ferdikoomen** [comment]
@RowanDZ Sure, but always good to have another opinion. I'm going for the second approach also for  @backwards compatibility, will push a new version soon (when the regexp stuff is fixed)

**Comment by ferdikoomen** [comment]
Pushed 0.5.3 to NPM
