### ISSUE TITLE
No properties for schemas created for root components

### ISSUE THREAD

**Issue by RowanDZ** [ferdikoomen/openapi-typescript-codegen#379]
OpenAPI 3.0

This:
![image](https://user-images.githubusercontent.com/8612920/95201387-2a60fc80-07e0-11eb-9e51-90b23b65e7e0.png)

Generates:
![image](https://user-images.githubusercontent.com/8612920/95200967-8a0ad800-07df-11eb-8665-a80f326880e4.png)

![image](https://user-images.githubusercontent.com/8612920/95201056-ac9cf100-07df-11eb-8ccf-5881202d6785.png)

Hence:
- The SomethingElse schema is missing `pattern` and `required`
- The pattern that is being generated for the Something.props.name, is not escaped properly (should become '^\\\w+$', double back-slashed)

Expected:
![image](https://user-images.githubusercontent.com/8612920/95201610-7744d300-07e0-11eb-8648-cf5a86bb39f6.png)

![image](https://user-images.githubusercontent.com/8612920/95201640-8035a480-07e0-11eb-8ce0-0baf3f610837.png)

Also, the schemas are not typed.
Adding `turtle: true` to the openapi spec, is not valid, so the typing could be made, because it shouldn't contain random keys

**Comment by ferdikoomen** [comment]
@RowanDZ Wow.. weirdly enough this did work for the V2 spec, but was missed in the V3 spec. It's fixed now, will push a change soon and publish 0.5.3 (hopefully including your other request)

**Comment by ferdikoomen** [comment]
The pattern is correct i believe, scroll down to "pattern" here: https://swagger.io/docs/specification/data-models/data-types/. The example is: '^\d{3}-\d{2}-\d{4}$', you can plug that into a RegExp like: `new RegExp('^\d{3}-\d{2}-\d{4}$', 'g')`.

**Comment by RowanDZ** [comment]
> The pattern is correct i believe, scroll down to "pattern" here: https://swagger.io/docs/specification/data-models/data-types/. The example is: '^\d{3}-\d{2}-\d{4}$', you can plug that into a RegExp like: `new RegExp('^\d{3}-\d{2}-\d{4}$', 'g')`.

The problem is, that this string that is being produced, with a single backslash, doesn't work for RegExp. It needs to be espaced.
So or the generator need to make a regexp `/^\w+$/`, or a string with double backslash `"^\\w+$"`.
I would say the latter, so it's usable as a `pattern` html attribute too.

Plaatje bij het praatje:
![image](https://user-images.githubusercontent.com/8612920/96152257-a4922f00-0f0c-11eb-8a23-226f4f5b7ead.png)

**Comment by ferdikoomen** [comment]
@RowanDZ then you need to update the backend, the Swagger spec dictates the regexp should follow the regular expression syntax used is from JavaScript (more specifically, ECMA 262)

**Comment by ferdikoomen** [comment]
oh wait sorry, now i get it! never mind i was reading the comments wrong!

**Comment by ferdikoomen** [comment]
yes i will escape the "\"

**Comment by ferdikoomen** [comment]
Im thinking that maybe exposing them as actual regexp makes sense... `/^\w+$/` if you want to change then (like make global or multiline then you can still do: `new RegExp(/^\w+$/, 'gm');`.

**Comment by RowanDZ** [comment]
If it's like `pattern: /^\w+$/`, then you end up with an RegExp instance. Which can be fine, but if you want to use it in an html input, you need to do `toString()` first. And: if you call it pattern, it should be a pattern, not a regexp. I think it makes the most sense to keep it a string (escaped), so it stays close to the spec and people can do new RegExp(pattern) themselves?

**Comment by ferdikoomen** [comment]
Your 'its a pattern not a regexp' makes sense. And indeed its easier to use in form fields (the main use case anyway).

**Comment by ferdikoomen** [comment]
Pushed 0.5.3 to NPM
