### ISSUE TITLE
ESLint Parsing error: Declaration or statement expected

### ISSUE THREAD

**Issue by mr-bjerre** [ferdikoomen/openapi-typescript-codegen#382]
I'm getting multiple linting errors from the script created by running

    npx openapi-typescript-codegen -i http://localhost:8080/openapi.json -o ./src/api

The first error I get is 

```typescript
TypeScript error in ./src/api/core/ApiError.ts(4,13):
'=' expected.  TS1005

    2 | /* tslint:disable */
    3 | /* eslint-disable */
  > 4 | import type { ApiResult } from './ApiResult';
      |             ^
    5 | 
    6 | export class ApiError extends Error {
    7 |     public readonly url: string;
```

I'm also getting `Parsing error: Declaration or statement expected` in VSCode when looking in `./src/api/index.ts` on the `export type` statements. I'm clueless whats actually the issue here?

**Comment by ferdikoomen** [comment]
@mr-bjerre Can you check what typescript version you are using? We are supporting typescript 3.8... But if needed i can probably create some support for older versions.

**Comment by mr-bjerre** [comment]
Oh my mistake. I was on 3.7 - updating now. Thanks

**Comment by ferdikoomen** [comment]
@mr-bjerre No problem, ill update the documentation to mention this.
