### ISSUE TITLE
Ship NPM package with typings

### ISSUE THREAD

**Issue by lukeautry** [ferdikoomen/openapi-typescript-codegen#383]
I want to use this from a node.js client, but there's no type declaration shipped with the package and no @types package either.

**Comment by ferdikoomen** [comment]
@lukeautry You meen using the generator itself in NodeJS? Or do you want to generate NodeJS compatible REST API client? If it's the first then sure, we can add some typings. If it's the last then just see: https://github.com/ferdikoomen/openapi-typescript-codegen#nodejs-support

**Comment by ferdikoomen** [comment]
@lukeautry I just added types: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/types/index.d.ts, will be in the next release (0.5.2). Need to finalise some additional work for two tickets.

**Comment by lukeautry** [comment]
I meant the generator itself. Looks great, thanks!

**Comment by ferdikoomen** [comment]
@lukeautry pushed 0.5.2 to NPM that should have typings!
