### ISSUE TITLE
at sign (@) causing compilation error in generated files

### ISSUE THREAD

**Issue by cpoliver** [ferdikoomen/openapi-typescript-codegen#384]
When running the code generation script against a C# oData API, the properties preceded with an "@" are not properly quoted, and cause compilation errors.

Please see [this gist](https://gist.github.com/cpoliver/02a560ffd35810c1a6e8fd5bbe4b5b20) for an example of the output, and how I've manually fixed the issue, by quoting the properties beginning with an "@"

Screenshot of the error thrown when running tsc against the generated code:
![image](https://user-images.githubusercontent.com/1554333/95980859-af1dcd00-0e15-11eb-85ae-554878c091a8.png)

**Comment by ferdikoomen** [comment]
@cpoliver do you have a snippet of the spec that you are using? (or the whole spec if you are allowed to share that)?

**Comment by cpoliver** [comment]
Hey @ferdikoomen thank you for the super fast response.

I've added reduced example of the paths object from the swagger api to the gist, [available to view here](https://gist.github.com/cpoliver/02a560ffd35810c1a6e8fd5bbe4b5b20#file-swagger_paths-json)

If you need more I can probably provide it, but hopefully this should cut out a lot of the noise. Let me know if you need any more info.

Also, here's a link to some of the MS spec/docs around their oData APIs: https://docs.microsoft.com/en-us/odata/concepts/get-data 

Many thanks,

Charlue

**Comment by ferdikoomen** [comment]
@cpoliver I pushed 0.5.2 to NPM, can you check if this solves your issue?

**Comment by cpoliver** [comment]
Hey @ferdikoomen - that is working like a charm now. Thank you for the quick fix 🙇

**Comment by ferdikoomen** [comment]
👍🏻
