### ISSUE TITLE
Using `required` in a parent for a ref doesn't make it required

### ISSUE THREAD

**Issue by RowanDZ** [ferdikoomen/openapi-typescript-codegen#385]
Given the yaml OpenAPI 3.0:
```
SomeAbstractDto:
    properties:
      name:
        type: string
      age:
        type: number

SomeDto:
      required:
        - name
      allOf:
        - $ref: '#/components/schemas/SomeAbstractDto'
```

This generates:
```
interface SomeAbstractDto {
  name?: string;
  age?: number;
}

interface SomeDto extends SomeAbstractDto {}
```

Expected is:
```
interface SomeAbstractDto {
  name?: string;
  age?: number;
}

interface SomeDto extends SomeAbstractDto {
  name: string;
}
```

I hope this can be resolved!

**Comment by RowanDZ** [comment]
I have to admit here:
The same happens to Java models made from the same spec (don't know the generator). Maybe it is something that is not according to spec, or the same core is used under the hood of both generators?

**Comment by ferdikoomen** [comment]
This is expected. You are not specifying a property. So, the required does now know what it applies to. AllOf 'just' extends the model, but that is where the fun stops.

**Comment by RowanDZ** [comment]
Hmm, limited fun then ;) Thanks for the quick response. Closing!
