### ISSUE TITLE
Improve maintainability score

### ISSUE THREAD

**Issue by ferdikoomen** [ferdikoomen/openapi-typescript-codegen#387]
Improve maintainability score: https://codeclimate.com/github/ferdikoomen/openapi-typescript-codegen
- Removing duplicate files between V2 and V3 generator (possibly move then to a shared folder)
- Splitting up larger files into sub routines (parseModel for instance)

**Comment by 0xorial** [comment]
Somewhat related - are tests supposed to work? I got following with `yarn test`:
```
Snapshot Summary
 › 2 snapshots failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 7 failed, 47 passed, 54 total
Tests:       8 failed, 66 passed, 74 total
Snapshots:   2 failed, 203 passed, 205 total
Time:        6.983 s
```

**Comment by ferdikoomen** [comment]
Should work indeed :-) https://travis-ci.org/github/ferdikoomen/openapi-typescript-codegen

**Comment by ferdikoomen** [comment]
Closing this, will do a rewrite at some point, but will create a few architectural ideas first
