### ISSUE TITLE
Add support for getting response headers and response body at the same time

### ISSUE THREAD

**Issue by mrBrownys** [ferdikoomen/openapi-typescript-codegen#388]
generated/request.ts

![Снимок экрана 2020-10-17 в 16 10 12](https://user-images.githubusercontent.com/71230349/96337953-683d0b00-1093-11eb-8322-241fb1d0900a.png)

**Comment by ferdikoomen** [comment]
@mrBrownys reason for this is that the OpenAPI doec allows you to get a response from a header OR from the body, but not both (if i'm not mistaken, unless you have a spec that has this?)

**Comment by mrBrownys** [comment]
@ferdikoomen you are right, I couldn't find an example either. But this happens sometimes in those places where you are unable to change the Open Api Description. What are your thoughts on accessing the original answer from fetch to get the headers manually?

**Comment by ferdikoomen** [comment]
Well you need to define the spec to request the headers, if you want full access to the request and all the headers then it's probably easier to request all your stuff yourself and dont use this library. This hides a lot of this code and only focusses on the responses you should get based on the OpenAPI spec that you give it.

**Comment by mrBrownys** [comment]
@ferdikoomen You are right, I am closing the issue. Thanks for answers.

**Comment by jsnanigans** [comment]
@ferdikoomen I would like to reopen this issue, please.

We are currently implementing the ETag for an API endpoint. To follow the specs, we would need to get the ETag from the response header. We also need access to the body of the response, if the resource has been modified.
Here is the spec: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
