### ISSUE TITLE
Bug with FormData in generated code Illuminated in VSCode 

### ISSUE THREAD

**Issue by mrBrownys** [ferdikoomen/openapi-typescript-codegen#389]
VSCode - latest
TS - 4.0.3

TSConfig.json 

> {
>   "compilerOptions": {
>     "module": "commonjs",
>     "outDir": "dist",
>     "removeComments": true,
>     "sourceMap": true,
> 
>     "target": "ESNext",
>     "resolveJsonModule": true,
> 
>     /* Strict Type-Checking Options */
>     "strict": true,
>     "noImplicitAny": true,
>     "strictNullChecks": true,
>     "strictFunctionTypes": true,
>     "strictBindCallApply": true,
>     "strictPropertyInitialization": true,
>     "noImplicitThis": true,
>     "alwaysStrict": true,
> 
>     /* Additional Checks */
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "noImplicitReturns": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     /* Module Resolution Options */
>     "moduleResolution": "node",
>     "esModuleInterop": true,
> 
>     /* Experimental Options */
>     "experimentalDecorators": true,
>     "emitDecoratorMetadata": true,
>     "downlevelIteration": true,
> 
>     /* Advanced Options */
>     "forceConsistentCasingInFileNames": true,
>     "types": ["node"],
>     "typeRoots": ["node_modules/@types"]
>   },
>   "include": ["src/**/*.ts", "generated/**/*.ts"],
>   "exclude": []
> }

generated/core/request.ts

![Снимок экрана 2020-10-17 в 16 17 34](https://user-images.githubusercontent.com/71230349/96338126-b7377000-1094-11eb-9b3e-8aeae4e2d87b.png)

Troubleshooting suggestions:
![Снимок экрана 2020-10-17 в 16 29 04](https://user-images.githubusercontent.com/71230349/96338346-f914e600-1095-11eb-940f-307828a6b02f.png)

**Comment by ferdikoomen** [comment]
@mrBrownys You will need to include the "dom" lib in your tsconfig, since FormData is a default browser class: `"lib": ["es6", "dom"],`. Unless you are building a NodeJS project, in that case: please read: https://github.com/ferdikoomen/openapi-typescript-codegen#nodejs-support

**Comment by mrBrownys** [comment]
Yes, I am building a project for NodeJS. Following this instruction:
https://github.com/ferdikoomen/openapi-typescript-codegen#nodejs-support. I added build flag -c node and installed dependencies: @ types / node-fetch, node-fetch, form-data.
But TypeScript is throwing an error:

> /node_modules/ts-node/src/index.ts:500
> [0]     return new TSError(diagnosticText, diagnosticCodes)
> [0]            ^
> [0] TSError: ⨯ Unable to compile TypeScript:
> [0] generated/api/core/request.ts(61,26): error TS2351: This expression is not constructable.
> [0]   Type 'typeof FormData' has no construct signatures.


For this line of request.ts: 
`const formData = new FormData();`
![Снимок экрана 2020-10-19 в 10 14 12](https://user-images.githubusercontent.com/71230349/96413129-db5d9300-11f3-11eb-8a2b-23480b3d1f2a.png)

This is my package.json:

> {
  "name": "edo.server",
  "version": "1.0.0",
  "private": true,
  "main": "dist/src/server.js",
  "dependencies": {
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-http-proxy": "^1.6.2",
    "express-session": "^1.17.1",
    "form-data": "^3.0.0",
    "ip": "^1.1.5",
    "morgan": "^1.10.0",
    "node-fetch": "^2.6.1",
    "passport": "^0.4.1",
    "passport-local": "^1.0.0",
    "request": "^2.88.2",
    "swagger-ui-express": "^4.1.4",
    "tslib": "^2.0.1",
    "tsoa": "^3.2.1",
    "winston": "^3.3.3"
  },
  "scripts": {
    "dev": "concurrently 'nodemon' 'nodemon -x tsoa spec-and-routes'",
    "build": "tsoa spec-and-routes && tsc",
    "start": "node dist/src/server.js",
    "lint": "eslint --cache  src/**/*.ts src/*.ts",
    "generate.api": "openapi -i ./generated/spec/api.json -o ./generated/api -c node --useOptions  true"
  },
  "lint-staged": {
    "src/**/*.ts": "eslint --fix"
  },
  "devDependencies": {
    "@types/express": "^4.17.8",
    "@types/express-http-proxy": "^1.6.1",
    "@types/express-session": "^1.17.0",
    "@types/ip": "^1.1.0",
    "@types/morgan": "^1.9.1",
    "@types/node": "^14.10.1",
    "@types/node-fetch": "^2.5.7",
    "@types/nodemon": "^1.19.0",
    "@types/passport": "^1.0.4",
    "@types/passport-local": "^1.0.33",
    "@types/swagger-ui-express": "^4.1.2",
    "@typescript-eslint/eslint-plugin": "^4.1.1",
    "@typescript-eslint/parser": "^4.1.1",
    "concurrently": "^5.3.0",
    "eslint": "^7.9.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-promise": "^4.2.1",
    "husky": "^4.3.0",
    "lint-staged": "^10.4.0",
    "nodemon": "^2.0.4",
    "openapi-typescript-codegen": "^0.5.2",
    "prettier": "^2.1.2",
    "ts-node": "^9.0.0",
    "typescript": "^4.0.2"
  }
}

**Comment by ferdikoomen** [comment]
Hi @mrBrownys there are some extensive tests with the generator and they all work with Typescript and NodeJS.The line `import * as FormData from 'form-data';` should be correct. `import FormData from 'form-data';` is only allowed if allowSyntheticDefaultImports is enabled in tsconfig. Or maybe this works because esModuleInterop is enabled? Not sure. I see there are a lot of options in your tsconfig, my best bet would be to see if esModuleInterop could be disabled.

**Comment by rattkin** [comment]
I seem to have the same problem. disabling it allows to compile. however vscode still complains that error TS2351: This expression is not constructable.

**Comment by rattkin** [comment]
> I seem to have the same problem. disabling it allows to compile.
our app compiles without esModuleInterop , but doesn't work.
i have to abandon generated client

**Comment by mrBrownys** [comment]
@rattkin I followed the advice and disabled allowSyntheticDefaultImports, but I agree the moment is unpleasant

**Comment by ferdikoomen** [comment]
I will put the import to import FormData from 'form-data'; and put a note that you will need allowSyntheticDefaultImports, that seems like a sensible default

**Comment by mrBrownys** [comment]
> I will put the import to import FormData from 'form-data'; and put a note that you will need allowSyntheticDefaultImports, that seems like a sensible default

really cool news, thanks! 🦾🔝
