### ISSUE TITLE
Enable different template for services generation

### ISSUE THREAD

**Issue by yanivbeaudoin** [ferdikoomen/openapi-typescript-codegen#390]
Hey!

First, thank you for your work on the repo, it's very useful!

One thing that doesn't work for me is the way that the service fill is organized.
I use react-query so I prefer the output of the generator to generate hooks as react-query suggests to.
Of course that not everybody that will use the generator will use react query.
So what I suggest to add some way to use the parser without using the service output. 

Maybe to export the getService so I can use it and generate my own way of wrapping my requests?
Or maybe add an option to chose an output template?

Hope it makes sense.
Thanks
Yaniv

**Comment by ferdikoomen** [comment]
@yanivbeaudoin There is no way (yet) to provide these templates or write your own services. But can't you do this in ReactQuery:
```
const { isLoading, error, data } = useQuery('todos', () =>
   MyService.getAllTodos()
);
```
Where MyService.getAllTodos would be the calls generated by the client?

**Comment by ferdikoomen** [comment]
Closing this due to no response
