### ISSUE TITLE
Incorrectly generates types and filenames starting with numbers

### ISSUE THREAD

**Issue by fnky** [ferdikoomen/openapi-typescript-codegen#397]
Running codegen with [this schema](https://gist.githubusercontent.com/ioggstream/f4583730eb7d4e264ba1270727b2f91b/raw/954ae7d47183aa118bfc5465887e8373c3de6483/psd2-api-1.3.3) will create some models with exported types like `001.ts`, `052.ts`, etc. which results in syntax errors.

These types are defined by components with names that are separated by a period (`.`) and has segments starting with numbers, like `camt.052` and `paymentInitiationSct_pain.001`.

They likely also conflict with one another, but I haven't tested this.

**Comment by ferdikoomen** [comment]
@fnky I'm investigating this now. Will get back shortly

**Comment by ferdikoomen** [comment]
@fnky Nice spec BTW :-) I fixed the issues, you can use the new 0.5.4 version and then everything should be fine again.

**Comment by fnky** [comment]
Great! Thanks for the quick reply :-)
