### ISSUE TITLE
Dashes are not converted correctly

### ISSUE THREAD

**Issue by fnky** [ferdikoomen/openapi-typescript-codegen#398]
Running codegen against [this schema](https://gist.githubusercontent.com/ioggstream/f4583730eb7d4e264ba1270727b2f91b/raw/954ae7d47183aa118bfc5465887e8373c3de6483/psd2-api-1.3.3) produces a type for `periodicPaymentInitiation_xml-Part2-standingorderType_json`, but doesn't correctly convert the dashes (`-`) into valid type name, causing syntax errors.

**Comment by ferdikoomen** [comment]
@fnky I'm investigating this now. Will get back shortly

**Comment by ferdikoomen** [comment]
@fnky Nice spec BTW :-) I fixed the issues, you can use the new 0.5.4 version and then everything should be fine again.

**Comment by fnky** [comment]
Great! Thanks for the quick reply :-)
