### ISSUE TITLE
Support for custom request-function

### ISSUE THREAD

**Issue by nils4cosee** [ferdikoomen/openapi-typescript-codegen#400]
**Describe the solution you'd like**
In our last project, we have used a custom axios setup to access the backend. One thing that would not have been possible with "openapi-typescript-codegen" is the axios-interceptor that retrieves the the current language settings from "i18next" and adds a query parameter to the outgoing request. It was very convenient to do it this way, because from that point on, we didn't have to worry about transmitting the correct language anymore.

I would like to see a mechanism that uses a custom request-function. That way, everybody can write an adapter if needed.

The following changes 

```typescript
// OpenAPI.ts
export type RequestFunction = (options: ApiRequestOptions) => Promise<ApiResult>;

interface Config {
    BASE: string;
    VERSION: string;
    WITH_CREDENTIALS: boolean;
    TOKEN: string | (() => Promise<string>);
    requestFunction?: RequestFunction;  // added
}

// request.ts
export async function request(options: ApiRequestOptions): Promise<ApiResult> {
     if (OpenAPI.requestfunction != null) {
         return OpenAPI.requestFunction(options);
     }
     ...
}

```

would allow a configuration similar to the bearer-token:

```typescript

OpenAPI.requestFunction = async (options) => {
    ...
    return {
        ...
    }
}
```

I briefly thought about using your library in our project, but it was too late by then. In the next project, maybe. It could be a huge time-saver.

**Comment by ferdikoomen** [comment]
@nils4cosee The reason there is no 'requestFunction' is because the generator support fetch and XHR and both have quite different API options. The reason for supporting only these options is because this needs to be a lightweight 'no-libraries / no-dependencies' client. I get the idea of changing internals or creating these 'callbacks' (its been requested before), but for these advanced use cases you are better of with the JAVA based openapi-codegen. 

But let me look at it from a different view: How would your SPEC look like if you always need this 'language' property? Would there be this prop for each of the service calls?

**Comment by nils4cosee** [comment]
I have had a look at the swagger-spec of our API again. The query-param is currently not part of all endpoints. This is mainly, because we auto-generate the spec from the Spring-Boot endpoints and the query-parameter is processed in a Filter before the Controller classes are invoked. Since the parameter is universal, I would like to treat it in a universal fashion in the frontend as well. And I really don't want to pull any Java-dependencies into the frontend project..

The change could also be done by adding a new request-type ("customRequest" instead of "node", "xhr" or "fetch") which creates a function that delegates to `OpenAPI.requestFunction`. I think the result could still be called "lightweight". It would not add any dependencies. It would be the responsibility of user to provide the request function, including any dependencies.

I can create a small PR to illustrate what I mean.

--- 

When I think about it:

**Comment by ferdikoomen** [comment]
Closing this one, we now have a --request option that you can use to pass a custom request function.

**Comment by illicit-oblivion** [comment]
> Closing this one, we now have a --request option that you can use to pass a custom request function.

hi is there an example how to extend the default request function so that we can handle 401s for example?

**Comment by ferdikoomen** [comment]
@illicit-oblivion The correct way to handle errors is specifying them in the OpenAPI spec, something like:
```
"/api/some-call-with-errros": {
    "get": {
        "operationId": "SomeCallWithErrors",
        "responses": {
            "200": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "401": {
                "description": "My custom 401 server error"
            },
            "404": {
                "description": "My custom 404 server error"
            }
        }
    }
}
```
The OpenAPI client should throw you an `ApiError` object with the `message` being that custom error.

You should be able to do a try catch around the call and get any error there like:
```
try {
   await MyService.SomeCallWithErrors();
} catch (e) {
   console.log(e.message); // <-- General message or message specified in OpenApi spec
   console.log(e.status); // <-- Status code from the request (401, 404, 500, etc).
   console.log(e.statusText); // <-- Status text (depends on client and browser)
   console.log(e.body); // <-- Any data that the server has send back
}
```

**Comment by illicit-oblivion** [comment]
@ferdikoomen I see, but according to this example i should handle error in each request, but can i somehow catch 401s error globally

**Comment by ferdikoomen** [comment]
@illicit-oblivion Yes, its each request indeed. But you can write a simple handler function for this and reuse it off-course. What you could do, _but it's a bit of a hack_, is use the Axios client (`--client axios`) and register an interceptor: https://axios-http.com/docs/interceptors this can intercept each request and handle errors like this gobally.

**Comment by yondh** [comment]
@ferdikoomen Do you have an example of registering an interceptor on axios client?
