### ISSUE TITLE
Add custom headers

### ISSUE THREAD

**Issue by nandorojo** [ferdikoomen/openapi-typescript-codegen#401]
It would be nice to be able to add custom headers to a request. This is already possible with `TOKEN`, so headers would be a nice addition.

```js
import { OpenAPI } from 'openapi-typescript-codegen'

OpenAPI.HEADERS = {
  screenWidth: Dimensions.screenWidth
}
```

**Comment by ferdikoomen** [comment]
@nandorojo You can add these headers in the OpenAPI spec: https://swagger.io/specification/#header-object. In case you want so use them every time, then maybe a lightweight wrapper would be an idea? Reason for this strictness is: If we do this for (default) headers, then we should also do this for (default) parameters or (default) cookies. And this is not the role of the client generator.
