### ISSUE TITLE
Add support for custom templates

### ISSUE THREAD

**Issue by ZakharDolozhevskiy** [ferdikoomen/openapi-typescript-codegen#402]
Hello, 

I have started to use a generator and found it impossible to change predefined templates. My particular case is to tweak a bit services template to change parameters structure and convert to simple functions instead of the class instance with methods

Idea: 

As you probably know [openapi-generator](https://github.com/OpenAPITools/openapi-generator) has customization for templates and they allow to define the path to custom template files, files should have the same name as files in the template generator and it would be awesome to have it here as well ( at least for services, models, schemas ) 

Usage:

`openapi --input ./example.json --output ./dist --templates ./custom-templates`

and custom-templates folder extend the same structure of templates what the package openapi-typescript-codegen has

**Comment by ferdikoomen** [comment]
@ZakharDolozhevskiy The idea behind this generator is to have a strict use case, in case you want to use custom templates, then the Java based codegen is a better alternative for these advanced use-cases https://openapi-generator.tech/docs/templating/
