### ISSUE TITLE
Authorization header instead of `Bearer`

### ISSUE THREAD

**Issue by cobraz** [ferdikoomen/openapi-typescript-codegen#411]
Thank you so much for this library 🙏 I come from Swagger/OpenAPI Codegenerator, and this is so much better! ❤️

I see that many users are requesting the ability to add headers. Myself, I am looking for a way to apply `Basic` auth. Right now, I am adding that functionality by editing `core/OpenAPI.ts` and `core/request.ts`. This is making me unable to generate freely.

In my implementation, I am replacing `getToken` with this:

```typescript
async function getToken(): Promise<string> {
  const token = typeof OpenAPI.TOKEN === 'function' ? await OpenAPI.TOKEN() : OpenAPI.TOKEN;
  const username =
    (typeof OpenAPI.USERNAME === 'function' ? await OpenAPI.USERNAME() : OpenAPI.USERNAME) || '0';
  return token && `Basic ${btoa(`${username}:${token}`)}`;
}
```

and replacing the `Authorization` part with this:

```typescript
const authHeader = await getToken();
  if (isDefined(authHeader) && authHeader !== '') {
    headers.append('Authorization', authHeader);
  }
```

I am also adding `USERNAME` to `OpenAPI` object.

However, if you disable core files in the generator (with `--exportCore false`) they all are deleted.

Possible fixes:

1. Add an idiomatic way to extend core files (hooks, custom configuration)
2. Do not delete core files if they exist.
3. Add attribute that can reference to where core files/request can be found.

I tend to like number 3 best, since the way I organize the project is with all generated files in a `generated/` folder.

**Comment by ferdikoomen** [comment]
@cobraz There will be a next version uploaded to nexus soon. I have fixed the deletion of core files (and other). Plus added properties for USERNAME and PASSWORD, plus the ability to set customer (default) HEADERS for each request. is you specify the username and password then the correct authorisation header is set

**Comment by ferdikoomen** [comment]
The new version will be: 0.6.0, but need to fix a few more issues today before i will push that
