### ISSUE TITLE
Improve support for `anyOf`, `oneOf`, and `allOf`

### ISSUE THREAD

**Issue by budde377** [ferdikoomen/openapi-typescript-codegen#420]
**Describe the solution you'd like**
The current implementation only supports `xOf` of references.

This PR (#419) adds support for not only directories but other types as well using TypeScripts union an intersection.

**Comment by ferdikoomen** [comment]
@budde377 cool thanks! Right now there are two PR's:
https://github.com/ferdikoomen/openapi-typescript-codegen/pull/419
https://github.com/ferdikoomen/openapi-typescript-codegen/pull/399
Let me check how they can be combined :-)

**Comment by ferdikoomen** [comment]
Closing this on and will continue in this thread: https://github.com/ferdikoomen/openapi-typescript-codegen/issues/141
