### ISSUE TITLE
Improve build tool

### ISSUE THREAD

**Issue by yordis** [ferdikoomen/openapi-typescript-codegen#427]
Would love to leverage the internal code for generating the TypeScript types for an alternative code-gen tool: https://github.com/straw-hat-team/openapi-web-sdk-generator. You have done an amazing job generating the TypeScript types and took some decisions around some metadata.

Fundamentally both tools do the same, different solutions when it comes to generating clients. I tried to leverage your code so since it would be much better to collaborate than re-invent the wheel.

But it seems that you compile this package into a single file, so I can't import the parser and some of your internal functions.

### Proposal

I would propose two solutions:

1. Change the build step to output multiple files rather than one file
2. Change the repo to mono-repo and create multiple packages

**Comment by ferdikoomen** [comment]
@yordis the goals of this library is a fast and zero config OpenAPI client generation. This is largely done by pre-processing all Handlebar templates and making sure the dependency load in NodeJS is kept to a minimum. This is why there is just one file with a bunch of jiberish :-) but on large projects this generation speed is a huge timesaver (specially if you generate stuff during a build step). The goal is not to make a 'toolkit' or some kind of über configurable setup. For these scenarios the OpenAPI JAVA codegen is much better. 
I can imagine that we could split up the project into mono-repos and export independent packages like parser and what not.. but what would be the goal? I mean feel free to just grab what you need from my code and use it in your library :-)

**Comment by ferdikoomen** [comment]
Btw you can use the library inside NodeJS like any other. The Node API also gives you the option to just generate specific parts

,,,
const path = require('path');
const openapi = require('openapi-typescript-codegen');

const spec = {
  // your spec
};

openapi.generate({
  input: spec,
  output: path.resolve(__dirname, 'generated'),
  exportCore: false,
  exportServices: true,
  // etc...
});

You can generate just the models or the services, but write your own request layer (core)

Not sure if that would work for you?

,,,

**Comment by yordis** [comment]
> For these scenarios the OpenAPI JAVA codegen is much better.

But it is Java 😅 

> we could split up the project into mono-repos and export independent packages like parser and what not.. but what would be the goal?

@ferdikoomen some of my generations deviate from this one, my goal is pretty much the same, just that we have two different routes to generate the clients, folders, and what have you.

Here are some core things that the package does differently from others

- Operations are organized per file and each operation is a function (tree-shaking friendly)
- We use `x-directories` to organize the operation files
- Operations takes a client as a first param, being agnostic of the implementation of such client (give you control over the final client, agnostic of the environment)
- Operations take a `param` argument that has 3 keys: query, body, path params (allow you to avoid collisions passing data, and also it is explicit about what the data is for)
- We used it before 🤷🏻  so we need how it works 😄 

> I mean feel free to just grab what you need from my code and use it in your library :-)

I could, but having the same codebase and collaborate together would be much better.

> You can generate just the models or the services, but write your own request layer (core)

I will give it a try, but code-gen the types for the individual, the only concern is generating the typespec for the `params` argument: https://github.com/straw-hat-team/openapi-web-sdk-generator/blob/d5c0ddc785487542b792e9ab885839224bf879ad/templates/operation.ts.ejs#L4-L14

**Comment by ferdikoomen** [comment]
@yordis closing this story, there will be a new version in the future with better abstraction (exporting services that dont have a (direct) dependency on a client is hight on the list. Similar to improving some tooling. But right now I will not make any big changes. Mainly due to time restrictions.
