### ISSUE TITLE
Ability to set "global" headers on client generation

### ISSUE THREAD

**Issue by Alex0007** [ferdikoomen/openapi-typescript-codegen#429]
![image](https://user-images.githubusercontent.com/1143226/99484399-25b46a00-2982-11eb-9baf-4ba300cc5f67.png)

I want to specify some "global" headers to pass package version to API (for example `X-Client` header)
I have [implemented](https://github.com/Alex0007/openapi-typescript-codegen/commit/fb6d48bda9ad0509d71f68b3c44927c9d48a9c9c) this functionality in my fork (but now it's too outdated comparing to current master branch)

Current `openapi-typescript-codegen` situation: headers can be set when using generated code only (not when generating client).

Maybe idea isn't that bad and can be added into this project?

**Comment by ferdikoomen** [comment]
@Alex0007 closing this one. Recently we had some similar requirements and it's easy to set these headers in runtime, or alternatively publish a package from the generated client with those headers set.
