### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by MikeYermolayev** [ferdikoomen/openapi-typescript-codegen#435]
**Describe the bug**
Hi, I'm trying to use this codegen with Discourse openapi.json file (https://docs.discourse.org/) but what I get is this error:

![image](https://user-images.githubusercontent.com/8783498/99852173-7ea61d00-2b91-11eb-9059-690a641992eb.png)

Any ideas what's wrong? Thanks in advance

**Comment by MikeYermolayev** [comment]
Hm, looks like I've found the problem.

The problem occurs because this openapi file doesn't describe schema for parameters. It describes it as:

"/c/{id}.json": {
      "get": {
        "description": "Get a list of topics in the specified category\n",
        "tags": ["Categories"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
But should as

"/c/{id}.json": {
      "get": {
        "description": "Get a list of topics in the specified category\n",
        "tags": ["Categories"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
So I guess it's expected behavior

**Comment by ferdikoomen** [comment]
@MikeYermolayev Indeed, im working on the @next version of the library that will have the option to validate the spec before parsing it, this will help in these cases.
