### ISSUE TITLE
index.ts exports can have naming collisions when model name ends in 'Service'

### ISSUE THREAD

**Issue by Nixes** [ferdikoomen/openapi-typescript-codegen#436]
**Describe the bug**
The list of index.ts exports can have naming collisions when a model name also ends in 'Service'.
This results in a Typescript compile error of "Error: TS2300: Duplicate identifier 'ActiveService '."

Solutions I can think of that might prevent this: 
- 'Service' could be postfixed to the name of the Service even if it already contains the word 'Service'. In this case maybe ActiveServiceService.
- The models could be postfixed with 'Model' too.
- Models and services could be exported individually from within their own source files.

Example currently generated code: 
```ts
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { OpenAPI } from './core/OpenAPI';

export type { ActiveService } from './models/ActiveService';

export { ActiveService } from './services/ActiveService';
```

**Comment by ferdikoomen** [comment]
@Nixes Makes sense, im thinking about dropping the PostFixes actually, since i've seen a few places where this goes wrong. Or have the ability to overwrite them somehow. I've put this on the roadmap for the @next version

**Comment by Nixes** [comment]
I think it make sense to have postfixes in codegen, but probably the code that generates the the postfixed name needs to be updated to not check if it is already added, so that at least ''ActiveServiceService' is generated instead of the conflicting name

**Comment by ferdikoomen** [comment]
@Nixes there is a 0.12.0-alpha published now that has the option to set a custom postfix (using `--postfix` defaults to `"Service"`). The 0.12.0 version will be published soon when testing is done, but this should fix your issue
