### ISSUE TITLE
What's the difference between --exportSchemas and just using the spec object?

### ISSUE THREAD

**Issue by mvasin** [ferdikoomen/openapi-typescript-codegen#450]
Hi @ferdikoomen!

Quick question: is there a difference between the `--exportSchemas` output and grabbing that data from the spec object directly? If not, can we add to the readme the phrase "...alternatively, you can extract that data from the spec object directly". And, by the way, would using directly mean converting it with the `yaml` library and exporting the result as an object, or will the generator provide it?

**Comment by ferdikoomen** [comment]
@mvasin Yes, you can definitely do that, but the spec also contains all the service layer definitions. The idea behind the schemas is to have a 'standard' way to iterate over the model properties that are very close to what is generated. But indeed, you can include the whole spec and do the same.

**Comment by mvasin** [comment]
I'm missing some context - what is the service layer, and what are service layer definitions?

**Comment by ferdikoomen** [comment]
@mvasin sorry i was in a backend mindset. The spec file contains more then just model definitions, it also contains the API routes, etc. (sometimes called API end-points or Services). Off course you can just grab a specific part of your spec file and use that. However the problem with this is:
- The spec is specific to a OpenAPI version (V2 and V3 are quite different in some area's), but the generated schema is version agnostic.
- The spec might reference external files, the generator bundles these and creates one model/schema for you with everything resolved.
- The spec might contain property types that need some mapping (int -> number), the types in the generated schema should be pretty standard for Javascript environments.
