### ISSUE TITLE
OpenAPI.WITH_CREDENTIALS is no longer respected when http client is fetch or node-fetch

### ISSUE THREAD

**Issue by EqualMa** [ferdikoomen/openapi-typescript-codegen#475]
**Describe the bug**

In #256 , requesting with `fetch` respects `OpenAPI.WITH_CREDENTIALS`:

https://github.com/ferdikoomen/openapi-typescript-codegen/blob/c9b232e5afa4775effd696e84725f001d0cd9cc2/src/templates/core/request.ts#L37-L42

But this is no longer available in current version. The above code can no longer be found in current version of [`fetch/sendRequest`](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/ea29f25b19b9b63cb1a29116e68793296dc9e9fa/src/templates/core/fetch/sendRequest.hbs)

**Comment by ferdikoomen** [comment]
Hey @EqualMa good point! Will push a new build soon

**Comment by ferdikoomen** [comment]
@EqualMa  0.7.1 should fix this, its available now
