### ISSUE TITLE
Generating types with fixed enum values

### ISSUE THREAD

**Issue by markygab** [ferdikoomen/openapi-typescript-codegen#478]
I have a few types which reference the same enum. Some of the types are restricted to have only a single value from the enum, but i'm not sure how to define this.. Currently, it is generating invalid TypeScript from valid yaml.

I think the TypeScript output I expect is:

```
export enum SurfaceType {
    SURVEY = 'SURVEY',
    DESIGN = 'DESIGN',
}
export type Surface = {
    id: string,
    type: SurfaceType
}
export SurveySurface = Surface & {
    type: SurfaceType.SURVEY
}
```

And the Yaml I have is:
```
SurfaceType:
  type: string
  enum:
    - SURVEY
    - DESIGN

Surface:
  type: object
  properties:
    id:
      type: string
    type:
      $ref: '#/components/schemas/SurfaceType'

SurveySurface:
  type: object
  allOf:
    - $ref: '#/components/schemas/DataSetSurface'
    - type: object
      properties:
        type:
          allOf:
            - $ref: '#/components/schemas/SurfaceType'
            - type: string
              enum:
                - SURVEY
```

but this is generating

```
export type SurveySurface = (Surface & {
    type: (SurfaceType & SurveySurface.),
});
```

**Comment by ferdikoomen** [comment]
@markygab actually the response should be slightly different. The SurveySurface **type** prop can be "allOf" the following types: **SurfaceType** or **string** (or actually the string value is SURVEY). So the generated code should be:

Option 1:
```
export SurveySurface = Surface & {
    type: SurfaceType & string // This is a bit weird, since its an enum value "SURVEY"
}
```

Option 2:
```
export SurveySurface = Surface & {
    type: SurfaceType & 'SURVEY' // This is also a bit weird, since 'SURVEY' is a value of SurfaceType
}
```

Option 3:
```
export SurveySurface = Surface & {
    type:  'SURVEY' // This is correct since 'SURVEY' is the only valid value here
}
```
I'm investigating now why this generates incorrectly.

**Comment by ferdikoomen** [comment]
The issue is: When simply checking the spec we end up with something like this:
```
export SurveySurface = Surface & {
    type: SurfaceType & 'SURVEY'
}
```
Yes, 'SURVEY' is a value of SurfaceType, but hat is not clear from the spec. I need to follow up on this, but at the moment the easiest solution is to remove this last bit from the spec (if you have access to that):
```
- type: string
  enum:
  - SURVEY
```

**Comment by ferdikoomen** [comment]
No response
