### ISSUE TITLE
Service method JSDoc uses non-standard @result tag instead of standard @returns/@return

### ISSUE THREAD

**Issue by iansan5653** [ferdikoomen/openapi-typescript-codegen#490]
**Describe the bug**
This is a pretty minor thing, but the standard JSDoc tag for describing return values is `@return` (or `@returns`). The generated code uses `@result`, which I assume is intended to describe the resolved value of the returned promise, but this is not a standard tag and isn't handled by any editors.

**Comment by ferdikoomen** [comment]
@iansan5653 done, will create new build soon!

**Comment by ferdikoomen** [comment]
@iansan5653 0.7.1 should fix this, its available now
