### ISSUE TITLE
Incorrect interfaces are produced when a property has a space in the name

### ISSUE THREAD

**Issue by iansan5653** [ferdikoomen/openapi-typescript-codegen#493]
If a property of a schema has a space in the name (ie, `"Example Property"`, the output will have the property name `Example$u0020Property`, replacing all spaces with `$u0020`. Instead, the property name should just be wrapped in quotes. This is a valid interface in TypeScript:

```ts
interface Example {
  "Example Property": string;
}
```

For simplicity, maybe all property names should be quoted and not escaped at all (except to add a backslash before any double quotes already in the name).

**Comment by ferdikoomen** [comment]
@iansan5653 what spec are you using, is i define a propery like:
```
"property with space": {
   "type": "string"
},
```
then the result is:
```
'property with space'?: string;
```
in the generated model

**Comment by iansan5653** [comment]
Sorry, after some more examination this is actually a problem with the schema we're using, not with this library.
