### ISSUE TITLE
Letter case is changed to lowercase in angular but correct in node project

### ISSUE THREAD

**Issue by rattkin** [ferdikoomen/openapi-typescript-codegen#509]
This openapi spec, single file shared between both projects:
```
components:
    schemas:
        Address:
            required:
                - AddressTypeID
            properties:
                AddressTypeID:
                    $ref: "#/components/schemas/AddressTypeID"
        AddressTypeID:
            type: string
            enum: [BA, EX]
            example: BA
            description: BA - Billing Address, EX - Expedition
```

I'm using this command, the same in both projects:
```
openapi --input ../api/openapi.yaml --output ./src/shared/api-model --exportServices false --exportCore false
```

In node project, the letter case is I think correct:
```
import type { AddressTypeID } from './AddressTypeID';
export type Address = {
    AddressTypeID: AddressTypeID;
```
And the AddressTypeId.ts:
```
export enum AddressTypeID {
    BA = 'BA',
    EX = 'EX',
}
```

However, in Angular project there are some letters changed for some strange reason to lower-case:
```
import { AddressTypeId } from './address-type-id';
export interface Address {
  AddressTypeID: AddressTypeId;
}
```
And the address-type-id.ts:
```
export enum AddressTypeId {
  Ba = 'BA',
  Ex = 'EX'
}
```

Because 'BA' !== 'Ba', I can not copy for example mock objects from one project to another without cumbersome replacements.
What can I do to prevent it?

I know the letter case in our openapi spec is not 'proper' and while I might care, my boss sure doesn't and will not allow any change in openapi spec.

**Comment by ferdikoomen** [comment]
@rattkin Not sure why that is happening... the import you are seeing:
```
import { AddressTypeId } from './address-type-id';
```
Are generated using a line like this in the Handlebars templates:
```
import type { {{{this}}} } from './{{{this}}}';
```
So the model name and file name should be exactly the same...

Could you check the version of handlebars in your project? Or can you isolate the issue and send an example setup to me?

**Comment by rattkin** [comment]
Thank You for caring.
I verified that handlebars versions match and that issue still persists for me.
Since I already have a workaround, I have moved on to other work.
