### ISSUE TITLE
Incorrectly resolved typescript type

### ISSUE THREAD

**Issue by huttarichard** [ferdikoomen/openapi-typescript-codegen#510]
based on swagger config:

```yaml
/v1/languages:
    get:
      operationId: get-languages
      produces:
      - application/json
      responses:
        "200":
          description: some result
          # headers:
          #   Location:
          #     description: /v1/languages
          #     type: string
          schema:
            $ref: '#/definitions/LanguagesOutputV1'
      summary: Returns languages  their ietf tags and whether they are active or not
      tags:
      - Languages
```

as long as headers are commented out you get this signature

```
public static async getLanguages(): Promise<LanguagesOutputV1> 
```

however once you uncomment the headers signature will become

```
public static async getLanguages(): Promise<string>
```

I don't think this is expected behaviour. Or am I missing somthing?

**Comment by ferdikoomen** [comment]
@huttarichard When we define the header as the response type, the OpenAPI generator will assume you want to get back the header value (that is a string), rather than the model that is used in the schema. This is because we generate a service call that 'resolves' only one type.
So the question would be: What should happen in this case? What would be the expected return type? 
Maybe it makes sense to prioritise the schema instead of the header?

**Comment by huttarichard** [comment]
@ferdikoomen I opened this issues long time ago, and later down the road started building my own generator. Few things I found are not filling up my expectations. This was actually one of them.

I will write them up, maybe as a sugestion what can be imho improved:

I do prefer to have full response, If serverside provides response headers together with payload I don't see reason to prefer & return only part of the response. You can actually return both. 

Handlebars were driving me crazy, it works, but I think we could improve and get the abstraction over the AST to allow more swift and safe code gen. And to allow safe modification.

Third thing which bothered me was the need for present operationId and tags, together with modularity. I think you can make each request being just a simple function in its own file named and generated by path. Having a pure function which takes and returns type together with commonjs will allow tree shaking, no collisions, simple access via imports.

Finally I would rather prefer to single library like axios which works on both sides, because that way you can actaully used one client for both nodejs and browser. 

Those are just suggestions. I actually forked the library, and eventually started from scratch. But thanks for wonderful work.
