### ISSUE TITLE
Enum with bool is is broken (v3)

### ISSUE THREAD

**Issue by tamasfe** [ferdikoomen/openapi-typescript-codegen#511]
The following schema breaks the generator, but is accepted by the swagger editor:

```json
{
  "type": "boolean",
  "enum": [true]
}
```
It's quite a niche use-case, but should work regardless.

**Comment by ferdikoomen** [comment]
Hi @tamasfe

Assuming we have the following input:
```
"bool": {
    "type": "boolean",
    "enum": [
        true
    ]
},
```
The typescript equivalent of an enum for this:
```
export enum bool {
   TRUE = true,
}
```
Will not compile (true is not a valid value), so i will convert this case to:
```
bool?: boolean;
```
I will include a fix for this in the next release (will be pushed this evening): version 0.8.0
