### ISSUE TITLE
Responses that return files don't work

### ISSUE THREAD

**Issue by iansan5653** [ferdikoomen/openapi-typescript-codegen#517]
It's possible for an API to return a file in response to a request. The OpenAPI [documentation](https://swagger.io/docs/specification/describing-responses/#response-that-returns-a-file) says to describe this as a response with the schema:
```json
{
  "type": "string",
  "format": "binary"
}
```

Currently the service (at least in `fetch` form) only either calls `json()` or `text()` on the fetch response. I think that when it sees a response with `format: binary`, it should instead call `blob()` and the response type of the method should be `Blob`.

**Comment by ferdikoomen** [comment]
@iansan5653 currently no. I have only written support for uploading binaries. Feel free to create a PR. If time permits i'll add it down the road.
