### ISSUE TITLE
Method name

### ISSUE THREAD

**Issue by ksydex** [ferdikoomen/openapi-typescript-codegen#525]
How is it generated? Can i specify these by myself to make them more clear?
P.S. I talk about `postAuthService`, `postAuthService1` etc.
![image](https://user-images.githubusercontent.com/38377534/104767262-e6857800-577c-11eb-9840-e7f0d2d620c6.png)

**Comment by ferdikoomen** [comment]
@ksydex The service method names are auto generated from the `operationId`. If there are multiple services with the same operation id, then it's postfixed with a number. So the easy answer is: Update the spec file (or request it to be updated)

**Comment by donkey-donkey** [comment]
so we cannot have a get ```/apples/:id``` and a get all for ```/apples/``` because the second one listed will turn into apples1
isnt the openapi spec to have the endpoints both named apples? but then we get silly apples1 function name? am i missing something?
