### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by stefanpl** [ferdikoomen/openapi-typescript-codegen#539]
Hello 👋

```
node 14.15.3
```

Please consider this shell script:
```sh
cd /tmp
mkdir output
wget "https://docs.docker.com/engine/api/v1.41.yaml"
npx openapi-typescript-codegen --input ./v1.41.yaml --output ./output
```

It fails with
```
TypeError: e.replace is not a function
    at /home/[…]/.npm/_npx/10359/lib/node_modules/openapi-typescript-codegen/dist/index.js:1:968
```

I do understand that the docker yaml file contains quite a lot of errors (there are various tickets trying to remedy that). But I still think `openapi-typescript-codegen` could be a bit more robust here – it does not generate any output at all, and the error is very obscure.

In case somebody wants to tackle this, I'd be more than happy! If not, might this be a good *first issue*? I'm not very familiar with the intricacies of the OpenApi spec, but know my way around TypeScript.

Either way, thanks a lot in advance for a quick feedback on this!

**Comment by ferdikoomen** [comment]
@stefanpl yes one of the idea's on the roadmap is to provide a 'validation step' based on the OpenAPI schema. This would give you back a slightly better error than some 'random' code parser one. If you want to do that already then use something like this: https://github.com/APIDevTools/swagger-parser
