### ISSUE TITLE
Missing config in OpenAPI.ts

### ISSUE THREAD

**Issue by sussdorff** [ferdikoomen/openapi-typescript-codegen#545]
Within the last two weeks (approx.) something changed which results in OpenAPI.ts missing some config which is still required by request.ts (like USERNAME; PASSWORD; HEADERS)

Below is the diff of the previous generated version and the version generated now of OpenAPI.ts

We can easily fix this by adding the config back to OpenAPI.ts, but I wanted to make sure there isn't something important "missing".

 /* istanbul ignore file */
 /* tslint:disable */
 /* eslint-disable */
-type Resolver<T> = () => Promise<T>;
-type Headers = Record<string, string>;

-type Config = {
+interface Config {
     BASE: string;
     VERSION: string;
+    CLIENT: 'fetch' | 'xhr';
     WITH_CREDENTIALS: boolean;
-    TOKEN?: string | Resolver<string>;
-    USERNAME?: string | Resolver<string>;
-    PASSWORD?: string | Resolver<string>;
-    HEADERS?: Headers | Resolver<Headers>;
+    TOKEN: string;
 }

+import { config } from "../../config";
+
 export const OpenAPI: Config = {
+    CLIENT: 'fetch',
     WITH_CREDENTIALS: false,
-    TOKEN: undefined,
-    USERNAME: undefined,
-    PASSWORD: undefined,
-    HEADERS: undefined,
+    TOKEN: '',
 };

**Comment by ferdikoomen** [comment]
@sussdorff The config is still there: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/templates/core/OpenAPI.hbs
And request.ts imports the OpenAPI file:
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/templates/core/fetch/request.hbs
Also the tests (and real life examples) are running fine. 
Can you clarify your issue?

**Comment by sussdorff** [comment]
@ferdikoomen this is what I saw which confused me as it is explicitely excluded (the lines from the OpenAPI.hbs) when generating the OpenAPI.ts in our environment. As I'm not sure what is involved in turning the .hbs into a .ts file I can't really say. Note that we are using the npm install with     "openapi-typescript-codegen": "^0.7.2" which does seem to have the correct data in index.js. => I am somewhat clueless how / why it might not put USERNAME,PASSWORD,HEADERS into the OpenAPI.ts

I just realized that in pasting the code it turned the + and - into *. therefore attaching the git diff.

[OpenAPI.ts.diff.txt](https://github.com/ferdikoomen/openapi-typescript-codegen/files/5879686/OpenAPI.ts.diff.txt)

**Comment by ferdikoomen** [comment]
@sussdorff could you check the version of handlebars in the node_modules directory?
And maybe give me you specs: Node version, OS version

**Comment by sussdorff** [comment]
handlebars ist 4.7.6
node 14.14.22
MacOS 10.15.7 (catalina - Intel CPU)

**Comment by ferdikoomen** [comment]
Ok so, the newly generated OpenAPI file should look something like:
```
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
type Resolver<T> = () => Promise<T>;
type Headers = Record<string, string>;

type Config = {
    BASE: string;
    VERSION: string;
    WITH_CREDENTIALS: boolean;
    TOKEN?: string | Resolver<string>;
    USERNAME?: string | Resolver<string>;
    PASSWORD?: string | Resolver<string>;
    HEADERS?: Headers | Resolver<Headers>;
}

export const OpenAPI: Config = {
    BASE: 'http://localhost:3000',
    VERSION: '1.0',
    WITH_CREDENTIALS: false,
    TOKEN: undefined,
    USERNAME: undefined,
    PASSWORD: undefined,
    HEADERS: undefined,
};
```
In the diff i see an older version, where there is still a property like this
```
CLIENT: 'fetch' | 'xhr';
```
Do you see a runtime/compile issue as well? because the new OpenAPI generator should generate compatible files (the request.ts file should only use properties that are defined in the OpenAPI.ts).

**Comment by sussdorff** [comment]
Thanks. The version you described is the *old* version we have. 

Having seen that I double checked my environment. Long story short... there was an old version of the openapi-typescript-codegen outside my main NPM respository which was linked from /usr/local/bin/.... resulting in finding a 0.4 version. Now I changed the call to run using `npx openapi-typescript-codegen`. 

Thanks for guiding me through this and the patience and quick response.
