### ISSUE TITLE
0.8 Regression: Unexpected token in JSON

### ISSUE THREAD

**Issue by robinmetral** [ferdikoomen/openapi-typescript-codegen#546]
Hi,

First of all, thank you for the great tool!

I think there might be a regression in 0.8.0 (from two days ago). I've reproduced the behavior below on the latest Node 12 and 14, I'm on Ubuntu.

The issue is at step 5. below, but the error message is not very useful so I'm adding steps for reproduction:

1. `npm init` to start with a clean project`
2. `npm install -S openapi-typescript-codegen@0.8.0`
3. add this script to package.json (attempts to generate a client for the swagger petstore API):
    ```json
    "generate": "openapi --input https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml --output ./dist"
    ```
4. `npm run generate`
5. :bug: : `SyntaxError: Unexpected token u in JSON at position 0`
6. sanity check: downgrade to 0.7.2 `npm install -S openapi-typescript-codegen@0.7.2`
7. `npm run generate`
8. :tada: the client is generated fine

Happy to provide more details if it helps. Let me know!

**Comment by HMilbradt** [comment]
Now seeing this as well when running the following command:

`npx openapi-typescript-codegen --input ./schema.json --output ./src/lib --client node --useOptions`

On version 0.8.0:

```
npx openapi-typescript-codegen --version

npx: installed 24 in 1.985s
0.8.0
```

Thanks for providing the workaround @robinmetral

**Comment by ferdikoomen** [comment]
Yep see the issue, the upgrade of commander package has broken the generator, fix will be pushed in an hour

**Comment by ferdikoomen** [comment]
Just pushed version 0.8.1.
