### ISSUE TITLE
Generated type for openapi response with a default value is marked as possibly undefined

### ISSUE THREAD

**Issue by mr-bjerre** [ferdikoomen/openapi-typescript-codegen#551]
In my front-end I'm consuming a backend endpoint `/test`. The `post` needs a body of type `Model` where the `a` property is optional with a default value. The response from this endpoint is a `Model` where I know that `a` will contain an integer since a default value is given. 

I.e. here is the openapi.json spec

```json
{
  openapi: "3.0.2",
  info: {
    title: "FastAPI",
    version: "0.1.0",
  },
  paths: {
    "/test": {
      get: {
        summary: "Foo",
        operationId: "foo_test_get",
        requestBody: {
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/Model",
              },
            },
          },
          required: true,
        },
        responses: {
          "200": {
            description: "Successful Response",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/Model",
                },
              },
            },
          },
        },
      },
    },
  },
  components: {
    schemas: {
      Model: {
        title: "Model",
        required: ["b"],
        type: "object",
        properties: {
          a: {
            title: "A",
            type: "integer",
            default: 5,
          },
          b: {
            title: "B",
            type: "integer",
          },
        },
      },
    },
  },
}
```

Running the following command

    npx openapi-typescript-codegen --input http://localhost:8000/openapi.json -o dist

produces the following type alias 

```typescript
export type Model = {
    'a'?: number;
    'b': number;
}
```

and service

```typescript
import type { Model } from "../models/Model";
import { request as __request } from "../core/request";

export class Service {
  /**
   * Foo
   * @param requestBody
   * @returns Model Successful Response
   * @throws ApiError
   */
  public static async fooTestPost(requestBody: Model): Promise<Model> {
    const result = await __request({
      method: "POST",
      path: `/test`,
      body: requestBody,
    });
    return result.body;
  }
}
```

It looks pretty good but since a default value is given for `a` then I know the response from `/test` is actually going to be `Promise<Required<Model>>`:

```typescript
{
    'a': number;
    'b': number;
}
```

I hope it make sense and I realise that maybe I need to fix it in openapi.json. I'm going back and forth on this matter and can't decide. Whats you take on it?

**Comment by andreujuanc** [comment]
Hi @mr-bjerre 
I've got the same issue. Have you got any workarounds?

**Comment by mr-bjerre** [comment]
No I haven't unfortunately

**Comment by andreujuanc** [comment]
Looks like the spec i'm using is not adding the required fields, which are not set in the props themselves but in an array like so:
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.json#L136
Ill try to get the proper json

**Comment by ferdikoomen** [comment]
@mr-bjerre i see the issue indeed. I created this PR: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/592 Will test the changes. Officially the required props need to be in the array, but the JAVA generator also marks properties with default values as non-optional, so will do some regression testing and then we could merge this.

**Comment by ferdikoomen** [comment]
@mr-bjerre just pushed a new version 0.9.1

**Comment by blipk** [comment]
This issue is still happening in 0.23.0 @ferdikoomen 

non-Optional fields with a default value should NOT be marked as optional in the generated typescript, yet they are.

**Comment by Oreilles** [comment]
Should this be reopened ? The exemple given by OP is still returning the same unexpected result.
