### ISSUE TITLE
Setting base path dynamically for production builds.

### ISSUE THREAD

**Issue by staklau** [ferdikoomen/openapi-typescript-codegen#552]
You usually develop against your server running at some local address, and use some other base path in production, e.g:
`http://locahost:8080` locally and `https://myprodserver` in production.

I would like the possibility to change the base path dynamically for creating my production builds.

If I understand correctly this comes directly from the OpenApi-spec-file, as of now, but I would like this to be independent of the OpenApi-spec, maybe as an input param to the cli-tool, or as an override through an environment-variable.

If there already is a way of doing this, without the need to change my OpenApi-spec generated at the backend, I would love to know.

**Comment by ferdikoomen** [comment]
Hi @staklau you can always change the base path bt setting this in OpenAPI.BASE = 'http://mydomain.com/api'. You can do that based on the environment config or inject it via webpack, whatever works.

**Comment by ferdikoomen** [comment]
Closing this since there is no reponse

**Comment by knobel-dk** [comment]
Hi @ferdikoomen,

Thanks for this great repo. This is the best TypeScript codegen of the ones I've tried.

This thread turned stale but I would be glad to see a full example. Any chance you could show that in a fictive `index.ts` file before the service is called?

**Comment by ferdikoomen** [comment]
@knobel-dk I have use something like this in the past: 

`setupOpenAPI.ts` (imported as one of the first files)

```
import { OpenAPI } from './myGeneratedClient';

if (process.env.DEBUG) {
   OpenAPI.BASE = 'http://localhost:8080/';
}
```
Then during a production build the 'regular' base is used that was there in the OpenAPI spec. 

This works with the Webpack environment plugin: https://webpack.js.org/plugins/environment-plugin/ you need to setup this for your repo. Similar plugins exists for Rollup and others.

**Comment by knobel-dk** [comment]
> @knobel-dk I have use something like this in the past:
> 
> `setupOpenAPI.ts` (imported as one of the first files)
> 
> ```
> import { OpenAPI } from './myGeneratedClient';
> 
> if (process.env.DEBUG) {
>    OpenAPI.BASE = 'http://localhost:8080/';
> }
> ```
> 
> Then during a production build the 'regular' base is used that was there in the OpenAPI spec.
> 
> This works with the Webpack environment plugin: https://webpack.js.org/plugins/environment-plugin/ you need to setup this for your repo. Similar plugins exists for Rollup and others.

Thanks, man!

**Comment by jamesarosen** [comment]
One downside to changing this after the fact is that the generated code still exposes the URL it was compiled with. For example, if one were to use this library with the [BFF pattern](https://samnewman.io/patterns/architectural/bff/) in [Next](https://nextjs.org/) or [Remix](https://remix.run/), using the Next/Remix server as a proxy for the upstream OpenAPI server, the browser code would have

```ts
// core/OpenAPI.ts

export const OpenAPI: OpenAPIConfig = {
  BASE: 'http://private-api-server.example.com',
}

// application-code.ts
OpenAPI.BASE = '/api/proxy';
```

**Comment by webtaken** [comment]
@jamesarosen In which file of Next JS 14 should be done this change?
I am doing on my `app/layout.tsx` this thing:

```
console.log(OpenAPI.BASE);
OpenAPI.BASE = process.env.BASE_PATH_API!;
```
But I am not calling tot he specified `BASE_PATH_API` env var.

**Comment by jamesarosen** [comment]
> In which file of Next JS 14 should be done this change?

I'm using Next 13, but I have it in `pages/_app.tsx`, right after the `import` statements.

**Comment by baughmann** [comment]
If you're using React (not SSR) you can also just do this somewhere (maybe your `index.tsx` or `main.tsx`:
```ts
import { OpenAPI } from "@infyrence/lib";
OpenAPI.BASE = window.location.origin;
```
