### ISSUE TITLE
Decouple TS types generation from  openapi-typescript-codegen

### ISSUE THREAD

**Issue by giowe** [ferdikoomen/openapi-typescript-codegen#553]
Hi @ferdikoomen , first of all thanks for your great job, we are using it in various projects.
In our experience we noticed that would be very useful to leverage the TS types generation not only for a client SDK but also for the server development. 
Are you interested in decoupling the TS types code generation from the SDK client generation?
If so let me know if I can help

**Comment by ferdikoomen** [comment]
@giowe I'm working on some rewrites (which are in a very draft state now). If it's slightly further along i would like some input on that. The next version will / should contain better decoupling between different steps (parsing, validation, generation, etc). For now you could execute the following command to 'just' get the models:

```
npx openapi-typescript-codegen --input ./spec.json --output ./dist --exportCore false --exportServices false
```
This should only generate the 'plain' models without any service layer.

Hope that helps.

Cheers

**Comment by giowe** [comment]
@ferdikoomen thanks! is it possible to achieve the same result passing somehow those parameters programmatically instead of using the cli ?

**Comment by ferdikoomen** [comment]
Sure, do you mean something like this? 

```
import * as OpenAPI from 'openapi-typescript-codegen';

OpenAPI.generate({
    input: './spec.json',
    output: './dist',
    exportCore: false,
    exportServices: false,
});
```

Cheers,

Ferdi

**Comment by giowe** [comment]
tnx!!!
