### ISSUE TITLE
Auth/Micro Service Use Case

### ISSUE THREAD

**Issue by laktak** [ferdikoomen/openapi-typescript-codegen#588]
I have a service where I need to pass the JWT (and other headers) of the request along to each API call I make.

I looked at the existing issues but it appears that I can only set the auth headers globally and not for each request? Is there a workaround?

**Comment by kwkelly** [comment]
@laktak, it's not ideal, but with some small-ish modifications you can generate code that utilizes an instance instead of static classes for the service methods. See the fork here for an example: https://github.com/kwkelly/openapi-typescript-codegen .
You can instantiate a client as needed per request to keep the auth separate. See in particular the `v3.node.spec.js` for how it works.

@ferdikoomen would you accept a PR that adds the option of using instance based services instead of the static class method based ones?

**Comment by laktak** [comment]
I only looked at your changes but it looks very promising! Thank you!

I would change the naming from all caps though to conform with the standard naming conventions ... the project currently uses them in that form but it's different for global settings IMO.

**Comment by kwkelly** [comment]
Thanks laktak... I updated the instance config to use lowercase.

**Comment by ferdikoomen** [comment]
@laktak @kwkelly You can do two thing currently:
In the place where you set the global headers:
```
OpenAPI.HEADERS = {
  'BEARER': 'my-super-secure-bearer-token'
}
```
You can actually pass a async method. This will be called on each request to get the headers you might want to apply:
```
OpenAPI.HEADERS = async () => {
   const token = await getMyToken();
   return {
      'BEARER': token
   }
}
```
Hope that might also help you, its not perfect, but it might just work in your case.

**Comment by andreujuanc** [comment]
@ferdikoomen  do we have access to the current request? I'm interested in forwarding the current headers.

**Comment by laktak** [comment]
@kwkelly I wanted to test your implementation but the repo is now 404?

@ferdikoomen I've seen that but the function is missing the context - how would I get the current request in your `getMyToken` example?

**Comment by ferdikoomen** [comment]
@laktak we could add this, seems like a usable thing... Let me check

**Comment by kwkelly** [comment]
@laktak check again. Sorry.

**Comment by laktak** [comment]
@ferdikoomen I think the implementation by @kwkelly solves this in a good way.

He changed the `Service` from static to a normal class where you can pass headers to the constructor:

```
export class Service extends ApiRequest {

    constructor(config: InstanceConfig = {}) {
        super(config);
        ...
```

**Comment by andreujuanc** [comment]
I would love to have one instance per request instead of a singleton. 
It would open the door on handling multiple backends if forwarding from different autentication contexts.

**Comment by laktak** [comment]
@ferdikoomen just wanted to ask if you have any updates on this. Can we help?

**Comment by ferdikoomen** [comment]
@laktak When you use the latest OpenAPI generator the GLOBAL config looks like this:

```
type Config = {
    BASE: string;
    VERSION: string;
    WITH_CREDENTIALS: boolean;
    TOKEN?: string | Resolver<string>;
    USERNAME?: string | Resolver<string>;
    PASSWORD?: string | Resolver<string>;
    HEADERS?: Headers | Resolver<Headers>;
}
```
So the `OpenAPI.HEADERS` or `OpenAPI.TOKEN` property can be used to either set a headers once, or you can pass a function that 'resolves' the headers for each request. This could look something like:

```
OpenAPI.HEADERS = async (options: ApiRequestOptions) => {
   // The options object contains the request properties
   // You can do whatever you want here, even call another backend...
   // Just return the correct object when done
   return {
      'my-header': 'some-value'
   }
}
```
There is no progress on the "one instance per request instead of a singleton".

**Comment by laktak** [comment]
Thank you. 

I have incoming calls from other services with a JWT in the header. How can I pass the JWT along to the async method?

I looked at the `ApiRequestOptions` but there is not context or "session" to pass along so I can't get to the JWTs that I have. Am I missing something?

**Comment by ferdikoomen** [comment]
@laktak I don't know how you receive the JWT header, but in some of the projects that i'm involved in, we do something like this:

We have an authentication library (OpenID in our case), that library receives new JWT tokens when the old ones expire:
```
import { UserManager } from 'oidc-client';

const userManager = new UserManager({ ..settings });

// This userManager from OpenID gives a new access_token automatically.
// We store this in the global OpenAPI configuration, so that each call after that uses
// the JWT token to make requests.
userManager.getUser().then(user => {
    OpenAPI.TOKEN = user.access_token;
})
```
This setup would set the token (or override it when a new token comes in). And all the calls would just use this token in their requests: Setting the OpenAPI.TOKEN will use that token as the bearer token for each request.

If you can explain to me how you receive your JWT tokens, then maybe I can help you a bit better.

**Comment by ferdikoomen** [comment]
Maybe a better question would be: how would you write it with another library? Like directly with fetch, axios, etc.?

**Comment by laktak** [comment]
OK, I'll try to explain it a bit better. 

For example we have an orchestration service with a `/message` API. 

User A calls orchestration:/message JWT-A, the service then
- calls store:/message (JWT-of-A) to save the message in the outbox of user A (JWT-of-A grants access to this outbox)
- calls notify:/send (JWT-of-A) to send a notification (JWT-of-A grants access and identifies A as the sender)

User B calls orchestration:/message JWT-B, the service then
- calls store:/message (JWT-of-B) to save the message in the outbox of user A (JWT-of-B grants access to this outbox)
- calls notify:/send (JWT-of-B) to send a notification (JWT-of-B grants access and identifies B as the sender)

etc. 

So you see, the JWT contains the id and roles of each user. Each request needs to hand the JWT of the user to the next service. There is no global JWT because each user needs a different id/has different roles.

**Comment by ferdikoomen** [comment]
@laktak Cool! Thanks for clarifying. Let me check if this use case can be done, but indeed this might be an issue. I dont want to loose the Static services, they are handy in most common application scenarios. But maybe we can create both: static methods and class instance creation, using those methods, but having some scoped configuration... interesting issue.

**Comment by laktak** [comment]
That would be great, thank you!

**Comment by rbayliss** [comment]
This is kind of important for us as well.  Our use case is that we have a class (`Submitter`), and multiple "environments" the submitter might point to.  Within the scope of a single script, we create and use a new `Submitter` for each environment:
```
const submitted = { 
  // ...
};
const submitters = [
  new Submitter("dev"),
  new Submitter("stage")
];
await Promise.all(submitters.map((submitter) => submitter.submit(obj));
```
Ideally, each `Submitter` could be instantiated with a client instance with the base URL and credentials configured. Lacking this, we'd have to do a lot of reconfiguration of singletons as the calls are made.

**Comment by ferdikoomen** [comment]
@laktak @andreujuanc @rbayliss There is a new version that allows to create client instances to each client can have its own bearer token. You can specify the `--name` argument while generating the client. More info:
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/588
