### ISSUE TITLE
Validate wrong specs

### ISSUE THREAD

**Issue by andreujuanc** [ferdikoomen/openapi-typescript-codegen#597]
Hi, 

I've got an spec which basically says that it's a GET but also contains a body. 
This library generates the request and sends a body along the way. 

Is it possible to make it so when generating the client if the verb is a GET and the spec contains a body then we at least show a warning? 

Thanks <3

**Comment by ferdikoomen** [comment]
The generator tries to do a best effort indeed, the validity of the spec if down to the implementor. I'm thinking a mayor next version could do some validation before executing the generation step. For now the best approach is to run a validation with another library first. You can checkout any of the tools here: https://openapi.tools/#data-validators

**Comment by andreujuanc** [comment]
Fair.! Thanks.
