### ISSUE TITLE
Generating invalid typescript

### ISSUE THREAD

**Issue by mikearnaldi** [ferdikoomen/openapi-typescript-codegen#605]
When an API input has the field `default` we will generate a client that uses `default` as a parameter, unfortunately, `default` is a reserved word.

Reproduction: `openapi -i https://raw.githubusercontent.com/CurrencyCloud/currencycloud-swagger/master/src/reference.yaml -o src` leads to code that doesn't compile

**Comment by ferdikoomen** [comment]
Hi @mikearnaldi good point, will add the reserved words check, tested a few use cases and seems this is the list:

```
arguments
break
case
catch
class
const
continue
debugger
default
delete
do
else
enum
eval
export
extends
false
finally
for
function
if
implements
import
in
instanceof
interface
let
new
null
package
private
protected
public
return
static
super
switch
this
throw
true
try
typeof
var
void
while
with
yield
```

**Comment by ferdikoomen** [comment]
@mikearnaldi just pushed version 0.9.2. Could you check if that solved your issue?

**Comment by mikearnaldi** [comment]
@ferdikoomen It does! thanks very much for the rapid fix, I'll close the issue
