### ISSUE TITLE
Return type is Promise<any> instead of Promise<void> for endpoints with bodyless responses

### ISSUE THREAD

**Issue by ljwagerfield** [ferdikoomen/openapi-typescript-codegen#607]
Given the following OpenAPI Spec:

```json
"/v1/accounts/current": {
  "put": {
    "operationId": "Initialize",
    "responses": {
      "204": { "description": "Success." }
    },
    "tags": ["accounts"],
    "security": [{ "bearer-token": [] }],
    "parameters": [],
    "requestBody": {
      "required": true,
      "content": { "application/json": { "schema": { "$ref": "#/components/schemas/InitializeAccountRequest" } } }
    }
  }
}
```

The `openapi` CLI tool outputs:

```typescript
public static async initialize(requestBody: InitializeAccountRequest): Promise<any>
```

How can I change the return type to `Promise<void>`?

(Great tool btw!)

**Comment by ferdikoomen** [comment]
@ljwagerfield this seems related to the specified "204" return code, if there is no "responses" field then it should be void. But you have a good point: The 204 response should be "No content", so in this case we would expect a void indeed. I will have a quick look

**Comment by ferdikoomen** [comment]
@ljwagerfield I pushed a fix to the main branch, will publish a new version next week (working on a few more minor fixes). If a response has the 204 code then we can assume No Content e.g. void :-)

**Comment by ferdikoomen** [comment]
@ljwagerfield sorry for the delay, had some illness in between. There is a new version (0.9.3) that should contain the fix for the issue.

**Comment by ljwagerfield** [comment]
That's fantastic, thank you!

**Comment by mrlubos** [comment]
Hi @ljwagerfield, I had a problem where an endpoint returning both 200 and 204 would get typed as `MyResponseType` which is obviously not the case for 204. I opened a pull request changing it to `MyResponseType | void` in #1656. Could you have a look and see if this still works as you'd expect with your use case? Thanks!
