### ISSUE TITLE
Enums with floats generate invalid member names

### ISSUE THREAD

**Issue by CheesyFeet** [ferdikoomen/openapi-typescript-codegen#621]
An enum with floating point values generates invalid typescript. An example of generated code is:

```
export enum ExampleEnum {
    _0.981 = 0.981,
    _1 = 1,
    _1.011 = 1.011,
    _1.026 = 1.026,
}
```

This throws typescript errors due to the use of the decimal point in the name. Perhaps the decimal could be replaced with an underscore during generation if the value is a float?

Thanks

**Comment by ferdikoomen** [comment]
@CheesyFeet In the latest version the enums are generated as strings:
```
export enum ExampleEnum {
    '0.981' = 0.981,
    '1' = 1,
    '1.011' = 1.011,
    '1.026' = 1.026,
}
```

This might look weird, but it's "correct" from the API perspective. You can then use them like:

`EnumWithNumbers['1.026'] `

Yes, this is weird, but an enum like this is very weird :-) You can also add x-enum-varnames in the spec to describe these magic numbers:

```
            "EnumWithExtensions": {
                "description": "This is a simple enum with numbers",
                "enum": [
                    200,
                    400,
                    500
                ],
                "x-enum-varnames": [
                    "CUSTOM_SUCCESS",
                    "CUSTOM_WARNING",
                    "CUSTOM_ERROR"
                ],
                "x-enum-descriptions": [
                    "Used when the status of something is successful",
                    "Used when the status of something has a warning",
                    "Used when the status of something has an error"
                ]
            },
```

**Comment by ferdikoomen** [comment]
@CheesyFeet please test using 0.9.3 version (just pushed it)

**Comment by CheesyFeet** [comment]
Can confirm 0.9.3 generates the enums without causing typescript errors for me - thanks!
