### ISSUE TITLE
--useUnionTypes still uses enums for path parameters

### ISSUE THREAD

**Issue by ljwagerfield** [ferdikoomen/openapi-typescript-codegen#634]
### Expected behaviour

When specifying `--useUnionTypes` union types are used everywhere instead of enum types.

### Current behaviour

Given the following schema:

```json
"/v1/accounts/{accountId}/security/api_keys/{apiKeyType}": {
  "post": {
    "operationId": "CreateApiKey",
    "responses": {
      "204": {
        "description": "Success.",
        "content": { "application/json": { "schema": { "$ref": "#/components/schemas/ApiKeyExpanded" } } }
      }
    },
    "parameters": [
      {
        "in": "path",
        "name": "apiKeyType",
        "required": true,
        "schema": { "$ref": "#/components/schemas/ApiKeyType" }
      }
    ]
  }
}
...
"schemas": {
 "ApiKeyType": {
    "type": "string",
    "enum": ["public", "secret"],
    "example": "secret",
    "description": "API key type.",
    "pattern": "^(public|secret)$"
  }
}
```

When passing `--useUnionTypes`, the following code is generated:

```typescript
public static async createApiKey(
    apiKeyType: ApiKeyType
  ): Promise<void>

...

export enum ApiKeyType {
  PUBLIC = "public",
  SECRET = "secret"
}
```

---

|           Dependency            |  Version  |
|------------------------------|-----------|
| `openapi-typescript-codegen` | `0.9.3`   |
| `typescript`                 | `4.1.2`   |
| `node`                       | `12.19.0` |

**Comment by ljwagerfield** [comment]
Possibly related to https://github.com/ferdikoomen/openapi-typescript-codegen/issues/633

**Comment by GoodGuyMarco** [comment]
Hey folks, what is the status about this? Are there plans on fixing this behaviour?

**Comment by ferdikoomen** [comment]
Merged PR
