### ISSUE TITLE
How to deal with errors

### ISSUE THREAD

**Issue by ex0ns** [ferdikoomen/openapi-typescript-codegen#655]
I'm using the following definition to generate TS code from this lib

```yaml    
      /api/1.0/move:
        post:
            operationId: postApi1.0Move
                - name: user
                  in: header
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: ''
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GameInfo'
                '400':
                    description: ''
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorInfo'
```

Which I then use from my code:

```typescript
const gameInfo = await Service.postApi10Move(user);
if ('id' in gameInfo) {
                                // valid move
} else {
                                // invalid move, represented by an ErrorInfo
}
```

Unfortunately, this does not work because the underlying `request` function called by the `postApi10Move` uses `Throw` to throw an error in case the response is not 200. I don't think this is a good idea. Many API are expected to return a body even if the status code is not 200.

This force the client to wrap the API calls inside some try/catch such as 

```typescript
try {
  const gameInfo = await Service.postApi10Move....
  ...
} catch (e) {
  console.error(e.body);
  return false;
}
```

Did I miss something or is it the way it was desgiend to work ? Is there a way around that behavior using this library ?

**Comment by ferdikoomen** [comment]
@ex0ns This is how it was designed, successful requests (HTTP status 200 range) will return normally and unsuccessful requests will throw an error. In many application cases you would probably want to show a notification to the user. So indeed your second example is correct:
```
try {
  const gameInfo = await Service.postApi10Move....
  // valid move, you should have gameInfo.id
} catch (e) {
  // invalid move, represented by an ErrorInfo inside (e.body)
}
```
