### ISSUE TITLE
Add support for type mappings

### ISSUE THREAD

**Issue by npwork** [ferdikoomen/openapi-typescript-codegen#669]
In my schema I have type `number` with format, which is currently ignored by `openapi-typescript-codegen`
For my use case I have numbers that can't be represented in typescript's `number` (too big values)

so it would be great to have some sort of flag:
`--typeMappings number=Big`

Another usecase is to replace dates with moment's dates.

**Comment by ferdikoomen** [comment]
@npwork How does that spec look like? Is it a `integer` with a `int64` format? 

On the replacement of dates:
Never use moment.js https://momentjs.com/docs/#/-project-status/, there are better alternatives. Or if really needed, just convert then when needed (in a UI component for instance)
There is a PR with a date parsing: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/494
Feel free to check if that works for you and comment on it
