### ISSUE TITLE
Generate models and services in separate folders

### ISSUE THREAD

**Issue by CloudPower97** [ferdikoomen/openapi-typescript-codegen#670]
Hello,
would it be feasible to generate models and schemas in different folders than where the services and core are?
At the moment, if one specify the option `--exportModels false` it seems that in the services it still tries to import models from the models directory that, obviously, has not been generated.

The main use case for this is the ability to share generated types/interfaces with different packages inside a lerna monorepo.

As a matter of fact, I was able to generate only models in a separate package of my choice, and the last step was to generate only the services and the core in another package, importing the types where needed.

**Comment by ferdikoomen** [comment]
@CloudPower97 Right now there are no plans to do this. A better (recommended) option would be to expose your generated code in the Lerna 'sub-package'. I would have the spec file inside this sub-package and do the generation there (as a build step), then you can do this using something like in that package.json:

{
    "name": "@my-project/my-client",
    "version": "0.0.1",
    "files": [
        "./generated/index.ts",
        "./generated/core/*.ts",
        "./generated/models/*.ts",
        "./generated/services/*.ts"
    ],
    "scripts": {
        "build": "openapi --input src/spec.js --output ./generated"
    },
    "dependencies": {
        "openapi-typescript-codegen": "^0.9.3"
    }
}
