### ISSUE TITLE
Consider renaming binary to something less generic

### ISSUE THREAD

**Issue by klaemo** [ferdikoomen/openapi-typescript-codegen#680]
Hey there,
thank you for creating this very useful tool :)

I noticed that the executable of this module is called `openapi`. Unfortunately, there are other tools out there that use the same name, notably `@redocly/openapi-cli`. So, I can't have both installed in the same project and invoke them with npm scripts.

Would it be possible to rename the binary from `openapi` to something like `openapi-typescript` to avoid this clash?

**Comment by ferdikoomen** [comment]
@klaemo Hi i will consider this for the next mayor release

**Comment by xiaoyu-tamu** [comment]
have you tried with npx? `npx openapi-typescript-codegen`

**Comment by ferdikoomen** [comment]
@klaemo i checked this with a few parties that use the generator. Although not a big issue it does break backwards compatibility. And like @xiaoyu-tamu mentioned you can use npx openapi-typescript-codegen command if there is a big clash in these specific cases. Closing the issue to cleanup the board.

**Comment by iamjaredwalters** [comment]
@ferdikoomen `npx openapi-typescript-codegen` will still have the same issue. If two packages define an executable of the same name, npx or not, they will overwrite each other.
