### ISSUE TITLE
Make generated code to be tree-shakable

### ISSUE THREAD

**Issue by gzaripov** [ferdikoomen/openapi-typescript-codegen#696]
Static classes are not tree-shakable by most of the bundlers, for example rollup https://github.com/rollup/rollup/issues/349

It can be convenient to use Api.doMethod() notation but it costs us a lot. My service file is quite big and has 8000 lines. When I want to import use some api method in my code, webpack will load the whole file into my application.

Can we make an option to export functions instead of a big service class to make them tree-shakable?

**Comment by cmcnicholas** [comment]
I agree these shouldn't be static methods, we have a similar issue but many thousands of lines generated.

We have 6 api's we integrate with and generate a single module for all our projects to install that includes the combined codegen outputs so we can maintain them all in once place. It does mean as these api's grow all products will be consuming this code and forced to pack many unused methods.

**Comment by ferdikoomen** [comment]
@gzaripov @cmcnicholas How would that work with similar function names?
`UserService.create`
`ProjectService.create`

I can export just the create functions inside the UserService file and ProjectService files, but when i export these in the index.ts file this will break. Should we prefix the methods?

`export const UserService_create = () => {...}`
`export const ProjectService_create = () => {...}`

**Comment by cmcnicholas** [comment]
The index.ts file (barreling all those exports) you mention is something we dropped a while ago which made this possible for our codebase.

Unfortunately this may not be an option for you due to backwards compatibility.

**Comment by ferdikoomen** [comment]
@cmcnicholas @gzaripov I just released a new version 0.16.0 that has the `--name` option. This generated a standalone client with non-static service methods. This should solve your tree shaking. Downside is that you need to initialise the client once and pass that around you application, but that should be pretty easy.

Example: https://github.com/ferdikoomen/openapi-typescript-codegen#generate-client-instance-with---name-option
