### ISSUE TITLE
Support security schemes globally and per operation

### ISSUE THREAD

**Issue by Ziaunys** [ferdikoomen/openapi-typescript-codegen#704]
In the OAS v3 spec you can define security schemes and use them globally or on a per-operation basis. It would be nice if the client could be aware of these schemes. Otherwise, callers of my client need to know which headers to set for authentication which are implicitly part of the API.

**Comment by ferdikoomen** [comment]
@Ziaunys yes at the moment we just support bearer tokens, and indeed OAS3 has these in the spec, at the moment the support for this is very limited. Please feel free to create a PR for this, right now it's not very high on my priority list.
