### ISSUE TITLE
Provide mechanism to automatically URI encode components in generated service request paths.

### ISSUE THREAD

**Issue by davidschmitt** [ferdikoomen/openapi-typescript-codegen#714]
The generated services do not URI encode arguments that are used to build the request path.

It would be great if there were some option (probably when service code is generated) to automatically URI encode such path components.

For example, here's part of a service generated from the Camunda OpenAPI spec:

```
public static async startProcessInstanceByKey({
    key,
    requestBody,
  }: {
    /** The key of the process definition (the latest version thereof) to be retrieved. **/
    key: string;
    requestBody?: StartProcessInstanceDto;
  }): Promise<ProcessInstanceWithVariablesDto> {
    const result = await __request({
      method: "POST",
      path: `/process-definition/key/${key}/start`,
```

In this case the "key" argument needs to be URI encoded.  Obviously, the caller can do it ahead of time, but it is not obvious that they should do so.  For example:

```
    const result = await __request({
      method: "POST",
      path: `/process-definition/key/${encodeUriComponent(key)}/start`,
```

**Comment by ferdikoomen** [comment]
@davidschmitt The reason we do not encodeUriComponent by default is that the method is a bit too strict. For instance `encodeURIComponent('wikipedia:content')` is escaped as `'wikipedia%3Acontent'`. However the `:` character is technically fine.  https://en.wikipedia.org/wiki/Wikipedia:Contents
However there is a OpenAPI.ENCODE_PATH property that you can use to encode the fullpath before sending.
