### ISSUE TITLE
Client methods should return types associated with other status codes such as errors

### ISSUE THREAD

**Issue by Ziaunys** [ferdikoomen/openapi-typescript-codegen#728]
I noticed that client method signatures don't include error response types unless an error response is defined as a `default`.
Maybe I'm just doing it wrong, but at the moment it seems like the caller is responsible for de-serializing the error response from the `ApiError` object.

Here's an example of the generated method I'm dealing with:
```ts
     /**
      * Get list of RBAC groups
      * Get list of RBAC groups for workspace
      * @returns ListRbacGroupsV1 An RBAC groups response
      * @returns ErrorV1 API Error Response
      * @throws ApiError
      */
     public static async getGroupsV1({
         workspaceId,
     }: {
         /** Identifies a workspace **/
         workspaceId: WorkspaceIdV1,
     }): Promise<ListRbacGroupsV1 | ErrorV1> {
         const result = await __request({
             method: 'GET',
             path: `/v1/groups`,
             query: {
                 'workspaceId': workspaceId,
             },
         });
         return result.body;
     }
```
In this case `ErrorV1` is never returned because it's an error response and callers seem to be responsible for handling all errors. This prompted me to stop using `default` in my OpenApi spec which is preferable anyways.

What I'd like is to have the client be responsible for returning known error responses just as it returns a response for 200. Any errors that don't fall into the response definition or don't match the error type can throw `ApiError` since that, to me, is exceptional behavior.

**Comment by willyxiao** [comment]
This makes sense.

For anything in 400/500, would you rather have `ApiError` be typed (ie generate a bunch of errors that extend `ApiError`?) or have a large union of responses?

**Comment by ferdikoomen** [comment]
@Ziaunys @willyxiao The result model from an operation is calculated from the success response codes (200 range) and indeed the default response value. However, during runtime we check the response code and when this is not a success (200 range) then we throw an error. This error cannot be typed (due to limitation in typing of promises), so there is no easy or nice way to fix this.
