### ISSUE TITLE
Do you need help maintaining this project?

### ISSUE THREAD

**Issue by klaemo** [ferdikoomen/openapi-typescript-codegen#738]
Hey Ferdi,
I was wondering if you'd accept additional contributors to the project? There are quite a few PRs and bug reports that would be super useful to get addressed and released. I do understand that you're probably doing this in your free time and that's why I'm asking if the community could help out in any way? Stuff like reviewing PRs, creating releases etc.

I think a few people are already using forks of this project which is unfortunate.

Thank you!

**Comment by janhartigan** [comment]
@ferdikoomen second this! I'd be willing to help out as well

**Comment by rattrayalex** [comment]
Would either of you be willing to lead a published fork?

**Comment by CommCody** [comment]
Hi @ferdikoomen ,

If you could drop by and help the community move this project forward, it would be very much appreciated.
I would like to help as well

**Comment by ferdikoomen** [comment]
@janhartigan @CommCody @klaemo Hi all, sorry i had Corona, then a broken collarbone and finally a house move in between. I'll try to pickup the work again. But there is indeed a lot to catch up on. Let me know if you still want to collaborate, then we can have a chat!
