### ISSUE TITLE
Enum fields of compound objects are not generated.

### ISSUE THREAD

**Issue by cima** [ferdikoomen/openapi-typescript-codegen#771]
**Describe the bug**
A clear and concise description of what the bug is. Ideally with a screenshot of the result or a link to a small example.

# Steps to reproduce
Using NodeJS 10 (due to azure limitations)
```
md myProject
cd myProject
git clone https://github.com/MicrosoftDocs/vsts-rest-api-specs.git
npm install openapi-typescript-codegen --save-dev
npm install --global strip-bom-cli
cd .\\vsts-rest-api-specs\\specification\\testPlan\\6.1\\
npx strip-bom-cli .\testPlan.json > .\testPlan_x.json
npx openapi --input testPlan_x.json  --output ../../../../src-generated/azure/testPlan --client node
```

see file ./myProject/src-generated/azure/testPlan/models/TestSuiteCreateParams.ts

## Actual result
```typescript
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { TestSuiteCreateUpdateCommonParams } from './TestSuiteCreateUpdateCommonParams';

/**
 * Test suite Create Parameters
 */
export type TestSuiteCreateParams = (TestSuiteCreateUpdateCommonParams & {
/**
 * Test suite requirement id.
 */
requirementId?: number,
/**
 * Test suite type.
 */
suiteType?: TestSuiteCreateParams.suiteType,
});
```

## Expected result
```typescript
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { TestSuiteCreateUpdateCommonParams } from './TestSuiteCreateUpdateCommonParams';

/**
 * Test suite Create Parameters
 */
export type TestSuiteCreateParams = (TestSuiteCreateUpdateCommonParams & {
/**
 * Test suite requirement id.
 */
requirementId?: number,
/**
 * Test suite type.
 */
suiteType?: TestSuiteCreateParams.suiteType,
});

export namespace TestSuiteCreateParams {

    /**
     * Clone operation state
     */
    export enum suiteType {
        NONE = 'none',
        DYNAMIC_TEST_SUITE = 'dynamicTestSuite',
        STATIC_TEST_SUITE = 'staticTestSuite',
        REQUIREMENT_TEST_SUITE = 'requirementTestSuite'
    }

}
```

## Notes

I suspect the fact that object [_TestSuiteCreateParams_](https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/testPlan/6.1/testPlan.json#L5015) in swagger is constructed as compound (from allof $ref) which causes properties to inherit $ref and thus in  your file [getModelProperties.ts](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/openApi/v2/parser/getModelProperties.ts) the enum directive is omitted.

**Comment by ferdikoomen** [comment]
@cima Indeed i see the same, it works fine if i remove the section:
```
      "allOf": [
        {
          "$ref": "#/definitions/TestSuiteCreateUpdateCommonParams"
        }
      ],
```
So, probably related to that area in the code, let me check what i can find and fix here

**Comment by ferdikoomen** [comment]
Pushed a fix to the master branch, will upload a new version to npm soon (0.12.5)
