### ISSUE TITLE
Not decoded URI component on ref

### ISSUE THREAD

**Issue by todesstoss** [ferdikoomen/openapi-typescript-codegen#791]
Hello, trying to generate TS on completely valid OpenAPI schema having this error:

```Error: Could not find reference: "#/paths/~1admin~1cache~1clear~1%7BcacheName%7D/parameters/0"```

Looks like this ref url in not decoded properly

**Comment by todesstoss** [comment]
if it could help, a similar issue:

https://github.com/drwpow/openapi-typescript/issues/587

**Comment by todesstoss** [comment]
The issue is in this file:

https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/openApi/v3/parser/getRef.ts

path is not decoded properly.

Maybe Pointer.parse from `json-schema-ref-parser` library should be used here?

**Comment by rbruggem** [comment]
Does https://github.com/todesstoss/openapi-typescript-codegen/pull/1 fix the issue?

**Comment by ferdikoomen** [comment]
Hi all the fix has been merged
