### ISSUE TITLE
Subpath references not supported in $ref

### ISSUE THREAD

**Issue by mikekniffen** [ferdikoomen/openapi-typescript-codegen#792]
Hello, thanks for all of your great work on this project! It has been hugely useful to me.

I've run into an issue when trying to generate a client for www.pagerduty.com . Link to [their openapi schema](https://github.com/PagerDuty/api-schema/blob/main/reference/REST/openapiv3.json) for reference.

The client generator is unable to follow a $ref that specifies an index under an allOf, anyOf, etc

Example snippet:
```javascript
{
    "$ref": "#/components/schemas/Tag/allOf/0"
}
``` 

This ends up resolving to
```typescript
import type { Tag_allOf_0 } from './Tag_allOf_0';
export type BusinessService = (Tag_allOf_0 & {
...
```
But the file "Tag_allOf_0.ts" is not generated and the generator does not understand the subpath referencing.

I am interested in contributing support for this use case. I want to consult with you first on the design of the solution, as it is not trivial.

Rough proposed solution:
- Modify getType() to understand index references and return a subpath as a field of its result object
- Modify getModel() / Model type to store this subpath as an attribute
- Modify model generator to export each subtype of a composition, then express the type as a composite of those subtypes
- Modify model generator to understand $ref by index / subpath, and to import the correct subtype from the referenced model's .ts file

Please let me know if this makes sense or if you have a preferred solution.

Thank you!
-Mike Kniffen

PS - Below is a minimal sample openapi spec which reproduces this issue.

```javascript
{
  "openapi": "3.0.0",
  "info": {
    "version": "v1.0"
  },
  "components": {
    "requestBodies": {
      "SimpleRequestBody": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Tag"
            }
          }
        }
      }
    },
    "schemas": {
      "ReferenceCompositionByIndex": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Tag/allOf/0"
          }
        ]
      },
      "Tag": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by ferdikoomen** [comment]
@mikekniffen At the moment this is correct, there is a bug fixed with subpaths that seems to resolve the generation. Attached screenshot of new result. Will upload a new version soon!
<img width="983" alt="Screenshot 2021-09-27 at 21 47 30" src="https://user-images.githubusercontent.com/1791679/134975148-e6e769b7-e177-4f3b-b1f8-40e84d84f511.png">
