### ISSUE TITLE
Reusing existing types

### ISSUE THREAD

**Issue by johtso** [ferdikoomen/openapi-typescript-codegen#801]
If my client and server share a codebase, is there any way to reuse my types rather than generating new types based on the OpenAPI spec?

The scenario is something like `typebox to define types and json schema` -> `fastify` -> `generate OpenAPI spec` -> `generate typescript client`

I'm guessing knowing which types to reference would be impossible as the relationship is lost along the way..

Just seems a shame not to be able to easily refer back to my original type definitions, and to have the types all in-lined and duplicated.

**Comment by WORMSS** [comment]
This would be something very useful, but may I suggest word of warning..
We have quite a large typescript codebase, and sometimes when the server updates their web request/response models it is sometimes overwhelming of a change. NOT using the webmodels throughout your codebase may actually be a safer option.

Trust me, It's something we wished we didn't do.

**Comment by ferdikoomen** [comment]
@johtso Right now there is no way to reuse types. If you want a stable way of doing then then i agree with @WORMSS. For instance in our (internal company) codebase we define our datalayer models and we base then in the OpenAPI generated models, but in the codebase we never work directly with the OpenAPI models. In case of changes it's just a minor change in a local area. Minimal (pseudocode) example:

The **MyUser** model
```
import { User as _User } from "my-open-api-client";
export type MyUser = _User;
```

The **MyUser** service
```
import { UserService } from "my-open-api-client";
import { MyUser } from "./datalayer";

const getUsers = async () => {
   await UserService.getUsers() as MyUser[];
};
```
