### ISSUE TITLE
Blob Support

### ISSUE THREAD

**Issue by Katarina-Chirich** [ferdikoomen/openapi-typescript-codegen#802]
So, as far I as understand, it looks like if we get from a server JSON, getResponseBody will return json, but for everything else it will return text. 

What if I need blob (and I need actually :))? Can we return here response.blob()?

![image](https://user-images.githubusercontent.com/51708132/126786389-5413cbd4-f035-4622-a045-c8d364ba571b.png)

**Comment by ferdikoomen** [comment]
@Katarina-Chirich Can you explain why you need the Blob? Or better: Can you show the spec for the operation? Because then i can check how to map the input and output types

**Comment by ferdikoomen** [comment]
Closing this due to no response.
