### ISSUE TITLE
How do I read a response’s headers?

### ISSUE THREAD

**Issue by nandorojo** [ferdikoomen/openapi-typescript-codegen#812]
Is there a way to read the headers of a response, similar to the `fetch(url).then(response => response.headers)`?

If not, maybe we could add this under a `__headers?: {}` field on all response objects?

Huge fan of this lib, btw. I'd be happy to submit a PR for this!

**Comment by jerber** [comment]
+1

**Comment by ferdikoomen** [comment]
@nandorojo This is driven by the OpenAPI spec itself. A response can be from the 'body' of the request or from a header. 
In the OpenAPI spec (3.0) this looks something like:
```
"responses": {
   "200": {
      "description": "Successful response that reads data from header",
         "headers": {
            "x-some-header-name": {
               "schema": {
                  "type": "string"
               }
            }
         }
      }
   }
}
```
But it's an either/or situation. You can get data from body OR from the headers, but not both.

**Comment by mskrip** [comment]
@ferdikoomen Could you please provide a link to the spec that says that? I found [this article in the OpenAPI 3.0 spec](https://swagger.io/docs/specification/describing-responses/) which explicitly says:
> A response is defined by its HTTP status code and the data returned in the response body **and/or** headers.

(see and/or, not either/or)

Also I found [this example](https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/examples/v3.0/petstore.yaml#L25) in the spec with both `headers` and `content` defined in the response schema.

**Comment by banool** [comment]
As far as I'm aware this still isn't possible. I've opened a new issue and made it clear that it is perfectly fine for an OpenAPI spec response to use both the body and headers.

**Comment by banool** [comment]
We have added a hack as a workaround in our fork: https://github.com/aptos-labs/openapi-typescript-codegen/tree/0.24.0. It just adds `__headers` to the response. This won't work if the response isn't an object (e.g. an object) hence the `try / catch`.

**Comment by mosskin-woast** [comment]
@ferdikoomen, can you please take another look at this issue? It is now over a year old and describes a missing feature that makes the library unusable for applications where headers are used for critical data like CSRF tokens. I can't find any evidence to support your statement that OpenAPI response specs support only one of headers or body - if you can provide some, that would be helpful. Regardless of whether the OpenAPI spec supports it, it is useful for HTTP clients to he able to read response headers - an escape hatch to access a raw map of headers in the response would be equally useful.

I think the ideal solution is to improve on @banool's proposed patch and merge it.

**Comment by Bears-Eat-Beets** [comment]
This feature would be very useful for requests requiring a response body and headers, such as responses that include an ETag, which assists in "mid-air collisions" of database objects.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

I have had to resort back to plain Axios for a few API calls, which isn't a big deal but feels a bit like tech debt.

**Comment by mrlubos** [comment]
@Bears-Eat-Beets Hey! How do you get both body and headers with plain Axios?
