### ISSUE TITLE
Support Angular http client

### ISSUE THREAD

**Issue by matthelliwell2** [ferdikoomen/openapi-typescript-codegen#821]
**Describe the solution you'd like**
I would like the option to generate client code that uses the Angular http library instead of fetch.

I have some Angular projects (version 11 and 12) that make calls to external rest services. We currently handcraft the calls to the rest services. We have open api specs available for the services so I would like to be able to generate client code that I can use in Angular.

The issue is that the projects make use of HttpInterceptors in Angular. When I use the generated code it is using Fetch so the interceptors will not get called.

**Comment by ferdikoomen** [comment]
@matthelliwell2  Right now we do not support this. You can use the --request option to supply a custom request method. See https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/test/custom/request.ts for an example of such a custom request file. There are no plans to support framework specific logic. Angular decided that they needed a whole abstraction layer for the HTTP calls, but if we start supporting this, then we probably need to rewrite this layer as many times as i has been rewritten in Angular ;-)
