### ISSUE TITLE
~1 escaped characters do not seem to be parsed for reference paths

### ISSUE THREAD

**Issue by WORMSS** [ferdikoomen/openapi-typescript-codegen#824]
I was trying to codegen this maps openapi3 spec made by Google.

https://raw.githubusercontent.com/googlemaps/openapi-specification/main/dist/google-maps-platform-openapi3.json

They make use of 
```json
"parameters": [
          {
            "$ref": "#/paths/~1maps~1api~1directions~1json/get/parameters/0"
          },
          {
            "$ref": "#/paths/~1maps~1api~1directions~1json/get/parameters/1"
          },
```
from what I gather it's something like
#/paths/`path to another endpoint`/`method`/parameters/`endpoint parameter index`

I've had a quick look around your code, sadly I wasn't exactly sure what I was looking for, but I didn't see anything even remotely close to this type of parsing..

I did a quick little hack and this seems to work, but I am unsure if there would be a more official fix for this.

```js
function getRef(openApi, item) {
    if (item.$ref) {
        // Fetch the paths to the definitions, this converts:
        // "#/components/schemas/Form" to ["components", "schemas", "Form"]
        const paths = item.$ref
            .replace(/^#/g, '')
            .split('/')
            .filter(item => item)
            .map(p => p.replace(/~1/g, '/')); // replace any escaped '/' back from '~1'
```
Obviously I did this 'after' you split on '/'

**Comment by ferdikoomen** [comment]
@WORMSS You where correct, this has been resolved. New version will be uploaded soon.
