### ISSUE TITLE
Arguments for Service Calls should be passed as a single object

### ISSUE THREAD

**Issue by knoefel** [ferdikoomen/openapi-typescript-codegen#826]
**Describe the bug**
When a generated service method accepts multiple parameter and some of them are optional, TS complains when they are mixed up. This happens if an optional parameter is followed by a required parameter.

<img width="666" alt="Screenshot 2021-09-06 at 17 08 41" src="https://user-images.githubusercontent.com/2396344/132237538-69dedfa5-661a-4ab1-9afb-48a73595d56d.png">

If the parameter are passed as a single object, i guess this error wouldn't happen. But maybe I'm missing something or doing something wrong and this problem can be solved differently? 

However in my opinion passing the parameter by object would be much cleaner and scales better for situations with many parameters like in a query call with many query params.

In any case, it's a great lib - thanks and keep up the great work! 👍

**Comment by EvanFBC** [comment]
Try the --useOptions flag

**Comment by knoefel** [comment]
Oh no, i somehow overlooked this in the docs. 😳 Thanks @EvanFBC and sorry for the spam.

**Comment by knoefel** [comment]
Now I do have another question: is it possibly planned to also generate TS types from the object-style arguments?

```ts
// Instead of this
function createUser({ name, password, type, address }: {
    name: string,
    password: string,
    type?: string
    address?: string
}) {
    // ...
}

// Use generated input types
function createUser({ name, password, type, address }: CreateUserInput) {
    // ...
}
```

For example, the OperationId name with the suffix "Input" could be used as the naming. This would make it easier to write wrapper methods that pass the input to the API service method. In my case I use `react-query` and outsource each service call to a hook, so it would be convenient to pass and use this generated input type as an argument to the hook instead of having to define it again.

**Comment by knoefel** [comment]
As a quick fix i got it working by adding a helper type, which extracts the arguments.

```ts
export type ExtractArgsAsType<FnType> = FnType extends (args: infer Args) => any ? Args : never;

// QueryService would be a generated service provided by openapi-typescript-codegen
export type QueryInput = ExtractArgsAsType<typeof QueryService.getItems>;
```

**Comment by motorin** [comment]
Hi, guys.

It's so nice, I'm not the only one, who wants it! :)

I met with the same problem: in fact, when you only prepare the object to put it in service method props, it's nice to have typings for this object.

So, I did PR for this.
I propose automatic naming for these types like  `{{ServiceMethodName}}{{HTTPMethodName}}Props`
`GetClientsGetProps`, for example.

```
ClientService.getClients( { ... }: GetClientsGetProps ) { ...}
```

So, now, if you are using `--useOptions` you get named typings for service methods props as well.


There is PR: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/828

**Comment by ferdikoomen** [comment]
@EvanFBC @motorin @knoefel  In Typescript there is a very easy way to extract the "type" in this case.

```
type GetClientsParams = Parameters<typeof ClientService.getClients>;
```
https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype

I would suggest using this approach, or export named 'request' models for you requests?

**Comment by nicoandresr** [comment]
@ferdikoomen  @motorin The utility type `Parameters<Type>` from typescript almost works well in this case because constructs a tuple type:

> Constructs a tuple type from the types used in the parameters of a function type Type.

I prefer the @knoefel version that not constructs a tuple and here a fork of the helper type:

```ts
type Parameter<T extends (...args: any[]) => any> = T extends (args: infer Args) => any ? Args : never;
```
