### ISSUE TITLE
How should we validate using the exported schemas?

### ISSUE THREAD

**Issue by goodoldneon** [ferdikoomen/openapi-typescript-codegen#827]
How should I use the exported schemas to validate responses? They don't appear to be valid JSON schema, so we can't run them through `ajv`

**Comment by ferdikoomen** [comment]
@goodoldneon good point, right now the schema's have a custom format, due to some limitations of JSON schema. But you can use something like: https://github.com/openapi-contrib/openapi-schema-to-json-schema if you want to generate JSON schema's from your openapi spec
