### ISSUE TITLE
Typescript cannot compile generated code for Node with node-fetch v3: "Type 'string | ArrayBuffer | ArrayBufferView' is not assignable to type 'BodyInit | undefined'."

### ISSUE THREAD

**Issue by Nick-Lucas** [ferdikoomen/openapi-typescript-codegen#830]
Edit: This appears to be a problem introduced by node-fetch `3.0.0` and downgrading to 2.x resolves the compilation issue. I am leaving this issue in place for others who get the problem.

Configuration:

* Typescript: 4.4.3
  * tsc / ts-node running on NodeJS
* Node 14 
* openapi-typescript-codegen: 0.9.3
  * Client: "node"

The following code is generated in `request.ts` but is not able to compile as `BodyInit` does not contain `ArrayBuffer` in its union.

```js
// This code is generated by the package

function getRequestBody(options: ApiRequestOptions): BodyInit | undefined {
    if (options.formData) {
        return getFormData(options.formData);
    }
    if (options.body) {
        if (isString(options.body) || isBinary(options.body)) {
            return options.body;
        } else {
            return JSON.stringify(options.body);
        }
    }
    return undefined;
}
```

```
Type 'string | ArrayBuffer | ArrayBufferView' is not assignable to type 'BodyInit | undefined'.
  Type 'ArrayBuffer' is not assignable to type 'BodyInit | undefined'.
    Type 'ArrayBuffer' is missing the following properties from type 'Buffer': write, toJSON, equals, compare, and 76 more.
```

![image](https://user-images.githubusercontent.com/8896153/134389978-60543e6d-7d60-4e01-a109-d9a377941304.png)

**Comment by ferdikoomen** [comment]
Added support for node-fetch 3.0.0 from version 0.10.0 and onwards. Will upload a new version soon.

**Comment by hendrikdevloed** [comment]
> Added support for node-fetch 3.0.0 from version 0.10.0 and onwards. Will upload a new version soon.

Does this mean the remark in [docs/node-fetch-support.md](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/8485f9da0a069fbf571bae7f1261ee09eed4bb1e/docs/node-fetch-support.md) is no longer current and 3.0 is supported?

> Since version 3.x [node-fetch](https://www.npmjs.com/package/node-fetch) switched to ESM only, breaking many CommonJS based toolchains (like Jest). Right now we do not support this new version!

> npm install @types/node-fetch@2.x --save-dev
> npm install abort-controller@3.x --save-dev
> npm install form-data@4.x --save-dev
> npm install node-fetch@2.x --save-dev
