### ISSUE TITLE
Per-request auth / headers / request options

### ISSUE THREAD

**Issue by Lanny** [ferdikoomen/openapi-typescript-codegen#859]
**Describe the solution you'd like**
In server side rendering environments it is common that a single process may need to make requests on behalf of several users, each with their own set of credentials. It seems like this is doable with something like:

```ts
import { MyService, OpenAPI } from 'MyService'

OpenAPI.TOKEN = () => { OpenAPI.TOKEN = undefined; return 'abc123' }
MyService.someOperation({})
```

The issue is that the `TOKEN` needs to be set before each call in a bit of a clunky way, and if there the is anything async that happens between setting it and the request actually being sent off it's possible for one request to incorrectly be made with credentials intended for another. Ideally I'd like to be able to pass credentials as a final argument any operation (this works better with the "useOptions" style). I'd also be OK with passing some kind of extension of `ApiRequestOptions` so that resolvers could work on a per-req basis, e.g.:

```ts
import { MyService, OpenAPI } from 'MyService'

OpenAPI.TOKEN = (opts) => opts.myCustomAuth
MyService.someOperation({}, { myCustomAuth: 'abc123' )
```

**Comment by obabichev** [comment]
I got the same problem with the generated code.

I think that the fact that all the parameters are global makes the usage of the tool much more limited than it might be.

I use the library to generate the API for react native and jest tests. And in the tests, I got the problem that if two tests "concurrently" change the token it follows to the unstable behavior.

It might be a good idea to encapsulate all the parameters inside the class (/object/closure) and allow to create of different instances with different parameters.

**Comment by ankit-gaur** [comment]
more use-cases for custom headers are where service operation doesn't accept application/json and the guessed headers in the generated request file doesn't work so headers need to be overridden only in some cases.

**Comment by ferdikoomen** [comment]
These tickets are all related to the same "global" objects:
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/859
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/703
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/588

Closing them and keeping the original ticket:
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/428

I definitely see the use case, there is also already a PR for this:
PR: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/822

**Comment by ferdikoomen** [comment]
These tickets are all related to the same "global" objects:
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/859
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/703
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/588

Closing them and keeping the original ticket:
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/428

I definitely see the use case, there is also already a PR for this:
PR: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/822
