### ISSUE TITLE
Support multiple OpenAPI operation tags

### ISSUE THREAD

**Issue by Tak-Iwamoto** [ferdikoomen/openapi-typescript-codegen#860]
I would like to generate operations per OpenAPI operation tags.
An example is shown below.

OpenAPI definition
``` yaml
openapi: 3.0.0
info:
  title: sample
  version: '1.0'
paths:
  /example:
    get:
      tags:
        - tag1
        - tag2
      operationId: execute
      responses:
        '200':
          description: OK
```

generated codes

`Tag1Service.ts`
``` typescript 
export class Tag1Service {
  public static async execute() {...}
}
```

`Tag2Service.ts`
``` typescript
export class Tag2Service {
  public static async execute() {...}
}
```

If possible, I would like to contribute to this feature development.
Thanks.

**Comment by ferdikoomen** [comment]
@Tak-Iwamoto Sound logical from a spec point of view, but why would you want exactly the same code in both services :-) But i agree that from looking at the spec i would also expect the same

**Comment by ferdikoomen** [comment]
@Tak-Iwamoto i pushed a update into the master branch, will push version 0.12.0 soon (today or tomorrow)

**Comment by Tak-Iwamoto** [comment]
@ferdikoomen 
Awesome! Thank you so much :grinning:
