### ISSUE TITLE
getOperationName custom user hook

### ISSUE THREAD

**Issue by reslear** [ferdikoomen/openapi-typescript-codegen#864]
add to 

https://github.com/ferdikoomen/openapi-typescript-codegen/blob/830b317d0a0f6aaa97dba43818ce6d1ccc109be2/src/openApi/v2/parser/getOperation.ts#L19

or

https://github.com/ferdikoomen/openapi-typescript-codegen/blob/830b317d0a0f6aaa97dba43818ce6d1ccc109be2/src/openApi/v3/parser/getOperationName.ts#L8

custom user hook

for use like example

```ts
OpenAPI.generate({
    input: './spec.json',
    output: './dist',

    // feat
    getOperationName: (name) => name.toLowerCase()
});
```

**Comment by ferdikoomen** [comment]
@reslear The generate call should match the 'API' for the CLI, so this is hard to do. Plus the correct 'formatting' is pretty standard (pascal case) for Javascript or Typescript projects. If I want to change anything that i would not do any formatting at al, leave it as close to the original name as defined in the spec file
