### ISSUE TITLE
custom service postfix 

### ISSUE THREAD

**Issue by reslear** [ferdikoomen/openapi-typescript-codegen#865]
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/830b317d0a0f6aaa97dba43818ce6d1ccc109be2/src/openApi/v3/parser/getServiceClassName.ts#L14

like 

```ts
OpenAPI.generate({
    input: './spec.json',
    output: './dist',
    postfixes: {
       service: "Api"
    }
});
```

`FriendsService` -> `FriendsApi` or without prefix ->`Friends`

and for skip item simple remappings

<img width="353" alt="Screenshot 2021-10-24 at 18 28 21" src="https://user-images.githubusercontent.com/12596485/138600979-64baf430-9135-4b25-bc76-11c29830196e.png">

**Comment by ferdikoomen** [comment]
Hi @reslear In 0.12.0-alpha i added the postfix parameter to allow you to control the postfix of services. Could you test this? The API is:
```
OpenAPI.generate({
    input: './spec.json',
    output: './dist',
    postfix: 'Api'
});
```

Its just `postfix` since we only have that one at the moment and we need a nice way to support his from command line
