### ISSUE TITLE
exclude parameters in header 

### ISSUE THREAD

**Issue by reslear** [ferdikoomen/openapi-typescript-codegen#866]
<img width="1176" alt="Screenshot 2021-10-24 at 18 46 19" src="https://user-images.githubusercontent.com/12596485/138601890-6684c645-6c71-418b-a680-9955505e5ed7.png">

exclude parameters in header on any requests, and set once in header 

```ts
OpenAPI.generate({
    input: './spec.json',
    output: './dist',

   // feat
    excludeParameters: (name, in) => name === "apiKey" && in === 'header'
});
```

and set 

```ts
OpenAPI.HEADERS = {
  apiKey: process.env.apiKey
}
```

**Comment by ferdikoomen** [comment]
@reslear The goal of the project is to generate a "true" result of the API as defined in the SPEC file. The API key parameter is part of your spec and thus should be included in each call. The best way to handle these situations is to wrap the services in your own and modify what's needed:

```
import { UserService as _UserService } from "./generated";
import { API_KEY } from "./constants";

// Move this to some util file
type RemoveFirstFromTuple<T extends any[]> = 
    T['length'] extends 0 ? undefined : 
        (((...b: T) => void) extends (a, ...b: infer I) => void ? I : [])

export class UserService {

    public static create(...args: RemoveFirstFromTuple<Parameters<typeof _UserService.create>>): ReturnType<typeof _UserService.create> {
        return _UserService.create(API_KEY, ...args);
    }

    public static update(...args: Parameters<typeof _UserService.update>): ReturnType<typeof _UserService.update> {
        return _UserService.update(API_KEY, ...args);
    }
}
```

**Comment by reslear** [comment]
I also temporarily entered :) It would be cool if the tool was flexible and customizabled
