### ISSUE TITLE
Ability to exclude certain operations from Service

### ISSUE THREAD

**Issue by ashkanjj** [ferdikoomen/openapi-typescript-codegen#874]
**Describe the solution you'd like**

Would be great to be able to exclude generating services from certain operations such as OPTIONS. Currently, as far as I can tell, there is no way to exclude any operations from the generated client.

One possible solution is to add a certain header in the openapi spec to mark it as "internal" (similar to how redoc.ly do [this](https://redoc.ly/docs/cli/guides/hide-apis/))

**Comment by ferdikoomen** [comment]
@ashkanjj The first question would be: Why are you hiding it from the 'generated' code while it is in the spec... I mean it's not very hidden :-) But we could do something like the "x-internal: true" setup that they have https://redoc.ly/docs/cli/guides/hide-apis/#Operation-marked-as-internal Not sure if that works for you?

**Comment by ferdikoomen** [comment]
Closing this issue for cleanup. If it's inside the SPEC, it's not private, you use the SPEC file to define your endpoints. Off-course you are free to not use the endpoints :-)
