### ISSUE TITLE
Duplicated exports

### ISSUE THREAD

**Issue by robertusopo** [ferdikoomen/openapi-typescript-codegen#875]
When you run the script, it generates the index.ts with the different models and services.

If the API has a pagination DTO, like "PagedResultDto" what it appears many times. It tries to create and import the different type, but is stucked on the first one. 

`export type { PagedResultDto } from './models/PagedResultDto';
export type { PagedResultDto } from './models/PagedResultDto';
export type { PagedResultDto } from './models/PagedResultDto';
export type { PagedResultDto } from './models/PagedResultDto';
export type { PagedResultDto } from './models/PagedResultDto';
export type { PagedResultDto } from './models/PagedResultDto';
export type { PagedResultDto } from './models/PagedResultDto';`

and inside, you can see the same import: 

`import type { UserDto } from './UserDto';
export type PagedResultDto = {
    totalCount?: number;
    items?: Array<UserDto>;
}
`
when you must see different ones (UserDto, TenantDto, etc.)

**Comment by ferdikoomen** [comment]
@robertusopo do you have an example spec that i can test?

**Comment by ferdikoomen** [comment]
@robertusopo ?

**Comment by ferdikoomen** [comment]
No response, closing the issue
