### ISSUE TITLE
Use `as const` for runtime schemata

### ISSUE THREAD

**Issue by yuhr** [ferdikoomen/openapi-typescript-codegen#877]
**Describe the solution you'd like**

The contents of schemata should be statically typed. This enables us to conditionally generate derivative static types based on schemata. Could this be an option like `--exportSchemas asConst`?

<img width="356" alt="Screen Shot 2021-11-05 at 19 55 42" src="https://user-images.githubusercontent.com/18474125/140500233-14681c42-40b9-441a-82fe-628a441b7bfc.png">

<img width="379" alt="Screen Shot 2021-11-05 at 19 55 56" src="https://user-images.githubusercontent.com/18474125/140500245-5dff40d8-02eb-4ffb-acba-da160bfa1d1f.png">

**Comment by ferdikoomen** [comment]
I think we can, i have added this for 0.12.0-alpha, could you retest this?

**Comment by yuhr** [comment]
YES it worked, thank you! It seems to be enabled with `--exportSchemas true`, it's completely okay for me, but I'm afraid there might be a small surprise to existing users as it changes every field into `readonly` so that the schema object cannot be mutated. Though the package is still 0.x.x so it's totally safe.

**Comment by ferdikoomen** [comment]
@yuhr well it could be a surprise, but really people should not mutate this property anyway :D

**Comment by yuhr** [comment]
Yeah, definitely 😆
