### ISSUE TITLE
Similar to #249. Request.credentials as "omit"

### ISSUE THREAD

**Issue by cale148** [ferdikoomen/openapi-typescript-codegen#880]
When server returns wildcard for allow-origin it doesn't wok with "include" option and sending cookies (WITH_CREDENTIALS === true) due to hardcoded in the template

   `if (OpenAPI.WITH_CREDENTIALS) {
        request.credentials = 'include';
    }`

How can I support *omit* instead of *include*?

**Comment by ferdikoomen** [comment]
@cale148 why do you nee omit, instead of the default `"same-origin"` when you set `OpenAPI.WITH_CREDENTIALS` to false?

**Comment by ferdikoomen** [comment]
Because with "same-origin" you will only send cookies to domains that are on the same origin, in your case that should give you the same result as omit.

**Comment by cale148** [comment]
@ferdikoomen If I set credentials to false it wouldn't send token in cookies but I need them. Backend server provide wildcard instead of referrer for example. So means if it with "same-origin" I get 401 in that case

**Comment by cale148** [comment]
anyway in standard it's 3 options and would be helpful have case to pass them all

**Comment by ferdikoomen** [comment]
@cale148 but with `omit` the cookies are not send at all.. 
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

So i still don't get it:
- `omit`: Never send or receive cookies.
- `same-origin`: Send user credentials (cookies, basic http auth, etc..) if the URL is on the same origin as the calling script. This is the default value.
- `include`: Always send user credentials (cookies, basic http auth, etc..), even for cross-origin calls.

So if you want the cookie, you can use `same-origin` (OpenAPI.WITH_CREDENTIALS = false), or 'include' (OpenAPI.WITH_CREDENTIALS = true)

Btw its not a standard, its a FETCH standard, XHR request don't have these 3 values, it just has one flag:
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by cale148** [comment]
@ferdikoomen sorry, here's misprint, it's about headers not cookies. I need authorisation, when I enabled WITH_CREDENTIALS it passes "authorization" header with request but rises CORS issue due to server provides "Access-Control-Allow-Origin: *"
So "The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*'" (https://stackoverflow.com/a/19744754). Same origin doesn't fit to me due to I do request from another domain than API server. Only "omit" sends authorisation header and ignores wildcard

**Comment by ferdikoomen** [comment]
ahhh now it makes sense!

**Comment by ferdikoomen** [comment]
@cale148 I pushed the changes to the master branch, will upload a 0.12.0-beta soon. After testing i'll publish a 0.12.0 (hopefully today / tomorrow).

**Comment by cale148** [comment]
@ferdikoomen great, thanks!
