### ISSUE TITLE
Can't compile with client axios

### ISSUE THREAD

**Issue by landoephan** [ferdikoomen/openapi-typescript-codegen#884]
**Describe the bug**
A clear and concise description of what the bug is. Ideally with a screenshot of the result or a link to a small example.

When I use the following command 
```
openapi --input http://localhost:8000/api/schema/?format=json --output src/generated/swagger --client axios
```
I get the following error when trying to run my vue app:
TS7016: Could not find a declaration file for module 'form-data'.

the error originated in `request.ts` at import `FormData from 'form-data'`

I already tried to install the type with `npm i --save-dev @types/form-data`. But no success.

**Comment by ferdikoomen** [comment]
Hi @landoephan There is a section missing indeed inside the documentation. Will add that soon (and then close the ticket). But the axios client can be used inside NodeJS and browser based environments, but because of that you need additional dependencies:

```
"axios": "^0.24.0",
"cross-blob": "^2.0.1",
"form-data": "^4.0.0",
```

**Comment by ferdikoomen** [comment]
Added documentation: https://github.com/ferdikoomen/openapi-typescript-codegen#axios-support

**Comment by landoephan** [comment]
I think it's enough to install form-data and put "node" to your tsconfig.json types array
