### ISSUE TITLE
Allow custom service naming/formatting

### ISSUE THREAD

**Issue by bardkalbakk** [ferdikoomen/openapi-typescript-codegen#886]
Service name generation generates redundant names when processing Open API spec generated by NSwag. NSwag will create the operationId based on `${controller}_${method}` naming, in order to ensure unique operationId's in the document.

Example Open API 3 spec:
```
 "/api/Notifications/active": {
      "get": {
        "tags": [
          "Notifications"
        ],
        "operationId": "Notifications_GetActiveNotifications",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Notification"
                  }
                }
              }
            }
          }
        }
      }
    },
```

Will produce the following Service class by openapi-typescript-codegen:
```
export class NotificationsService {

    /**
     * @returns Notification 
     * @throws ApiError
     */
    public static notificationsGetActiveNotifications(): CancelablePromise<Array<Notification>> {
        return __request({
            method: 'GET',
            path: `/api/Notifications/active`,
        });
    }

}
```

I would like to reduce this redunant naming so that notificationsGetActiveNotifications() method is instead named 
GetActiveNotifications().

I'm not sure this can be solved in a generic way, as this `controller_method` operationId naming is just the way NSwag does things, it's not in Open API spec.

If we can have a means of doing custom naming then this can be solved on a per project basis. And that would be awsome.

[]Default NSwag operationId name generator:
https://github.com/RicoSuter/NSwag/blob/002641eb859ebd71ab69435a3f387a762b482abc/src/NSwag.CodeGeneration/OperationNameGenerators/MultipleClientsFromOperationIdOperationNameGenerator.cs#L70

**Comment by ferdikoomen** [comment]
@bardkalbakk you are fixing an issue in the spec with the generator.. I get this is an 'easy' place to fix this, but it's really an issue with the generated spec. Can you inject some 'x-operation-name' keys in there? otherwise we could have a look at those. The PR you have now changes it for everybody, but some might need the name in there, for instance:

`UserService.userInfo()` or `OrdersService.ordersByName()`, we cannot assume we can strip out the "User" or "Orders" part form the operations.

**Comment by bardkalbakk** [comment]
Well in this case we also control the API and spec generation with NSwag, so it was handled there*

I still believe this package would benefit from an option to specify how the TS client are generated, including method names in the services class.  Another example is exporting the service methods directly, instead of exporting service classes with static methods. That way we could benefit from tree-shaking, and reducing the footprint of api usage.

(*)If anyone else needs to manipulate OperationId with NSwag you can do this implementing the IOperationProcessor: https://github.com/RicoSuter/NSwag/wiki/Document-Processors-and-Operation-Processors
