### ISSUE TITLE
Multiple files upload in multipart not correctly prepares formData

### ISSUE THREAD

**Issue by keeema** [ferdikoomen/openapi-typescript-codegen#891]
```json
"requestBody": {
  "description": "File to upload",
  "content": {
    "multipart/form-data": {
      "schema": {
        "type": "object",
        "properties": {
          "filename": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "binary"
            }
          }
        }
      }
    }
  },
  "required": true
  },
```

This is definition for multiple files upload in multipart data.
I this case `formData.append` has to be called for every entry in array `filename`.
Instead there is only one `formData.append` with the whole array.

**Comment by ferdikoomen** [comment]
@keeema Do you have an example that works, since binary can be anything (anything extending a Blob) and this means there is no `fileName` or anything, but `formData.append` needs a key and value. We can either add the array index as key, but this is not always (often) the result we want.

**Comment by keeema** [comment]
If it is array then you can append these blobs with the same key.

**Comment by ferdikoomen** [comment]
@keeema perfect! Just tried it and indeed it works fine 👍 I have pushed a new version to NPM: 0.12.4

**Comment by Rashair** [comment]
Is there an option to provide the `filename`?
