### ISSUE TITLE
Wrong Type Is Generated For Nullable Fields since v0.10.0

### ISSUE THREAD

**Issue by knoefel** [ferdikoomen/openapi-typescript-codegen#892]
Recently i tried to update from `v0.9.3` to `v0.12.3` but after executing the codegen script i got an TS error, because a nullable API field was generated without the `null` option. The first version it won't work anymore is `v.0.10.0`. Here is a screenshot showing the diff between the old version and on the right side after the update. The problematic field has the `"name": "value"`.

![Untitled](https://user-images.githubusercontent.com/2396344/143468715-468666d2-190c-48a1-9a73-2a17d394d622.png)

Additionally here is the relevant section of the `openapi.json` from Swagger: 

```json
{
  "/api/filters/results/grouped/recommendations": {
    "get": {
      "parameters": [
        {
          "in": "query",
          "name": "value",
          "required": false,
          "schema": {
            "type": "string",
            "default": null,
            "nullable": true
          }
        },
       ...
      ],
      ...
    }
  }
}
```

Is there something that has changed since `v0.10.0` that i'm not aware of?

Thx for helping out - unfortunately this a blocker as i wanted to update to have the functionality to cancel promises.

**Comment by ferdikoomen** [comment]
@knoefel Let me have a look, could be a regression. I'll add it to the testcases

**Comment by ferdikoomen** [comment]
Ah yes, could be a regression in the sorting order or the props!

**Comment by ferdikoomen** [comment]
@knoefel I pushed an update into the development branch, I'll upload a new version this week, after i have looked into some formData generation issues.

**Comment by knoefel** [comment]
@ferdikoomen That's great to hear - Thanks so much for the quick help!!
