### ISSUE TITLE
Use different bin name to avoid conflicting `node_modules/.bin/openapi` 

### ISSUE THREAD

**Issue by khanhhuy** [ferdikoomen/openapi-typescript-codegen#905]
Hello, first of all, thank you for building this great package! It'll help me a lot in generating TS types 😃

**Problem**
- Previously, I'm using Redocly to generate a docs page based on the Open API specs https://github.com/Redocly/openapi-cli
- It added a bin inside `node_modules/.bin/` with the same name `openapi`
- When installed `openapi-typescript-codegen` the existing `openapi` bin is overwritten.

**Describe the solution you'd like**
I think `openapi` is a quite common term when developing Open API stuff, so people might use that words frequently. For example: could be a command of an npm package, or it could be an internal command of their project.

So, to avoid conflicts that might happen due to this, it'd be great if we can name-spacing our `openapi` command to be more specific, maybe `typescript-openapi`

Happy to hear your thoughts on this

**Comment by ferdikoomen** [comment]
@khanhhuy the best way to handle these cases is to use `npx`: 

```
npx openapi-typescript-codegen --input ./spec.json --output ./dist
```

**Comment by janstuemmel** [comment]
> @khanhhuy the best way to handle these cases is to use `npx`:
> 
> ```
> npx openapi-typescript-codegen --input ./spec.json --output ./dist
> ```

This does not work. If i install `openapi-typescript-codegen`, then redocly openapi client gets overriden in `.bin` folder. I am not able to use it with a npm script `"build": "openapi ..."`. I have to execute redocly client with `npx`. 

Would appreciate a more verbose naming.

Btw, thanks for this great lib.

**Comment by canvasplay** [comment]
Yes. Having the same issue! Naming the bin as `openapi-typescript-codegen` would be great and would not generate any name conflicts with libraries also working in the openapi ecosystem.
