### ISSUE TITLE
Server side header parameters (Next) 

### ISSUE THREAD

**Issue by mertohancan** [ferdikoomen/openapi-typescript-codegen#907]
In nextjs projects, I also need to send header parameters on the server side. How can I handle this in requests.ts. Anyone have experience?

**Comment by ferdikoomen** [comment]
@mertohancan What kind of headers are you talking about, if you need to send additional headers you can specify them in `
```
OpenAPI.HEADERS = {
   'x-header': 'some-value'
};
```

**Comment by ferdikoomen** [comment]
@mertohancan ?
