### ISSUE TITLE
Document how to output 2 space indent

### ISSUE THREAD

**Issue by mikemaccana** [ferdikoomen/openapi-typescript-codegen#909]
**Describe the bug**
Obviously most JS and TS uses 2 space indent, with JS/TS related tools like prettier, eslint, node, React, jQuery, Svelte, MDN, StackOverflow, TypeScript doc etc. defaulting to two.  I'm sure there's a way to make `openapi-typescript-codegen` generate 2 space indent (if there's not, consider this a feature request), but I can't see it:

```
$ npx openapi --help
Usage: openapi [options]

Options:
  -V, --version             output the version number
  -i, --input <value>       OpenAPI specification, can be a path, url or string content (required)
  -o, --output <value>      Output directory (required)
  -c, --client <value>      HTTP client to generate [fetch, xhr, node, axios] (default: "fetch")
  --useOptions              Use options instead of arguments
  --useUnionTypes           Use union types instead of enums
  --exportCore <value>      Write core files to disk (default: true)
  --exportServices <value>  Write services to disk (default: true)
  --exportModels <value>    Write models to disk (default: true)
  --exportSchemas <value>   Write schemas to disk (default: false)
  --postfix <value>         Service name postfix (default: "Service")
  --request <value>         Path to custom request file
  -h, --help                display help for command
```

How can we make generated TypeScript files look like other 2-space indented TS?

Thanks! 🙂

**Comment by ferdikoomen** [comment]
@mikemaccana The day you worry about 2 spaces, 4 spaces or tabs to indent your code, is the day you probably should stop with development ;-) What i see commonly done is two things:

1. Generate the client and run eslint/prettier over the generated source and then commit it in your repo
2. Exclude the generated files from eslint/prettier/git and ignore any formatting:
    https://prettier.io/docs/en/ignore.html
    https://eslint.org/docs/user-guide/configuring/ignoring-code

But, I just added a new option `--indent` (see readme for info) to satisfy your spacing needs :-)
