### ISSUE TITLE
File model was generated with binary as filename and model definition.

### ISSUE THREAD

**Issue by dannyvi** [ferdikoomen/openapi-typescript-codegen#911]
**File model was generated as binary.**
The model named `File` in the openapi definitions was generated to be `binary` at models and index.ts
```
"definitions": {
  "File": {
    "required": [ "mime" ],
    "type": "object",
    "properties": {
      "id": {
      "title": "Id",
      "type": "string",
      "readOnly": true,
      "minLength": 1
    },
"updated_at": {
"title": "Updated at",
"type": "string",
"format": "date-time",
"readOnly": true
},
"created_at": {
"title": "Created at",
"type": "string",
"format": "date-time",
"readOnly": true
},
"mime": {
"title": "Mime",
"type": "string",
"maxLength": 24,
"minLength": 1
},
"file": {
"title": "File",
"type": "string",
"readOnly": true,
"format": "uri"
}
}
},
}
```
<img width="519" alt="截屏2021-12-10 上午11 54 11" src="https://user-images.githubusercontent.com/25277042/145514614-53876d23-295e-41f0-a446-bc1d897199bf.png">

**Comment by ferdikoomen** [comment]
@dannyvi There is a fix for this in the development branch, once i have fixed a few more issues, i will push a new version to NPM

**Comment by ferdikoomen** [comment]
@dannyvi New version is pushed to NPM 0.13.0 Could you check if that resolves your issue?

**Comment by dannyvi** [comment]
Perfectly resolved my trouble, Thanks a lot!!
