### ISSUE TITLE
Generated Client uses NodeJS exclusive Buffer API

### ISSUE THREAD

**Issue by manuschillerdev** [ferdikoomen/openapi-typescript-codegen#912]
**Describe the bug**
I create the client with the intent of using it in the Browser with the following options:
```json
"scripts": {
    "api:generate-client": "openapi --client axios --input ./src/api/openapi.yml --output ./src/api/client --useOptions --useUnionTypes && prettier --write src/api/client"
}
```

This generates a client that uses a NodeJS exclusive `Buffer` API in the file `core/request.ts`, which leads to a TS Error:
```markdown
TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
```

```typescript
function base64(str: string): string {
  try {
    return btoa(str);
  } catch (err) {
    return Buffer.from(str).toString("base64"); // Buffer does not exist in Browser environments
  }
}
```

Used Versions:
```json
"devDependencies": {
    ...
    "axios": "^0.24.0",
    "cross-blob": "2.0.1",
    "form-data": "4.0.0",
    "openapi-typescript-codegen": "^0.12.5",
    ...
  },
  ```

**Comment by wjdp** [comment]
Have hit this same issue. I don't want to add the types for Node as they're not available in browser.

**Comment by wjdp** [comment]
Instead of installing the types my workaround for now is a `shame.d.ts` file with the following. This only pretends `Buffer` exists, rather than everything in `@types/node`.

```typescript
// Needed due to https://github.com/ferdikoomen/openapi-typescript-codegen/issues/912
// Remove when fixed.
declare const Buffer;
```

**Comment by ferdikoomen** [comment]
@wjdp @manuschillerdev There is a fix for this in the development branch now. Once i have fixed a few more issues i will push a new version to NPM

**Comment by wjdp** [comment]
Fantastic, thanks for the update @ferdikoomen

**Comment by ferdikoomen** [comment]
@wjdp New version is pushed to NPM 0.13.0 Could you check if that resolves your issue?
