### ISSUE TITLE
httpClient for electrons net API

### ISSUE THREAD

**Issue by MaxFichtelmann** [ferdikoomen/openapi-typescript-codegen#928]
Electron includes it's own [HTTP client API](https://www.electronjs.org/docs/latest/api/client-request) that supports stuff like partitioned sessions and proxy handling. It would be incredible, if the `--client` option could be extended to support generating electron based http code.

Would a pull request be welcome?

**Comment by ferdikoomen** [comment]
@MaxFichtelmann Sure, do you know where to start, or do you need a hand?
