### ISSUE TITLE
Option 'postfix' does not exist in type 'Options'(types/index.d.ts)

### ISSUE THREAD

**Issue by asc11cat** [ferdikoomen/openapi-typescript-codegen#934]
**Describe the bug**
Option 'postfix' does not exist in type 'Options'(types/index.d.ts), but exist on cli interface & internal project types.

Fix is awaiting approval at https://github.com/ferdikoomen/openapi-typescript-codegen/pull/933

Thanks!

**Comment by ferdikoomen** [comment]
@asc11cat Merged, will push a new version tonight 0.14.0
