### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by rchl** [ferdikoomen/openapi-typescript-codegen#937]
This project doesn't have a changelog in form of a CHANGELOG.md or Releases page so it's hard to know what has changed when upgrading to new versions and it's not clear whether there are breaking changes.

It would help if the repo at least had tags so we could look at the commits and know to which released versions those correspond. Or at least commit names that clearly indicated the version in the commit summary. This is created by default by `npm version ...` by even that seems to be overridden and done manually.

**Comment by ferdikoomen** [comment]
@rchl I added the first change log and release
