### ISSUE TITLE
[Bug] requestBody in parameters isn't sorted by required 

### ISSUE THREAD

**Issue by songzhi** [ferdikoomen/openapi-typescript-codegen#94]
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/836b5da64df63b9972ae35c1003718172dc60b16/src/openApi/v3/parser/getOperation.ts#L55-L60

The `requestBody` is always the last of parameters.If there's any optional parameter in front of it,there will be an TS error 1016: A required parameter cannot follow an optional parameter.
My simple solution is 
```js
operation.parameters.push(requestBody);
operation.parameters = operation.parameters.sort(sortByRequired);
```

**Comment by ferdikoomen** [comment]
That makes sense!

**Comment by ferdikoomen** [comment]
@songzhi I have pushed a new version (0.1.15) with the changes. Let me know if this works for you.
