### ISSUE TITLE
Generation of client instances creates invalid code when using custom name

### ISSUE THREAD

**Issue by ssams** [ferdikoomen/openapi-typescript-codegen#940]
When using the `--name` option to generate separate client instances, invalid code is generated when using a name different than the value used in the example / readme ("AppClient").

An invokation such as `openapi --input ./openapi.json --output ./src-gen --name DemoClient`  generates in the file `./src-gen/client.ts` the code

```typescript
// [...]
export class DemoClient {
// [...]
```

as expected, but in `./src-gen/index.tx` the wrong (nonexistent) class "AppClient" is referenced:

```typescript
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { AppClient } from './client';
// [...]
```

=> generated `index.ts` should also use the value from the name parameter when exporting the client.

**Comment by asbjornenge** [comment]
I'm seeing this also. Problem is import/export in `index.ts` does not adhere to the custom name 😅 For now I'm solving it using `--name AppClient` 😅 But should be easy to solve this one 👍

**Comment by ferdikoomen** [comment]
@ssams @asbjornenge Thanks! Stupid thing i missed during testing. I have pushed a new 0.16.1 version to NPM
