### ISSUE TITLE
Can't use --name option when using openapi-typescript-codegen as devDependency

### ISSUE THREAD

**Issue by johnsvanda** [ferdikoomen/openapi-typescript-codegen#945]
I have a following script in package.json:
`"generate": "openapi --input ./frontline_api_spec.json --output ./src/frontline-api --client axios --name FrontlineClient"`

When I run it, it goes like this:
![image](https://user-images.githubusercontent.com/39958806/151305585-1427953e-c6e5-43b6-9791-1dc6425c35b0.png)

When I installed it globally it works how it should.

**Comment by ferdikoomen** [comment]
@johnsvanda I just tried it with 0.17.0 inside the devDependencies and all is fine. Could you give me the following details:

- Windows or Mac
- Node version
- `openapi-typescript-codegen` version in `package.json`
-

**Comment by ferdikoomen** [comment]
@johnsvanda ?
