### ISSUE TITLE
Invalid Typescript generated from the public Jira swagger

### ISSUE THREAD

**Issue by matthelliwell2** [ferdikoomen/openapi-typescript-codegen#948]
We are generating Typescript from this swagger: https://developer.atlassian.com/cloud/jira/platform/swagger-v3.json

Command line: npx openapi -i https://developer.atlassian.com/cloud/jira/platform/swagger-v3.json -o src/jira -c node --useOptions --useUnionTypes

Using version "0.18.0"

Invalid Typescript is being generated due to the back ticks in the swagger.

For example, the swagger file includes this description as part of the updateDefaultWorkflow method:

"description": "Returned if the workflow scheme cannot be edited and `updateDraftIfNeeded` is not `true`."

The backticks are kept in generated Typescript so it no longer compiles:

 errors: {
                400: `Returned if the workflow scheme cannot be edited and `updateDraftIfNeeded` is not `true`.`,
                401: `Returned if the authentication credentials are incorrect or missing.`,
                403: `Returned if the user does not have the necessary permission.`,
                404: `Returned if the workflow scheme is not found.`,
            },

**Comment by ferdikoomen** [comment]
@matthelliwell2 Pushed a fix to master branch, will upload 0.18.1 version to NPM in a bit

**Comment by matthelliwell2** [comment]
That was quick, thanks.
