### ISSUE TITLE
[Bug] the required and nullable field in parameter object is overrided by the schema field

### ISSUE THREAD

**Issue by songzhi** [ferdikoomen/openapi-typescript-codegen#95]
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/836b5da64df63b9972ae35c1003718172dc60b16/src/openApi/v3/parser/getOperationParameter.ts#L80
If a operation parameter object like this(in test/sepc.json)
```json
{
    "description": "This is the parameter that goes into the request header",
    "name": "parameterHeader",
    "in": "header",
    "required": true,
    "nullable": true,
    "schema": {
        "type": "string"
    }
}
```
The `required` and `nullable` are true.But the `isRequired` and `isNullable` will be false after executing the code above.Which is wrong in my opinion.
I think the code should be like:
```js
 operationParameter.isRequired =  operationParameter.isRequired || model.default || model.isRequired; 
```

**Comment by ferdikoomen** [comment]
@songzhi I have pushed a new version (0.1.15) with the changes. Let me know if this works for you.
