### ISSUE TITLE
[Feature] Support enumNames-like setting to generate enum with custom names

### ISSUE THREAD

**Issue by songzhi** [ferdikoomen/openapi-typescript-codegen#96]
There's basically tow options.The first is use another field like`enumNames:string[]` in `OpenApiSchema` to generate enums with custom names.
Schema like this:
```json
"state": {
    "title": "State",
    "enum": [
        0,
        1,
        2
    ],
    "type": "integer",
    "default": 0,
    "enumNames": ["initial", "working", "finished"]
}
```
Generated code:
```js
enum state {
  INITIAL = 0,
  WORKING = 1,
  FINISHED = 2
}
```
But enumNames is not a valid openapi schema field.
Another option is expanding the `getEnumFromDescription`.

**Comment by ferdikoomen** [comment]
there is a nice thread here https://github.com/OAI/OpenAPI-Specification/issues/681 some client support the x-enum-varnames. The x- props are extension props in the V3 spec. That might be a semi-supported way to do it.

**Comment by ferdikoomen** [comment]
The code is not hard, I will have a look soon!

**Comment by ferdikoomen** [comment]
@songzhi would the following SPEC work for you?

Example with **x-enum-varnames** and **x-enum-descriptions**

```json
{
    "EnumWithStrings": {
        "description": "This is a simple enum with strings",
        "enum": [
            0,
            1,
            2
        ],
        "x-enum-varnames": [
            "Success",
            "Warning"
            "Error"
        ],
        "x-enum-descriptions": [
            "Used when the status of something is successful",
            "Used when the status of something has a warning"
            "Used when the status of something has an error"
        ]
    }
}
```

**Comment by songzhi** [comment]
@ferdikoomen It's works for me. Thanks for this.

**Comment by ferdikoomen** [comment]
Alright, i will try to implement this in the upcoming days. Keep you posted

**Comment by ferdikoomen** [comment]
I pushed some changes to the master branch, did not publish a new version yet. Feel free to have a look, i will do some final testing tomorrow.

**Comment by ferdikoomen** [comment]
ew version has been pushed (0.1.16) with support for enums
