### ISSUE TITLE
Node Client has runtime error without esModuleInterop enabled

### ISSUE THREAD

**Issue by KiwiKilian** [ferdikoomen/openapi-typescript-codegen#971]
I'm using NestJS (v8) with Node (v16). The default `tsconfig.json` had only `allowSyntheticDefaultImports` enabled but not `esModuleInterop`. Default `tsconfig.json` looks like this:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

With the default config firing a request results in the following error:
```
TypeError: Right-hand side of 'instanceof' is not an object
```

Which points to the return of `isFormData`:
```ts
return value instanceof FormData;
```

I can fix this problem by adding `esModuleInterop: true` to the config which was also discussed in #389. As the [TS docs state](https://www.typescriptlang.org/tsconfig#Interop_Constraints_6252) `allowSyntheticDefaultImports` only fixes the type checking, while `esModuleInterop` actually changes transpilation.

If we can confirm the necessesity of `esModuleInterop: true`, I'm happy to contribute to the [Node-Fetch support docs](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/node-fetch-support.md).

**Comment by ferdikoomen** [comment]
@KiwiKilian for the end-2-end test i am not using esModuleInterop:

```
compilerOptions: {
  target: 'es2020',
  module: 'es2020',
  moduleResolution: 'node',
  lib: ['es2020', 'dom'],
  declaration: false,
  declarationMap: false,
  sourceMap: false,
  noImplicitReturns: true,
  noImplicitThis: true,
  noImplicitAny: true,
  strict: true,
  skipLibCheck: true,
  allowSyntheticDefaultImports: true,
  experimentalDecorators: true,
},
```
But it could be the 'dom' lib that is supporting this behaviour. Could you check if setting:

```
lib: ['es2017', 'dom'],
```
or 
```
esModuleInterop: true,
```
resolves the issue? In that case we need to add it to the documentation, feel free to create a PR for that

**Comment by KiwiKilian** [comment]
I'm puzzled, I currently can't reproduce the problem, even though I tested thoroughly before submitting the issue. Im sorry for bothering, if the problem occurs later on again, I will get back to you.

Thank you for creating this library, I really enjoy using it and makes consuming my APIs a breeze!
