### ISSUE TITLE
Quotation mark in enum text not escaped when generating union types

### ISSUE THREAD

**Issue by davidbruhn** [ferdikoomen/openapi-typescript-codegen#974]
**Describe the bug**
The following enum in my JSON schema:
```
        "enum": [
          "Order won't fit",
          ...
       ]
```

Is converted to a union type that fails because the quotation mark in `won't` is not escaped:
```
export type CancelReason = 'Order won't fit' | ... ;
```

**Comment by ferdikoomen** [comment]
@davidbruhn just pushed a new version with the fix for this (v0.20.0)
