### ISSUE TITLE
Java Number type does not get converted to Typescript number

### ISSUE THREAD

**Issue by tiberiuzuld** [ferdikoomen/openapi-typescript-codegen#979]
Java type Number https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html
does not get converted to Typescript number

```ts
import type { Number } from "./Number";

export type MyType = {
  value?: Number;
};


```

**Comment by ferdikoomen** [comment]
Hi @tiberiuzuld `Number` (With capital) is not a valid OpenAPI type, see: https://swagger.io/docs/specification/data-models/data-types/

**Comment by tiberiuzuld** [comment]
Hi @ferdikoomen ,
Probably you are right in swagger we get:
![image](https://user-images.githubusercontent.com/15310395/157195448-76868d3b-cacc-406d-8883-ff7ee820b97a.png)
Most probably is because our very old version of swagger.
