### ISSUE TITLE
Prefer unions over namespaced enums

### ISSUE THREAD

**Issue by starkysclub** [ferdikoomen/openapi-typescript-codegen#988]
**Describe the solution you'd like**
Hello, love the library and prehaps I don't see the true benefit of current behavior what I'm about to describe, but even in that case, maybe someone else is facing the same question and would like the option

While chosing the useEnums option OpenApi's enums strings defined at the spot (not while referencing them) 
`"paymentMethod": {
        "enum": [
            "BANK_TRANSFER",
            "CARD",
            "CASH"
        ],
        "type": "string"
}`

creates enum in a namespace of the type which is then used like `PaymentInfo.paymentMethod.CASH` in which case I would probably prefer using union instead (while keeping enums elsewhere)

_I have a feeling that this was actually introduced in some of the newer versions of the library, which is why I might just be missing a point.._

**Proposal**
More configuration options of using enums/unions

**Comment by ferdikoomen** [comment]
@starkysclub Did you check the documentation:
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/enum-vs-union-types.md
You can have either enums or union types, not a mix.
