### ISSUE TITLE
Variable Names in CancelablePromise.ts cause iOS safari error

### ISSUE THREAD

**Issue by serajhqi** [ferdikoomen/openapi-typescript-codegen#993]
After implementing the library in my project my stopped working on iOS safari. After remotely inspecting safari in Mac I received the following error in the console:

`Unhandled Promise Rejection: SyntaxError: Invalid character: '#'`

I found out the variables in `CancelablePromise.ts` file cause this issue. So I temporarily fixed the problem:

    sed -i 's/#/_/g' ./api/core/CancelablePromise.ts

**Comment by ferdikoomen** [comment]
@serajhqi Seems like babel / setup issue, the generated code contains ES6 private properties (#variableName) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields
However, we had some issue with these before (sadly), so I will change them for 'regular' privates

**Comment by ferdikoomen** [comment]
@serajhqi I pushed a fix to the main branch, will release version 0.21.0 by the end of today

**Comment by robcecil** [comment]
Hi @ferdikoomen  the changes made in the version (0.21.0) for this seem to have been lost in a merge. Is that intentional ? thanks
